| schema_name | table_name                       | row_count | rls_enabled | primary_keys  | table_comment                                                                                              | created_at                    |
| ----------- | -------------------------------- | --------- | ----------- | ------------- | ---------------------------------------------------------------------------------------------------------- | ----------------------------- |
| public      | app_users                        | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | attachments                      | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | billing_periods                  | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_line_history              | 930       | true        | id            | Audit trail for all changes to budget line items. Automatically populated by trigger.                      | 2025-12-30 05:01:46.075239+00 |
| public      | budget_line_item_history         | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_lines                     | 317       | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_mod_lines                 | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_modification_lines        | -1        | true        | id            | Line items for budget modifications, linked to budget lines                                                | 2025-12-30 05:01:46.075239+00 |
| public      | budget_modifications             | -1        | true        | id            | Budget changes and modifications with approval workflow                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | budget_view_columns              | 756       | true        | id            | Column definitions for each budget view                                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | budget_views                     | 63        | true        | id            | User-defined budget view configurations                                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | change_event_line_items          | -1        | true        | id            | Line items for change events linked to budget lines                                                        | 2025-12-30 05:01:46.075239+00 |
| public      | change_events                    | -1        | true        | id            | Change events tracking potential budget impacts                                                            | 2025-12-30 05:01:46.075239+00 |
| public      | change_order_approvals           | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | change_order_costs               | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | change_order_lines               | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | change_orders                    | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_change_order_lines    | -1        | true        | id            | Line items for commitment change orders                                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_change_orders         | -1        | true        | id            | Change orders for commitments                                                                              | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_changes               | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_lines                 | -1        | true        | id            | Line items for commitments                                                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | commitments                      | -1        | true        | id            | Subcontracts and purchase orders                                                                           | 2025-12-30 05:01:46.075239+00 |
| public      | companies                        | 26        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | company_context                  | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | contacts                         | 340       | false       | id            | CRM                                                                                                        | 2025-12-30 05:01:46.075239+00 |
| public      | contract_billing_periods         | 0         | true        | id            | Billing periods for prime contracts with retention tracking                                                | 2025-12-30 05:01:46.075239+00 |
| public      | contract_change_orders           | 0         | true        | id            | Change orders for prime contracts with approval workflow                                                   | 2025-12-30 05:01:46.075239+00 |
| public      | contract_documents               | 1         | true        | id            | Document attachments for prime contracts stored in Supabase storage                                        | 2025-12-30 05:01:46.075239+00 |
| public      | contract_line_items              | 0         | true        | id            | Line items for prime contracts with auto-calculated totals                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | contract_payments                | 0         | true        | id            | Payment records for prime contracts with approval workflow                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | contract_snapshots               | -1        | true        | id            | Point-in-time snapshots of contract state for historical tracking                                          | 2025-12-30 05:01:46.075239+00 |
| public      | contract_views                   | -1        | true        | id            | Custom user-defined views for filtering and displaying contracts                                           | 2025-12-30 05:01:46.075239+00 |
| public      | contracts                        | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_code_division_updates_audit | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_code_divisions              | 40        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_code_types                  | 6         | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_codes                       | 310       | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_factors                     | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_forecasts                   | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | daily_log_equipment              | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | daily_log_manpower               | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |