| schema_name | table_name                       | row_count | rls_enabled | primary_keys  | table_comment                                                                                              | created_at                    |
| ----------- | -------------------------------- | --------- | ----------- | ------------- | ---------------------------------------------------------------------------------------------------------- | ----------------------------- |
| drizzle     | __drizzle_migrations             | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| extensions  | wrappers_fdw_stats               | 1         | false       | fdw_name      | Wrappers Foreign Data Wrapper statistics                                                                   | 2025-12-30 05:01:46.075239+00 |
| net         | _http_response                   | -1        | false       | null          | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| net         | http_request_queue               | 0         | false       | null          | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| next_auth   | accounts                         | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| next_auth   | sessions                         | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| next_auth   | users                            | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| next_auth   | verification_tokens              | -1        | false       | token         | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| pgmq        | meta                             | -1        | false       | null          | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| private     | document_processing_queue        | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | __drizzle_migrations             | -1        | false       | hash          | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | ai_analysis_jobs                 | -1        | false       | id            | Tracking AI analysis jobs and their results for submittals                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | ai_insights                      | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | ai_models                        | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | ai_tasks                         | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | app_users                        | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | asrs_blocks                      | 476       | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | asrs_configurations              | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | asrs_decision_matrix             | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | asrs_logic_cards                 | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | asrs_protection_rules            | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | asrs_sections                    | 70        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | attachments                      | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | billing_periods                  | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | block_embeddings                 | -1        | false       | block_id      | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | briefing_runs                    | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_line_history              | 930       | true        | id            | Audit trail for all changes to budget line items. Automatically populated by trigger.                      | 2025-12-30 05:01:46.075239+00 |
| public      | budget_line_item_history         | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_lines                     | 317       | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_mod_lines                 | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | budget_modification_lines        | -1        | true        | id            | Line items for budget modifications, linked to budget lines                                                | 2025-12-30 05:01:46.075239+00 |
| public      | budget_modifications             | -1        | true        | id            | Budget changes and modifications with approval workflow                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | budget_view_columns              | 756       | true        | id            | Column definitions for each budget view                                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | budget_views                     | 63        | true        | id            | User-defined budget view configurations                                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | change_event_line_items          | -1        | true        | id            | Line items for change events linked to budget lines                                                        | 2025-12-30 05:01:46.075239+00 |
| public      | change_events                    | -1        | true        | id            | Change events tracking potential budget impacts                                                            | 2025-12-30 05:01:46.075239+00 |
| public      | change_order_approvals           | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | change_order_costs               | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | change_order_lines               | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | change_orders                    | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_history                     | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_messages                    | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_sessions                    | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_thread_attachment_files     | -1        | false       | attachment_id | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_thread_attachments          | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_thread_feedback             | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_thread_items                | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chat_threads                     | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chats                            | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | chunks                           | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | clients                          | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | code_examples                    | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_change_order_lines    | -1        | true        | id            | Line items for commitment change orders                                                                    | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_change_orders         | -1        | true        | id            | Change orders for commitments                                                                              | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_changes               | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | commitment_lines                 | -1        | true        | id            | Line items for commitments                                                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | commitments                      | -1        | true        | id            | Subcontracts and purchase orders                                                                           | 2025-12-30 05:01:46.075239+00 |
| public      | companies                        | 26        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | company_context                  | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | contacts                         | 340       | false       | id            | CRM                                                                                                        | 2025-12-30 05:01:46.075239+00 |
| public      | contract_billing_periods         | 0         | true        | id            | Billing periods for prime contracts with retention tracking                                                | 2025-12-30 05:01:46.075239+00 |
| public      | contract_change_orders           | 0         | true        | id            | Change orders for prime contracts with approval workflow                                                   | 2025-12-30 05:01:46.075239+00 |
| public      | contract_documents               | 1         | true        | id            | Document attachments for prime contracts stored in Supabase storage                                        | 2025-12-30 05:01:46.075239+00 |
| public      | contract_line_items              | 0         | true        | id            | Line items for prime contracts with auto-calculated totals                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | contract_payments                | 0         | true        | id            | Payment records for prime contracts with approval workflow                                                 | 2025-12-30 05:01:46.075239+00 |
| public      | contract_snapshots               | -1        | true        | id            | Point-in-time snapshots of contract state for historical tracking                                          | 2025-12-30 05:01:46.075239+00 |
| public      | contract_views                   | -1        | true        | id            | Custom user-defined views for filtering and displaying contracts                                           | 2025-12-30 05:01:46.075239+00 |
| public      | contracts                        | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | conversations                    | -1        | true        | session_id    | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_code_division_updates_audit | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_code_divisions              | 40        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_code_types                  | 6         | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_codes                       | 310       | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_factors                     | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | cost_forecasts                   | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | crawled_pages                    | -1        | true        | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | daily_log_equipment              | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |
| public      | daily_log_manpower               | -1        | false       | id            | null                                                                                                       | 2025-12-30 05:01:46.075239+00 |