# Supabse Tables

| table_name                       |
| -------------------------------- |
| Prospects                        |
| __drizzle_migrations             |
| ai_analysis_jobs                 |
| ai_insights                      |
| ai_models                        |
| ai_tasks                         |
| app_users                        |
| archon_code_examples             |
| archon_crawled_pages             |
| archon_document_versions         |
| archon_project_sources           |
| archon_projects                  |
| archon_prompts                   |
| archon_settings                  |
| archon_sources                   |
| archon_tasks                     |
| asrs_blocks                      |
| asrs_configurations              |
| asrs_decision_matrix             |
| asrs_logic_cards                 |
| asrs_protection_rules            |
| asrs_sections                    |
| attachments                      |
| billing_periods                  |
| block_embeddings                 |
| briefing_runs                    |
| budget_codes                     |
| budget_items                     |
| budget_line_items                |
| budget_modifications             |
| budget_snapshots                 |
| change_event_line_items          |
| change_events                    |
| change_order_approvals           |
| change_order_costs               |
| change_order_line_items          |
| change_order_lines               |
| change_orders                    |
| chat_history                     |
| chat_messages                    |
| chat_sessions                    |
| chat_thread_attachment_files     |
| chat_thread_attachments          |
| chat_thread_feedback             |
| chat_thread_items                |
| chat_threads                     |
| chats                            |
| chunks                           |
| clients                          |
| code_examples                    |
| commitment_changes               |
| commitments                      |
| companies                        |
| company_context                  |
| contacts                         |
| contracts                        |
| conversations                    |
| cost_code_division_updates_audit |
| cost_code_divisions              |
| cost_code_types                  |
| cost_codes                       |
| cost_factors                     |
| cost_forecasts                   |
| crawled_pages                    |
| daily_log_equipment              |
| daily_log_manpower               |
| daily_log_notes                  |
| daily_logs                       |
| daily_recaps                     |
| decisions                        |
| design_recommendations           |
| direct_cost_line_items           |
| direct_costs                     |
| discrepancies                    |
| document_chunks                  |
| document_executive_summaries     |
| document_group_access            |
| document_insights                |
| document_metadata                |
| document_rows                    |
| document_user_access             |
| documents                        |
| employees                        |
| erp_sync_log                     |
| files                            |
| financial_contracts              |
| fireflies_ingestion_jobs         |
| fm_blocks                        |
| fm_cost_factors                  |
| fm_documents                     |
| fm_form_submissions              |
| fm_global_figures                |
| fm_global_tables                 |
| fm_optimization_rules            |
| fm_optimization_suggestions      |
| fm_sections                      |
| fm_sprinkler_configs             |
| fm_table_vectors                 |
| fm_text_chunks                   |
| forecasting                      |