# Supabase Database Tables

| table_schema | table_name                   |
| ------------ | ---------------------------- |
| auth         | audit_log_entries            |
| auth         | flow_state                   |
| auth         | identities                   |
| auth         | instances                    |
| auth         | mfa_amr_claims               |
| auth         | mfa_challenges               |
| auth         | mfa_factors                  |
| auth         | oauth_authorizations         |
| auth         | oauth_clients                |
| auth         | oauth_consents               |
| auth         | one_time_tokens              |
| auth         | refresh_tokens               |
| auth         | saml_providers               |
| auth         | saml_relay_states            |
| auth         | schema_migrations            |
| auth         | sessions                     |
| auth         | sso_domains                  |
| auth         | sso_providers                |
| auth         | users                        |
| cron         | job                          |
| cron         | job_run_details              |
| drizzle      | __drizzle_migrations         |
| extensions   | wrappers_fdw_stats           |
| net          | _http_response               |
| net          | http_request_queue           |
| next_auth    | accounts                     |
| next_auth    | sessions                     |
| next_auth    | users                        |
| next_auth    | verification_tokens          |
| pgmq         | meta                         |
| private      | document_processing_queue    |
| public       | Prospects                    |
| public       | __drizzle_migrations         |
| public       | ai_analysis_jobs             |
| public       | ai_insights                  |
| public       | ai_models                    |
| public       | ai_tasks                     |
| public       | app_users                    |
| public       | archon_code_examples         |
| public       | archon_crawled_pages         |
| public       | archon_document_versions     |
| public       | archon_project_sources       |
| public       | archon_projects              |
| public       | archon_prompts               |
| public       | archon_settings              |
| public       | archon_sources               |
| public       | archon_tasks                 |
| public       | asrs_blocks                  |
| public       | asrs_configurations          |
| public       | asrs_decision_matrix         |
| public       | asrs_logic_cards             |
| public       | asrs_protection_rules        |
| public       | asrs_sections                |
| public       | attachments                  |
| public       | billing_periods              |
| public       | block_embeddings             |
| public       | briefing_runs                |
| public       | budget_items                 |
| public       | budget_modifications         |
| public       | budget_snapshots             |
| public       | change_event_line_items      |
| public       | change_events                |
| public       | change_order_approvals       |
| public       | change_order_costs           |
| public       | change_order_lines           |
| public       | change_orders                |
| public       | chat_history                 |
| public       | chat_messages                |
| public       | chat_sessions                |
| public       | chat_thread_attachment_files |
| public       | chat_thread_attachments      |
| public       | chat_thread_feedback         |
| public       | chat_thread_items            |
| public       | chat_threads                 |
| public       | chats                        |
| public       | chunks                       |
| public       | clients                      |
| public       | code_examples                |
| public       | commitment_changes           |
| public       | commitments                  |
| public       | companies                    |
| public       | company_context              |
| public       | contacts                     |
| public       | contracts                    |
| public       | conversations                |
| public       | cost_codes                   |
| public       | cost_factors                 |
| public       | cost_forecasts               |
| public       | crawled_pages                |
| public       | daily_log_equipment          |
| public       | daily_log_manpower           |
| public       | daily_log_notes              |
| public       | daily_logs                   |
| public       | daily_recaps                 |
| public       | decisions                    |
| public       | design_recommendations       |
| public       | direct_costs                 |
| public       | discrepancies                |
| public       | document_chunks              |
| public       | document_executive_summaries |