import { existsSync, readFileSync, readdirSync } from "fs";
import { join } from "path";

import { DOCUMENT_TYPE_OPTIONS, documentTypeLabel } from "../document-types";

/**
 * Guardrail: the documents page filter/inline-edit/label all read from
 * DOCUMENT_TYPE_OPTIONS. The DocumentPicker (commitments, change orders,
 * companies, …) writes taxonomy type_keys into document_metadata.document_type,
 * which the documents page then reads. If a manually-attachable taxonomy type
 * is missing from DOCUMENT_TYPE_OPTIONS it renders as a raw key and can't be
 * filtered or set — the exact bug that hid W-9 and COI on the documents page.
 *
 * This test parses the document_type_taxonomy insert migrations and fails if a
 * manually-attachable (source_system-null) type_key is not represented in
 * DOCUMENT_TYPE_OPTIONS. Auto-generated communication types (those carrying a
 * source_system such as graph_email / graph_teams / fireflies) are excluded —
 * users never set them by hand, so they don't belong in the dropdown.
 */

const MIGRATIONS_DIR = join(__dirname, "../../../../../supabase/migrations");

// Row shape in the seed migration:
//   ('type_key','Display','category',array['x','y'],<source_system>,<sort>)
// where <source_system> is `null` or a quoted string. Later migrations omit the
// source_system column entirely (using is_active instead) — those rows are all
// manual types, so treat a missing source_system as null.
const SEED_ROW = new RegExp(
  "\\(\\s*'([a-z0-9_]+)'" + // 1: type_key
    "\\s*,\\s*'[^']*'" + // display_name
    "\\s*,\\s*'[^']*'" + // category
    "\\s*,\\s*(?:array|ARRAY)\\s*\\[[^\\]]*\\]" + // applies_to
    "\\s*,\\s*(null|'[^']*'|true|false)" + // 2: source_system OR is_active
    "\\s*,\\s*\\d+\\s*\\)",
  "gi",
);

function collectManuallyAttachableTaxonomyKeys(): Set<string> {
  const keys = new Set<string>();
  const files = readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith(".sql"));

  for (const file of files) {
    const sql = readFileSync(join(MIGRATIONS_DIR, file), "utf8");
    if (!/insert\s+into\s+(public\.)?document_type_taxonomy/i.test(sql)) continue;

    for (const match of sql.matchAll(SEED_ROW)) {
      const typeKey = match[1];
      const fifthCol = match[2].toLowerCase();
      // A quoted 5th column in the seed migration is a source_system value
      // (auto-generated type) → excluded. `null`, `true`, `false` all mean
      // "manually attachable" for our purposes.
      const isAutoGenerated =
        fifthCol.startsWith("'") && fifthCol !== "'null'";
      if (!isAutoGenerated) keys.add(typeKey);
    }
  }

  return keys;
}

describe("DOCUMENT_TYPE_OPTIONS ↔ document_type_taxonomy parity", () => {
  it("resolves the migrations directory", () => {
    expect(existsSync(MIGRATIONS_DIR)).toBe(true);
  });

  it("covers every manually-attachable taxonomy type_key", () => {
    const optionValues = new Set(DOCUMENT_TYPE_OPTIONS.map((o) => o.value));
    const taxonomyKeys = collectManuallyAttachableTaxonomyKeys();

    // Sanity: the parser must find the compliance types that motivated this test.
    expect(taxonomyKeys.has("w9")).toBe(true);
    expect(taxonomyKeys.has("insurance_certificate")).toBe(true);

    const missing = [...taxonomyKeys].filter((k) => !optionValues.has(k)).sort();
    expect(missing).toEqual([]);
  });

  it("has a friendly label for every option (no raw keys shown)", () => {
    for (const option of DOCUMENT_TYPE_OPTIONS) {
      expect(documentTypeLabel(option.value)).toBe(option.label);
    }
  });
});
