import { test, expect } from '@playwright/test';

const PROJECT_ID = 67;
const FORM_PATH = `/${PROJECT_ID}/prime-contracts/new`;

test.describe('Prime Contracts Form', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(FORM_PATH);
    await page.waitForLoadState('networkidle');
  });

  test('renders the general information panel', async ({ page }) => {
    await expect(
      page.getByRole('heading', { name: /new prime contract/i }),
    ).toBeVisible();

    await expect(
      page.getByRole('heading', { name: /general information/i }),
    ).toBeVisible();

    await expect(page.getByLabel('Contract #')).toBeVisible();
    await expect(page.getByLabel('Title')).toBeVisible();
    await expect(page.getByRole('button', { name: /status/i })).toBeVisible();
    await expect(
      page.locator('div[data-placeholder="Enter contract description..."]'),
    ).toBeVisible();
    await expect(page.getByLabel('Default Retainage')).toHaveValue('10');
  });

  test('submits the form and hits the contracts API', async ({ page }) => {
    const contractNumber = `PC-E2E-${Date.now()}`;
    await page.getByLabel('Contract #').fill(contractNumber);
    await page.getByLabel('Title').fill('Playwright Prime Contract');

    await page.getByRole('button', { name: /status/i }).click();
    await page.getByRole('option', { name: /draft/i }).click();

    await page.locator('div[data-placeholder="Enter contract description..."]').click();
    await page.keyboard.type('Automated description generated by Playwright.');

    await page.getByLabel('Default Retainage').fill('10');

    const createButton = page.getByRole('button', { name: /^Create$/i });

    const [response] = await Promise.all([
      page.waitForResponse(
        (res) =>
          res.url().includes(`/api/projects/${PROJECT_ID}/contracts`) &&
          res.request().method() === 'POST',
      ),
      createButton.click(),
    ]);

    expect(response.ok()).toBeTruthy();
    const payload = await response.request().postDataJSON();
    expect(payload.contract_number).toBe(contractNumber);
    expect(payload.title).toBe('Playwright Prime Contract');
    expect(payload.status).toBe('draft');

    await page.waitForLoadState('networkidle');
    await expect(page).toHaveURL(
      new RegExp(`/${PROJECT_ID}/prime-contracts/\\w+`),
    );
  });
});
