"""
Email service — sends emails via Resend REST API.

Uses httpx (already in requirements) for HTTP calls.
Falls back gracefully if RESEND_API_KEY is not configured.
"""
from __future__ import annotations

import logging
import os
from typing import Any, Dict, List, Optional

import httpx

logger = logging.getLogger(__name__)

RESEND_API_URL = "https://api.resend.com/emails"


def _get_api_key() -> Optional[str]:
    return os.getenv("RESEND_API_KEY")


def _get_from_address() -> str:
    return os.getenv("DIGEST_FROM_EMAIL", "ai@alleato.io")


def send_email(
    to_emails: List[str],
    subject: str,
    html_content: str,
    text_content: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Send an email via Resend.

    Returns dict with success bool and response data or error message.
    """
    api_key = _get_api_key()
    if not api_key:
        logger.warning("[Email] RESEND_API_KEY not set — skipping email send")
        return {"success": False, "error": "RESEND_API_KEY not configured"}

    if not to_emails:
        return {"success": False, "error": "No recipients provided"}

    payload: Dict[str, Any] = {
        "from": _get_from_address(),
        "to": to_emails,
        "subject": subject,
        "html": html_content,
    }
    if text_content:
        payload["text"] = text_content

    try:
        response = httpx.post(
            RESEND_API_URL,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=30.0,
        )
        if response.status_code in (200, 201):
            logger.info(
                "[Email] Sent to %d recipients: %s",
                len(to_emails), subject,
            )
            return {"success": True, "data": response.json()}
        else:
            logger.error(
                "[Email] Failed (%d): %s",
                response.status_code, response.text,
            )
            return {
                "success": False,
                "error": f"HTTP {response.status_code}: {response.text}",
            }
    except Exception as e:
        logger.error("[Email] Exception: %s", e)
        return {"success": False, "error": str(e)}


def send_digest_email(
    to_emails: List[str],
    meeting_title: str,
    meeting_date: str,
    digest_html: str,
) -> Dict[str, Any]:
    """Send a post-meeting digest email with branded template."""
    subject = f"Meeting Digest: {meeting_title} — {meeting_date}"
    html = _wrap_digest_html(digest_html, meeting_title, meeting_date)
    return send_email(to_emails, subject, html)


def send_daily_recap_email(
    to_emails: List[str],
    date_str: str,
    recap_html: str,
    meeting_count: int,
) -> Dict[str, Any]:
    """Send a daily recap email."""
    subject = f"Daily Project Pulse — {date_str}"
    html = _wrap_recap_html(recap_html, date_str, meeting_count)
    return send_email(to_emails, subject, html)


def _wrap_digest_html(
    body: str, title: str, date: str
) -> str:
    return f"""
<div style="max-width:700px;margin:0 auto;font-family:-apple-system,\
BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;">
  <div style="background:#1e3a5f;color:white;padding:24px 32px;\
border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:20px;">Post-Meeting Digest</h1>
    <p style="margin:8px 0 0;opacity:0.85;font-size:14px;">\
{title} &mdash; {date}</p>
  </div>
  <div style="padding:24px 32px;background:#ffffff;border:1px solid #e5e7eb;\
border-top:none;border-radius:0 0 8px 8px;">
    {body}
  </div>
  <p style="text-align:center;font-size:12px;color:#9ca3af;margin-top:16px;">
    Generated by Alleato AI
  </p>
</div>"""


def _wrap_recap_html(
    body: str, date: str, meeting_count: int
) -> str:
    return f"""
<div style="max-width:700px;margin:0 auto;font-family:-apple-system,\
BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;">
  <div style="background:#1e3a5f;color:white;padding:24px 32px;\
border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:20px;">Daily Project Pulse</h1>
    <p style="margin:8px 0 0;opacity:0.85;font-size:14px;">\
{date} &mdash; {meeting_count} meetings analyzed</p>
  </div>
  <div style="padding:24px 32px;background:#ffffff;border:1px solid #e5e7eb;\
border-top:none;border-radius:0 0 8px 8px;">
    {body}
  </div>
  <p style="text-align:center;font-size:12px;color:#9ca3af;margin-top:16px;">
    Generated by Alleato AI
  </p>
</div>"""
