export interface Project {
  id: number;
  created_at: string;
  name: string | null;
  job_number: string | null;
  start_date: string | null;
  est_completion_date: string | null;
  est_revenue: number | null;
  est_profit: number | null;
  address: string | null;
  onedrive: string | null;
  phase: string | null;
  state: string | null;
  category: string | null;
  aliases: string[] | null;
  team_members: string[] | null;
  stage: string | null;
  completion_percentage: number | null;
  budget: number | null;
  budget_used: number | null;
  client: string | null;
  summary: string | null;
  summary_metadata: Record<string, unknown> | null;
  summary_updated_at: string | null;
  health_score: number | null;
  health_status: "Healthy" | "At Risk" | "Needs Attention" | "Critical" | null;
  access: string | null;
  archived: boolean;
  archived_by: string | null;
  archived_at: string | null;
  erp_system: string | null;
  erp_last_job_cost_sync: string | null;
  erp_last_direct_cost_sync: string | null;
  erp_sync_status: string | null;
}
