/**
 * ============================================================================
 * POTENTIAL CHANGE ORDERS (PCO) API ROUTE (Collection-Level)
 * ============================================================================
 *
 * GET  /api/projects/[projectId]/pcos - List PCOs with filters
 * POST /api/projects/[projectId]/pcos - Create new PCO
 *
 * Schema Reference: potential_change_orders table
 * - id: bigint (PK)
 * - project_id: bigint (FK to projects)
 * - number, title, description, type, status
 * - current_version, estimated_value, approved_value
 * - markup_percentage, schedule_impact_days, schedule_impact_description
 * - rfq_required, rfq_status, annotation, annotation_note, root_cause
 * - prime_change_order_id, created_by_id (uuid)
 * - created_at, updated_at, submitted_at, approved_at
 */

import { withApiGuardrails } from "@/lib/guardrails/api";
import { GuardrailError } from "@/lib/guardrails/errors";
import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import { apiErrorResponse } from "@/lib/api-error";
import { requirePermission } from "@/lib/permissions-guard";

interface RouteParams {
  params: Promise<{ projectId: string }>;
}

/**
 * GET /api/projects/[projectId]/pcos
 * Returns list of PCOs for a project with optional filters
 *
 * Query Parameters:
 * - status: Filter by status (DRAFT, SUBMITTED, APPROVED, REVISION_REQUESTED, VOID)
 * - type: Filter by type
 * - search: Search number/title/description
 */
export const GET = withApiGuardrails(
  "projects/[projectId]/pcos#GET",
  async ({ request, params }) => {
  
    const { projectId } = await params;
    const numericProjectId = parseInt(projectId, 10);

    if (isNaN(numericProjectId)) {
      return NextResponse.json({ error: "Invalid project ID" }, { status: 400 });
    }

    const supabase = await createClient();
    const { searchParams } = new URL(request.url);

    const status = searchParams.get("status");
    const type = searchParams.get("type");
    const search = searchParams.get("search");

    let query = supabase
      .from("potential_change_orders")
      .select("*", { count: "exact" })
      .eq("project_id", numericProjectId)
      .order("created_at", { ascending: false });

    if (status) {
      query = query.eq("status", status);
    }

    if (type) {
      query = query.eq("type", type);
    }

    if (search) {
      // Sanitize to prevent PostgREST filter injection: allow only alphanumeric, spaces, hyphens, underscores
      const sanitizedSearch = search.replace(/[^a-zA-Z0-9\s\-_]/g, "");
      if (sanitizedSearch) {
        query = query.or(
          `number.ilike.%${sanitizedSearch}%,title.ilike.%${sanitizedSearch}%,description.ilike.%${sanitizedSearch}%`
        );
      }
    }

    const { data, error, count } = await query;

    if (error) {
      console.error("Failed to fetch PCOs:", error);
      return apiErrorResponse(error);
    }

    // Batch-fetch change event and line item counts (no FK join available for pco_line_items).
    // `pco_change_events.pco_id` is a number; `pco_line_items.pco_id` is a string.
    const pcoIdStrings = (data || []).map((pco: Record<string, unknown>) => String(pco.id));
    const pcoIdNumbers = pcoIdStrings
      .map((id) => Number(id))
      .filter((n) => Number.isFinite(n));
    const ceCountMap: Record<string, number> = {};
    const liCountMap: Record<string, number> = {};

    if (pcoIdStrings.length > 0) {
      const [ceResult, liResult] = await Promise.all([
        supabase.from("pco_change_events").select("pco_id").in("pco_id", pcoIdNumbers),
        supabase.from("pco_line_items").select("pco_id").in("pco_id", pcoIdStrings),
      ]);

      if (ceResult.data) {
        for (const row of ceResult.data) {
          const id = String(row.pco_id);
          ceCountMap[id] = (ceCountMap[id] || 0) + 1;
        }
      }
      if (liResult.data) {
        for (const row of liResult.data) {
          const id = String(row.pco_id);
          liCountMap[id] = (liCountMap[id] || 0) + 1;
        }
      }
    }

    const pcos = (data || []).map((pco: Record<string, unknown>) => ({
      ...pco,
      changeEventsCount: ceCountMap[String(pco.id)] ?? 0,
      lineItemsCount: liCountMap[String(pco.id)] ?? 0,
    }));

    return NextResponse.json({
      data: pcos,
      meta: { total: count || 0 },
    });
    },
);

/**
 * POST /api/projects/[projectId]/pcos
 * Creates a new PCO (number auto-generated by DB trigger)
 *
 * Request Body:
 * - title (required): string
 * - description?: string
 * - type?: string
 * - estimated_value?: number
 * - markup_percentage?: number
 * - schedule_impact_days?: number
 * - schedule_impact_description?: string
 * - rfq_required?: boolean
 * - root_cause?: string
 * - annotation?: string
 * - annotation_note?: string
 * - prime_change_order_id?: number
 */
export const POST = withApiGuardrails(
  "projects/[projectId]/pcos#POST",
  async ({ request, params }) => {
  
    const { projectId } = await params;
    const numericProjectId = parseInt(projectId, 10);

    if (isNaN(numericProjectId)) {
      return NextResponse.json({ error: "Invalid project ID" }, { status: 400 });
    }

    const guard = await requirePermission(numericProjectId, "change_orders", "write");
    if (guard.denied) return guard.response;

    const supabase = await createClient();
    const body = await request.json();

    // Get current user
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: "Unauthorized", details: authError?.message },
        { status: 401 }
      );
    }

    if (!body.title || typeof body.title !== "string" || !body.title.trim()) {
      return NextResponse.json(
        { error: "Validation error", details: "title is required" },
        { status: 400 }
      );
    }

    // Generate next PCO number for this project if not provided
    let pcoNumber: string | undefined = body.number;
    if (!pcoNumber) {
      const { data: latest } = await supabase
        .from("potential_change_orders")
        .select("number")
        .eq("project_id", numericProjectId)
        .order("id", { ascending: false })
        .limit(1);
      const prev = Number(latest?.[0]?.number);
      pcoNumber = Number.isFinite(prev) && prev > 0
        ? String(Math.floor(prev) + 1).padStart(3, "0")
        : "001";
    }

    // Only include columns that exist on `potential_change_orders`.
    // Legacy fields (change_reason, location, reference, request_received_from,
    // due_date, is_private, field_change, paid_in_full) are no longer on this
    // table and are ignored.
    const insertData = {
      project_id: numericProjectId,
      number: pcoNumber,
      title: body.title.trim(),
      description: body.description || null,
      type: body.type || "Client",
      status: "DRAFT",
      current_version: 1,
      estimated_value: body.estimated_value ?? null,
      markup_percentage: body.markup_percentage ?? null,
      schedule_impact_days: body.schedule_impact_days ?? null,
      schedule_impact_description: body.schedule_impact_description || null,
      rfq_required: body.rfq_required ?? false,
      root_cause: body.root_cause || null,
      annotation: body.annotation || null,
      annotation_note: body.annotation_note || null,
      prime_change_order_id: body.prime_change_order_id ?? null,
      created_by_id: user.id,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    const { data, error } = await supabase
      .from("potential_change_orders")
      .insert(insertData)
      .select()
      .single();

    if (error) {
      console.error("Failed to create PCO:", error);
      return apiErrorResponse(error);
    }

    // Write timeline event
    await supabase.from("timeline_events").insert({
      project_id: numericProjectId,
      parent_type: "PCO",
      parent_id: data.id.toString(),
      event_type: "CREATED",
      actor_id: user.id,
      summary: `PCO "${data.title}" created`,
      created_at: new Date().toISOString(),
    });

    return NextResponse.json(data, { status: 201 });
    },
);
