/**
 * ============================================================================
 * POTENTIAL CHANGE ORDERS (PCO) API ROUTE (Collection-Level)
 * ============================================================================
 *
 * GET  /api/projects/[projectId]/pcos - List PCOs with filters
 * POST /api/projects/[projectId]/pcos - Create new PCO
 *
 * Schema Reference: potential_change_orders table
 * - id: bigint (PK)
 * - project_id: bigint (FK to projects)
 * - number, title, description, type, status
 * - current_version, estimated_value, approved_value
 * - markup_percentage, schedule_impact_days, schedule_impact_description
 * - rfq_required, rfq_status, annotation, annotation_note, root_cause
 * - prime_change_order_id, created_by_id (uuid)
 * - created_at, updated_at, submitted_at, approved_at
 */

import { createClient } from "@/lib/supabase/server";
import { NextRequest, NextResponse } from "next/server";
import { apiErrorResponse } from "@/lib/api-error";
import { requirePermission } from "@/lib/permissions-guard";

interface RouteParams {
  params: Promise<{ projectId: string }>;
}

/**
 * GET /api/projects/[projectId]/pcos
 * Returns list of PCOs for a project with optional filters
 *
 * Query Parameters:
 * - status: Filter by status (DRAFT, SUBMITTED, APPROVED, REVISION_REQUESTED, VOID)
 * - type: Filter by type
 * - search: Search number/title/description
 */
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { projectId } = await params;
    const numericProjectId = parseInt(projectId, 10);

    if (isNaN(numericProjectId)) {
      return NextResponse.json({ error: "Invalid project ID" }, { status: 400 });
    }

    const supabase = await createClient();
    const { searchParams } = new URL(request.url);

    const status = searchParams.get("status");
    const type = searchParams.get("type");
    const search = searchParams.get("search");

    let query = supabase
      .from("potential_change_orders")
      .select(
        `
        *,
        pco_change_events(count),
        pco_line_items(count)
      `,
        { count: "exact" }
      )
      .eq("project_id", numericProjectId)
      .order("created_at", { ascending: false });

    if (status) {
      query = query.eq("status", status);
    }

    if (type) {
      query = query.eq("type", type);
    }

    if (search) {
      // Sanitize to prevent PostgREST filter injection: allow only alphanumeric, spaces, hyphens, underscores
      const sanitizedSearch = search.replace(/[^a-zA-Z0-9\s\-_]/g, "");
      if (sanitizedSearch) {
        query = query.or(
          `number.ilike.%${sanitizedSearch}%,title.ilike.%${sanitizedSearch}%,description.ilike.%${sanitizedSearch}%`
        );
      }
    }

    const { data, error, count } = await query;

    if (error) {
      console.error("Failed to fetch PCOs:", error);
      return apiErrorResponse(error);
    }

    const pcos = (data || []).map((pco: any) => ({
      ...pco,
      changeEventsCount: pco.pco_change_events?.[0]?.count ?? 0,
      lineItemsCount: pco.pco_line_items?.[0]?.count ?? 0,
    }));

    return NextResponse.json({
      data: pcos,
      meta: { total: count || 0 },
    });
  } catch (error) {
    return apiErrorResponse(error);
  }
}

/**
 * POST /api/projects/[projectId]/pcos
 * Creates a new PCO (number auto-generated by DB trigger)
 *
 * Request Body:
 * - title (required): string
 * - description?: string
 * - type?: string
 * - estimated_value?: number
 * - markup_percentage?: number
 * - schedule_impact_days?: number
 * - schedule_impact_description?: string
 * - rfq_required?: boolean
 * - root_cause?: string
 * - annotation?: string
 * - annotation_note?: string
 * - prime_change_order_id?: number
 */
export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const { projectId } = await params;
    const numericProjectId = parseInt(projectId, 10);

    if (isNaN(numericProjectId)) {
      return NextResponse.json({ error: "Invalid project ID" }, { status: 400 });
    }

    const guard = await requirePermission(numericProjectId, "change_orders", "write");
    if (guard.denied) return guard.response;

    const supabase = await createClient();
    const body = await request.json();

    // Get current user
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: "Unauthorized", details: authError?.message },
        { status: 401 }
      );
    }

    if (!body.title || typeof body.title !== "string" || !body.title.trim()) {
      return NextResponse.json(
        { error: "Validation error", details: "title is required" },
        { status: 400 }
      );
    }

    const insertData: Record<string, any> = {
      project_id: numericProjectId,
      title: body.title.trim(),
      description: body.description || null,
      type: body.type || null,
      status: "DRAFT",
      current_version: 1,
      estimated_value: body.estimated_value ?? null,
      markup_percentage: body.markup_percentage ?? null,
      schedule_impact_days: body.schedule_impact_days ?? null,
      schedule_impact_description: body.schedule_impact_description || null,
      rfq_required: body.rfq_required ?? false,
      root_cause: body.root_cause || null,
      annotation: body.annotation || null,
      annotation_note: body.annotation_note || null,
      prime_change_order_id: body.prime_change_order_id ?? null,
      change_reason: body.change_reason || null,
      location: body.location || null,
      reference: body.reference || null,
      request_received_from: body.request_received_from || null,
      due_date: body.due_date || null,
      is_private: body.is_private ?? false,
      field_change: body.field_change ?? false,
      paid_in_full: body.paid_in_full ?? false,
      created_by_id: user.id,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    const { data, error } = await supabase
      .from("potential_change_orders")
      .insert(insertData)
      .select()
      .single();

    if (error) {
      console.error("Failed to create PCO:", error);
      return apiErrorResponse(error);
    }

    // Write timeline event
    await supabase.from("timeline_events").insert({
      project_id: numericProjectId,
      parent_type: "PCO",
      parent_id: data.id.toString(),
      event_type: "CREATED",
      actor_id: user.id,
      summary: `PCO "${data.title}" created`,
      created_at: new Date().toISOString(),
    });

    return NextResponse.json(data, { status: 201 });
  } catch (error) {
    return apiErrorResponse(error);
  }
}
