import { CHANGE_REQUEST_WORKFLOW } from "@/lib/ai/workflow-registry";

const workflowRequiredFields = CHANGE_REQUEST_WORKFLOW.fields
  .filter((field) => field.required)
  .map((field) => ({
    name: field.name,
    label: field.label,
    description: field.description,
  }));

const workflowOptionalFields = CHANGE_REQUEST_WORKFLOW.fields
  .filter((field) => !field.required)
  .map((field) => ({
    name: field.name,
    label: field.label,
    description: field.description,
  }));

export const CHANGE_REQUEST_FIELD_GUIDE = {
  canonicalTool: CHANGE_REQUEST_WORKFLOW.backingTool,
  canonicalRecordName: "change request / change event",
  aliases: [
    "change request",
    "change event",
    "potential change",
    "field change",
    "scope change",
    "unexpected condition",
  ],
  requiredFields: workflowRequiredFields,
  optionalFields: workflowOptionalFields,
  generatedFields: [
    {
      name: "number",
      label: "Number",
      description: "Generated by the tool as the next CE number.",
    },
    {
      name: "updated_at",
      label: "Updated at",
      description: "Set by the tool at write time.",
    },
  ],
  previewRule:
    "Always call createChangeEvent with confirmed=false first. Only write with confirmed=true after the user explicitly confirms the preview.",
} as const;

type ChangeRequestPreviewFields = {
  project_id?: unknown;
  title?: unknown;
  description?: unknown;
  scope?: unknown;
  type?: unknown;
  status?: unknown;
  reason?: unknown;
  origin?: unknown;
  expecting_revenue?: unknown;
  line_item_revenue_source?: unknown;
};

type ReviewCardField = {
  key: string;
  label: string;
  value: string | null;
  helper: string;
  required?: boolean;
  generated?: boolean;
};

export type AssistantWriteReviewCard = {
  title: string;
  recordType: "change_event";
  groups: Array<{
    title: string;
    fields: ReviewCardField[];
  }>;
};

function formatPreviewValue(value: unknown): string | null {
  if (value == null) return null;
  if (typeof value === "string") return value.trim() || null;
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return JSON.stringify(value);
}

function guideField(name: string) {
  return [
    ...CHANGE_REQUEST_FIELD_GUIDE.requiredFields,
    ...CHANGE_REQUEST_FIELD_GUIDE.optionalFields,
    ...CHANGE_REQUEST_FIELD_GUIDE.generatedFields,
  ].find((field) => field.name === name);
}

function reviewField(
  name: string,
  key: keyof ChangeRequestPreviewFields | string,
  value: unknown,
  options: { required?: boolean; generated?: boolean } = {},
): ReviewCardField {
  const guide = guideField(name);
  return {
    key,
    label: guide?.label ?? name,
    value: formatPreviewValue(value),
    helper: guide?.description ?? "",
    required: options.required,
    generated: options.generated,
  };
}

export function buildChangeRequestReviewCard(
  fields: ChangeRequestPreviewFields,
): AssistantWriteReviewCard {
  return {
    title: "Review change request",
    recordType: "change_event",
    groups: [
      {
        title: "Required",
        fields: [
          reviewField("projectId", "project_id", fields.project_id, {
            required: true,
          }),
          reviewField("title", "title", fields.title, { required: true }),
        ],
      },
      {
        title: "Optional",
        fields: [
          reviewField("description", "description", fields.description),
          reviewField("type", "type", fields.type),
          reviewField("scope", "scope", fields.scope),
          reviewField("status", "status", fields.status),
          reviewField("reason", "reason", fields.reason),
          reviewField("origin", "origin", fields.origin),
          reviewField(
            "expectingRevenue",
            "expecting_revenue",
            fields.expecting_revenue,
          ),
          reviewField(
            "lineItemRevenueSource",
            "line_item_revenue_source",
            fields.line_item_revenue_source,
          ),
        ],
      },
      {
        title: "Generated by Alleato",
        fields: [
          reviewField("number", "number", "Generated after confirmation", {
            generated: true,
          }),
          reviewField("updated_at", "updated_at", "Set at write time", {
            generated: true,
          }),
        ],
      },
    ],
  };
}

function formatFieldList(
  fields: ReadonlyArray<{
    name: string;
    label: string;
    description: string;
  }>,
) {
  return fields
    .map((field) => `- ${field.name} (${field.label}): ${field.description}`)
    .join("\n");
}

export function renderChangeRequestFieldGuide() {
  return [
    "### Change Request / Change Event Field Guide",
    "",
    `Canonical tool: \`${CHANGE_REQUEST_FIELD_GUIDE.canonicalTool}\`.`,
    `User wording to treat as this workflow: ${CHANGE_REQUEST_FIELD_GUIDE.aliases.join(", ")}.`,
    "",
    "Required before preview:",
    formatFieldList(CHANGE_REQUEST_FIELD_GUIDE.requiredFields),
    "",
    "Optional fields to prefill when known:",
    formatFieldList(CHANGE_REQUEST_FIELD_GUIDE.optionalFields),
    "",
    "Generated by Alleato, do not ask the user for these:",
    formatFieldList(CHANGE_REQUEST_FIELD_GUIDE.generatedFields),
    "",
    CHANGE_REQUEST_FIELD_GUIDE.previewRule,
  ].join("\n");
}

export function renderChangeRequestToolDescription() {
  return [
    "Help create a change request/change event for a possible scope, cost, or schedule change.",
    "Use this when the user says change request, change event, potential change, field change, scope change, or describes an unexpected field condition.",
    "Required fields are projectId and title. Optional fields are description, type, scope, status, reason, origin, expectingRevenue, and lineItemRevenueSource.",
    "The tool generates the change event number and updated_at timestamp.",
    CHANGE_REQUEST_FIELD_GUIDE.previewRule,
  ].join(" ");
}
