create table if not exists public.outlook_email_intake (
  id bigint generated by default as identity primary key,
  graph_message_id text not null,
  mailbox_user_id text not null,
  project_id integer null,
  project_email_id integer null,
  document_metadata_id text null,
  subject text not null,
  body text null,
  body_html text null,
  body_text text null,
  from_name text null,
  from_email text null,
  to_list text[] null,
  cc_list text[] null,
  bcc_list text[] null,
  status text not null default 'Received',
  match_status text not null default 'unassigned',
  assignment_method text null,
  assignment_confidence double precision null,
  received_at timestamptz null,
  has_attachments boolean null,
  web_link text null,
  internet_message_id text null,
  conversation_id text null,
  source_metadata jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz null,
  deleted_at timestamptz null,
  created_at timestamptz null default timezone('utc'::text, now()),
  updated_at timestamptz null default timezone('utc'::text, now())
);

create unique index if not exists outlook_email_intake_graph_message_id_idx
  on public.outlook_email_intake(graph_message_id);

create index if not exists outlook_email_intake_mailbox_received_idx
  on public.outlook_email_intake(mailbox_user_id, received_at desc);

create index if not exists outlook_email_intake_project_idx
  on public.outlook_email_intake(project_id);

create table if not exists public.outlook_email_intake_attachments (
  id bigint generated by default as identity primary key,
  intake_email_id bigint not null,
  email_attachment_id integer null,
  project_document_id integer null,
  document_metadata_id text null,
  project_id integer null,
  graph_attachment_id text not null,
  file_name text not null,
  file_url text not null,
  file_size bigint null,
  content_type text null,
  content bytea null,
  checksum_sha256 text null,
  extracted_text text null,
  is_inline boolean null,
  promotion_status text not null default 'pending',
  promotion_reason text null,
  promotion_attempt_count integer not null default 0,
  promoted_at timestamptz null,
  source_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz null default timezone('utc'::text, now()),
  updated_at timestamptz null default timezone('utc'::text, now())
);

create unique index if not exists outlook_email_intake_attachments_intake_graph_idx
  on public.outlook_email_intake_attachments(intake_email_id, graph_attachment_id);

create index if not exists outlook_email_intake_attachments_project_idx
  on public.outlook_email_intake_attachments(project_id);

create index if not exists outlook_email_intake_attachments_promotion_idx
  on public.outlook_email_intake_attachments(promotion_status, created_at);

create table if not exists public.outlook_email_skip_audit (
  id bigint generated by default as identity primary key,
  graph_message_id text not null,
  mailbox_user_id text not null,
  internet_message_id text null,
  conversation_id text null,
  subject text not null,
  body_preview text null,
  from_name text null,
  from_email text null,
  received_at timestamptz null,
  web_link text null,
  classification_action text not null default 'skip',
  classification_category text not null,
  classification_confidence double precision null,
  classification_reason text not null,
  classification_signals jsonb not null default '[]'::jsonb,
  source_metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default timezone('utc'::text, now()),
  last_seen_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists outlook_email_skip_audit_graph_message_id_idx
  on public.outlook_email_skip_audit(graph_message_id);

create index if not exists outlook_email_skip_audit_mailbox_received_idx
  on public.outlook_email_skip_audit(mailbox_user_id, received_at desc);

alter table public.outlook_email_intake enable row level security;
alter table public.outlook_email_intake_attachments enable row level security;
alter table public.outlook_email_skip_audit enable row level security;

drop policy if exists outlook_email_intake_admin_select on public.outlook_email_intake;
create policy outlook_email_intake_admin_select
  on public.outlook_email_intake
  for select
  using (auth.role() = 'service_role');

drop policy if exists outlook_email_intake_service_write on public.outlook_email_intake;
create policy outlook_email_intake_service_write
  on public.outlook_email_intake
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists outlook_email_intake_attachments_admin_select on public.outlook_email_intake_attachments;
create policy outlook_email_intake_attachments_admin_select
  on public.outlook_email_intake_attachments
  for select
  using (auth.role() = 'service_role');

drop policy if exists outlook_email_intake_attachments_service_write on public.outlook_email_intake_attachments;
create policy outlook_email_intake_attachments_service_write
  on public.outlook_email_intake_attachments
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists outlook_email_skip_audit_admin_select on public.outlook_email_skip_audit;
create policy outlook_email_skip_audit_admin_select
  on public.outlook_email_skip_audit
  for select
  using (auth.role() = 'service_role');

drop policy if exists outlook_email_skip_audit_service_write on public.outlook_email_skip_audit;
create policy outlook_email_skip_audit_service_write
  on public.outlook_email_skip_audit
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
