-- Seed: Invoicing — Feature test suite
-- Generated by /test-scenario-audit invoicing all
-- Supabase project: lgveqfnpkxvzbnnwuled

-- 1. Upsert suite
insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('invoicing', 'feature', 'Invoicing — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <feature_suite_id> with the id returned above before running step 2+.
-- Actual id used in production seed: 6b1c58e7-21d5-4491-bd9f-fe13fb87ac61

-- 2. Wipe existing cases
delete from public.test_cases where suite_id = '6b1c58e7-21d5-4491-bd9f-fe13fb87ac61';

-- 3. Insert cases
insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  -- CREATE
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '1.1', 'Create', 'Owner invoice — all fields',
   'Create an owner invoice with all required and optional fields',
   'Covers the full happy-path new-invoice flow: contract selection, line items, and save.',
   E'- A prime contract exists in project 67.',
   E'1. Open /67/invoices\n2. Click "New Invoice"\n3. Select contract type "Prime Contract" and pick the first prime contract from the dropdown\n4. Enter invoice number "INV-TEST-001"\n5. Set Invoice Date to 2026-05-01\n6. Set Due Date to 2026-05-31\n7. Click "Add Line Item" and fill in Description "Mobilization", Contract Amount "10000", This Month Amount "5000"\n8. Enter Notes "Test invoice"\n9. Click "Save"\n10. Wait for the page to stop loading.',
   'A new owner invoice is created. The browser navigates to the invoice detail page. The invoice number "INV-TEST-001" and status "Draft" are shown. The line item "Mobilization" appears with $5,000.00 this-month amount.',
   'HIGH', 'scenario', '/67/invoices/new'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '1.2', 'Create', 'Required field validation',
   'Submitting the new-invoice form without a contract shows a validation error',
   'Checks that the form blocks submission when required fields are missing.',
   null,
   E'1. Open /67/invoices/new\n2. Leave Contract blank\n3. Click "Save".',
   'The form does not navigate away. An inline error message appears near the Contract field indicating selection is required.',
   'HIGH', 'scenario', '/67/invoices/new'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '1.3', 'Create', 'Subcontractor invoice — from commitment',
   'Create a subcontractor invoice linked to a commitment',
   'Covers the subcontractor invoice creation path via the Subcontractor tab.',
   E'- A commitment/subcontract exists in project 67.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Click "New Invoice"\n3. Select contract type "Commitment" and pick the first commitment\n4. Set Invoice Date to 2026-05-01\n5. Click "Save"\n6. Wait for the page to stop loading.',
   'A new subcontractor invoice is created and appears in the Subcontractor tab list. The invoice links to the correct commitment.',
   'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '1.4', 'Create', 'Billing period — manual',
   'Create a billing period manually with start date, end date, and due date',
   'Checks that a manually-defined billing period can be saved and appears in the list.',
   null,
   E'1. Open /67/invoices?tab=billing-periods\n2. Click "Create Billing Period"\n3. Ensure "Manual" tab is selected\n4. Set From to 2026-05-01, To to 2026-05-31, Due Date to 2026-06-15\n5. Click "Create"\n6. Wait for the dialog to close.',
   'The dialog closes. A new billing period row appears in the Billing Periods table with period dates 05/01/2026 – 05/31/2026 and due date 06/15/2026. Status shows "Open".',
   'HIGH', 'scenario', '/67/invoices?tab=billing-periods'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '1.5', 'Create', 'Billing period — automatic schedule',
   'Create a billing period using the Automatic tab with monthly frequency',
   'Checks that the automatic billing period generator resolves dates and saves successfully.',
   null,
   E'1. Open /67/invoices?tab=billing-periods\n2. Click "Create Billing Period"\n3. Click the "Automatic" tab\n4. Set Frequency to "Monthly", By Date\n5. Set Start Date to 1st of this month, End Date to 30th of this month, Due Date to 24th of this month\n6. Click "Create"\n7. Wait for the dialog to close.',
   'The dialog closes without error. A new billing period row appears in the list with the resolved start, end, and due dates.',
   'MEDIUM', 'scenario', '/67/invoices?tab=billing-periods'),

  -- EDIT
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '2.1', 'Edit', 'Edit owner invoice — editable fields',
   'Edit all editable fields on a Draft owner invoice',
   'Checks that edits to invoice number, dates, notes, and status are persisted.',
   E'- A Draft owner invoice exists in project 67.',
   E'1. Open /67/invoices (Owner tab)\n2. Click the invoice number of a Draft invoice to open its detail page\n3. Click "Edit"\n4. Change Invoice Number to "INV-EDIT-001"\n5. Change Period Start to 2026-04-01 and Period End to 2026-04-30\n6. Change Notes to "Edited notes"\n7. Click "Save"\n8. Wait for the page to stop loading.',
   'The invoice detail page reloads showing "INV-EDIT-001" as the invoice number and "Edited notes" in the notes section. All changed values persist after a browser refresh.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '2.2', 'Edit', 'Add line item to owner invoice',
   'Add a new line item to an existing Draft owner invoice',
   'Checks that a line item can be added and its amounts recalculate the invoice total.',
   E'- A Draft owner invoice exists in project 67.',
   E'1. Open a Draft owner invoice detail page\n2. Click "Edit"\n3. Click "Add Line Item"\n4. Enter Description "Additional Work", Contract Amount "20000", This Month Amount "8000"\n5. Click "Save"\n6. Wait for the page to stop loading.',
   'The new line item "Additional Work" appears in the line-items table. Net Amount and Gross Amount in the invoice header reflect the updated total.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '2.3', 'Edit', 'Remove line item from owner invoice',
   'Delete a line item from a Draft invoice and verify the totals update',
   'Checks that removing a line item reduces the invoice net amount.',
   E'- A Draft owner invoice exists with at least 2 line items.',
   E'1. Open a Draft owner invoice detail page\n2. Click "Edit"\n3. Click the delete icon (trash) on the first line item\n4. Click "Save"\n5. Wait for the page to stop loading.',
   'The deleted line item no longer appears in the list. The invoice total reflects the removal.',
   'MEDIUM', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '2.4', 'Edit', 'Cannot edit Approved invoice',
   'Edit controls are disabled or absent on an Approved invoice',
   'Checks that the EDITABLE_STATUSES constraint prevents editing non-draft invoices.',
   E'- An Approved owner invoice exists in project 67.',
   E'1. Open an Approved owner invoice detail page\n2. Observe the page header actions.',
   'No "Edit" button is visible. The invoice is read-only. Field values are displayed but cannot be modified.',
   'HIGH', 'scenario', '/67/invoices'),

  -- DELETE
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '3.1', 'Delete', 'Delete a Draft owner invoice',
   'Delete a Draft invoice and confirm it is removed from the list',
   'Checks the delete flow on the owner invoice detail page.',
   E'- A Draft owner invoice exists in project 67.',
   E'1. Open a Draft owner invoice detail page\n2. Click the row-actions menu (⋯)\n3. Click "Delete"\n4. Confirm the deletion in the alert dialog\n5. Wait for the page to stop loading.',
   'The browser navigates back to /67/invoices. The deleted invoice no longer appears in the Owner tab list.',
   'HIGH', 'scenario', '/67/invoices'),

  -- STATUS TRANSITIONS
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.1', 'Status', 'Submit owner invoice for approval',
   'Submit a Draft invoice and verify status changes to Under Review',
   'Covers the Draft → Under Review transition via the Submit action.',
   E'- A Draft owner invoice exists in project 67.',
   E'1. Open a Draft owner invoice detail page\n2. Click "Submit"\n3. Confirm submission if prompted\n4. Wait for the page to stop loading.',
   'The invoice status badge changes to "Under Review". The Submit button is no longer visible. The edit controls are disabled.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.2', 'Status', 'Approve an Under Review owner invoice',
   'Approve an Under Review invoice and verify status changes to Approved',
   'Covers the Under Review → Approved transition.',
   E'- An Under Review owner invoice exists in project 67.',
   E'1. Open an Under Review owner invoice detail page\n2. Click "Approve"\n3. Confirm the action if prompted\n4. Wait for the page to stop loading.',
   'The invoice status badge changes to "Approved". The Approved KPI total on the Invoices list page increases by the invoice gross amount.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.3', 'Status', 'Approve as Noted',
   'Use Approve as Noted action on an Under Review invoice',
   'Covers the Under Review → Approved as Noted transition.',
   E'- An Under Review owner invoice exists.',
   E'1. Open an Under Review owner invoice detail page\n2. Click "Approve as Noted"\n3. Confirm if prompted\n4. Wait for the page to stop loading.',
   'The invoice status badge changes to "Approved as Noted".',
   'MEDIUM', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.4', 'Status', 'Revise and Resubmit owner invoice',
   'Return an Under Review invoice to Revise & Resubmit',
   'Covers the Under Review → Revise & Resubmit transition.',
   E'- An Under Review owner invoice exists.',
   E'1. Open an Under Review owner invoice detail page\n2. Click "Revise"\n3. Confirm if prompted\n4. Wait for the page to stop loading.',
   'The invoice status badge changes to "Revise & Resubmit". The edit controls become available again.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.5', 'Status', 'Void an Approved owner invoice',
   'Void an Approved invoice and verify the status changes to Void',
   'Checks the Approve → Void transition.',
   E'- An Approved owner invoice exists.',
   E'1. Open an Approved owner invoice detail page\n2. Click "Void"\n3. Confirm the action in the dialog\n4. Wait for the page to stop loading.',
   'The invoice status badge changes to "Void". The invoice is no longer counted in the Approved KPI total.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.6', 'Status', 'Mark subcontractor invoice as Paid',
   'Use Mark Paid action on an Approved subcontractor invoice',
   'Covers the Approved → Paid transition for subcontractor invoices.',
   E'- An Approved subcontractor invoice exists.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Click the invoice number to open its detail page\n3. Click "Mark Paid"\n4. Confirm if prompted\n5. Wait for the page to stop loading.',
   'The invoice status shows "Paid". The Paid Amount column on the Subcontractor list tab updates to reflect the payment.',
   'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '4.7', 'Status', 'Submit subcontractor invoice',
   'Submit a Draft subcontractor invoice for approval',
   'Checks the Draft → Under Review transition for subcontractor invoices.',
   E'- A Draft subcontractor invoice exists.',
   E'1. Open a Draft subcontractor invoice detail page\n2. Click "Submit"\n3. Confirm if prompted\n4. Wait for the page to stop loading.',
   'The subcontractor invoice status changes to "Under Review".',
   'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  -- CALCULATIONS
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '5.1', 'Calculations', 'Net amount = gross minus retention',
   'Net Amount on an owner invoice equals Gross Amount minus retention percentage',
   'Verifies the retention calculation logic displayed on the invoice detail.',
   E'- A prime contract with 10% retention exists.\n- An owner invoice with at least one line item exists against it.',
   E'1. Open an owner invoice detail page linked to a 10% retention contract\n2. Note the Gross Amount\n3. Note the Net Amount.',
   'Net Amount equals Gross Amount × (1 − 0.10). For example, if Gross is $10,000 then Net is $9,000.',
   'HIGH', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '5.2', 'Calculations', 'Percent complete updates after edit',
   'Editing This Month amount recalculates % Complete on the subcontractor invoice',
   'Verifies that percent-complete displayed in the list reflects saved line-item amounts.',
   E'- A subcontractor invoice with a total contract amount exists.',
   E'1. Open a Draft subcontractor invoice detail page\n2. Click "Edit"\n3. Change a line item "This Month Amount" to 5000\n4. Save and wait for reload\n5. Go back to /67/invoices?tab=subcontractor and find the same invoice.',
   'The % Complete column in the list reflects the updated total-completed / total-contract calculation.',
   'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  -- FILTERS & SEARCH
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '6.1', 'Filters', 'Filter subcontractor invoices by billing period',
   'Applying a Billing Period filter shows only invoices in that period',
   'Checks the billing-period filter on the Subcontractor tab.',
   E'- Subcontractor invoices exist in at least two different billing periods.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Open the filter toolbar\n3. Select a specific billing period from "Billing Period" filter\n4. Wait for the list to update.',
   'Only invoices linked to the selected billing period are shown. The toolbar filtered-item count is less than the total count.',
   'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '6.2', 'Filters', 'Filter subcontractor invoices by contract company',
   'Applying a Contract Company filter shows only invoices from that company',
   'Checks the contract-company filter on the Subcontractor tab.',
   E'- Subcontractor invoices from at least two companies exist.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Open the filter toolbar\n3. Select a company from the "Contract Company" filter\n4. Wait for the list to update.',
   'Only invoices whose contract company matches the selection are shown.',
   'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '6.3', 'Filters', 'Filter by payment status — Unpaid',
   'Filtering by payment status "Unpaid" shows only unpaid subcontractor invoices',
   'Checks the payment-status filter reduces the list correctly.',
   E'- Both paid and unpaid subcontractor invoices exist.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Open the filter toolbar\n3. Select "Unpaid" from "Payment Status"\n4. Wait for the list to update.',
   'Only invoices with payment_status = unpaid are visible. Paid invoices are hidden.',
   'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '6.4', 'Filters', 'Sort Owner invoices by Gross Amount descending',
   'Clicking the Gross Amount column header sorts invoices highest to lowest',
   'Checks that column sort on a numeric field works correctly.',
   E'- Multiple owner invoices with different gross amounts exist.',
   E'1. Open /67/invoices (Owner tab)\n2. Click the "Gross Amount" column header once\n3. Click it again to reverse direction.',
   'First click: invoices sort ascending by gross amount. Second click: invoices sort descending. The sorted order is consistent with the displayed values.',
   'MEDIUM', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '6.5', 'Filters', 'Clear all filters restores full list',
   'Clicking "Clear filters" resets the Subcontractor tab to show all invoices',
   'Checks that clearing active filters returns the full unfiltered list.',
   E'- At least one filter is active on the Subcontractor tab.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Apply a status filter "Draft"\n3. Click "Clear filters"\n4. Wait for the list to update.',
   'All subcontractor invoices are shown again. The toolbar no longer shows active filter chips.',
   'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '6.6', 'Filters', 'Filter billing periods by status — Closed',
   'Filtering billing periods by "Closed" shows only closed periods',
   'Checks the status filter on the Billing Periods tab.',
   E'- Both open and closed billing periods exist.',
   E'1. Open /67/invoices?tab=billing-periods\n2. Apply status filter "Closed"\n3. Wait for the list to update.',
   'Only billing periods with is_closed = true are shown. Open periods are hidden.',
   'MEDIUM', 'scenario', '/67/invoices?tab=billing-periods'),

  -- COLUMN VISIBILITY
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '7.1', 'Filters', 'Toggle hidden column visible on Subcontractor tab',
   'Enabling ERP Status column makes it appear in the subcontractor invoice table',
   'Checks the column-visibility toggle for a non-default column.',
   null,
   E'1. Open /67/invoices?tab=subcontractor\n2. Open the Columns toggle in the toolbar\n3. Enable "ERP Status"\n4. Close the column panel.',
   'The "ERP Status" column appears in the table header and each row shows the ERP status value (or "–" if blank).',
   'LOW', 'scenario', '/67/invoices?tab=subcontractor'),

  -- PDF / EMAIL EXPORT
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '8.1', 'Export', 'Download owner invoice PDF',
   'Clicking the PDF download action returns a PDF file',
   'Checks the /pdf endpoint is reachable and returns a downloadable file.',
   E'- At least one owner invoice exists.',
   E'1. Open an owner invoice detail page\n2. Click the download / PDF button in the header actions.',
   'The browser triggers a PDF download or opens a PDF in a new tab. The file name includes the invoice number.',
   'MEDIUM', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '8.2', 'Export', 'Send invoice by email',
   'Using the Email action opens a dialog and sends the invoice',
   'Checks the email-send workflow on an owner invoice.',
   E'- At least one owner invoice with status Under Review or Approved exists.',
   E'1. Open an eligible owner invoice detail page\n2. Click the "Email" or "Send" action\n3. Confirm the recipient email in the dialog\n4. Click "Send".',
   'A success toast or confirmation message appears. No 500 error occurs.',
   'MEDIUM', 'scenario', '/67/invoices'),

  -- BILLING PERIOD DETAIL
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '9.1', 'Edit', 'Billing period manual form validation',
   'Submitting the billing period dialog without dates shows an error or keeps the button disabled',
   'Checks that the Create button is disabled when required date fields are empty.',
   null,
   E'1. Open /67/invoices?tab=billing-periods\n2. Click "Create Billing Period"\n3. Leave all date fields blank\n4. Observe the "Create" button state.',
   'The "Create" button is disabled (grayed out) and cannot be clicked. No network request is made.',
   'HIGH', 'scenario', '/67/invoices?tab=billing-periods'),

  -- PAGINATION
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '10.1', 'Filters', 'Pagination — change per-page to 10',
   'Changing per-page to 10 shows at most 10 rows per page',
   'Checks that pagination works correctly when more records than per-page limit exist.',
   E'- More than 10 invoices exist on the Owner tab.',
   E'1. Open /67/invoices (Owner tab)\n2. Change the per-page selector to "10"\n3. Wait for the list to update.',
   'At most 10 rows are visible. The pagination control shows page 1 of N pages. Clicking "Next" loads the next 10 rows.',
   'MEDIUM', 'scenario', '/67/invoices'),

  -- PERMISSIONS
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '11.1', 'Permissions', 'Read-only user cannot see approve button',
   'A user without contracts write permission does not see workflow action buttons',
   'Checks that the permission gate (requirePermission contracts write) hides destructive actions.',
   E'- A second test user exists with read-only access to project 67.',
   E'1. Log in as the read-only user\n2. Open an Under Review owner invoice detail page\n3. Observe the action buttons in the header.',
   'The "Approve", "Revise", and "Void" action buttons are not visible. The invoice displays in read-only mode.',
   'MEDIUM', 'scenario', '/67/invoices'),

  -- EDGE CASES
  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '12.1', 'Edge', 'Invoice number max length enforcement',
   'Entering more than 255 characters in Invoice Number truncates or errors',
   'Checks the 255-char max validation on the invoice number field.',
   null,
   E'1. Open a Draft owner invoice detail page\n2. Click "Edit"\n3. In Invoice Number, paste a string of 300 characters\n4. Click "Save".',
   'The form either truncates the value to 255 characters before saving, or shows a validation error "must be 255 characters or fewer". The invoice is not corrupted.',
   'LOW', 'scenario', '/67/invoices'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '12.2', 'Edge', 'Navigate to non-existent invoice returns 404',
   'Visiting an invoice ID that does not exist shows an error or not-found page',
   'Checks the GET /api/projects/67/invoicing/owner/999999 responds with a 404 and the UI handles it gracefully.',
   null,
   E'1. Navigate directly to /67/invoicing/999999\n2. Wait for the page to load.',
   'The page shows a "not found" or error message rather than a blank screen. No unhandled exception is thrown.',
   'LOW', 'scenario', '/67/invoicing/999999'),

  ('6b1c58e7-21d5-4491-bd9f-fe13fb87ac61', '12.3', 'Edge', 'Legacy invoicing URL redirects correctly',
   'Visiting /67/invoicing redirects to /67/invoices',
   'Checks the LegacyInvoicingPage redirect is working.',
   null,
   E'1. Navigate directly to /67/invoicing',
   'The browser is redirected to /67/invoices. The Owner tab is active and the page loads without error.',
   'LOW', 'scenario', '/67/invoicing')
;

-- 4. Update total_cases
update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '6b1c58e7-21d5-4491-bd9f-fe13fb87ac61')
 where id = '6b1c58e7-21d5-4491-bd9f-fe13fb87ac61';
