-- Seed: change-orders SMOKE test suite
-- Generated by /test-scenario-audit change-orders on 2026-04-20
-- Suite type: smoke | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('change-orders', 'smoke', 'Change Orders — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <smoke_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<smoke_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<smoke_suite_id>', '1.1', 'Navigation', 'Page load',
   'Open the Change Orders page',
   'Verifies the change orders index renders without a runtime error.',
   null,
   E'1. Log in as test1@mail.com\n2. Navigate to /67/change-orders',
   'The page loads. The table is visible (or a valid empty state). Tabs "Prime Contract" and "Commitments" are visible.',
   'HIGH', 'scenario', '/67/change-orders'),

  ('<smoke_suite_id>', '1.2', 'Navigation', 'Tab switch',
   'Switch between Prime Contract and Commitments tabs',
   'Checks tab routing and data loading on both views.',
   null,
   E'1. Open /67/change-orders\n2. Click "Commitments"\n3. Click "Prime Contract"',
   'Both tabs load without errors and each tab shows its own list context.',
   'HIGH', 'scenario', '/67/change-orders'),

  ('<smoke_suite_id>', '1.3', 'Navigation', 'Search',
   'Search filters rows on the active tab',
   'Confirms the text filter updates the visible list.',
   E'- At least one row exists on the active tab.',
   E'1. Open /67/change-orders\n2. Type "CO" into search',
   'Visible rows narrow to matches for number/title/description; clearing search restores the full list.',
   'HIGH', 'scenario', '/67/change-orders'),

  ('<smoke_suite_id>', '1.4', 'Navigation', 'Status filter',
   'Status filter narrows rows',
   'Ensures status filter chips are wired to list filtering.',
   null,
   E'1. Open /67/change-orders\n2. Open Filters\n3. Select Status = Approved',
   'Only Approved rows remain visible. Removing the filter restores all rows.',
   'HIGH', 'scenario', '/67/change-orders'),

  ('<smoke_suite_id>', '1.5', 'Navigation', 'Primary action',
   'New Change Order opens create flow',
   'Validates the primary create action is reachable.',
   null,
   E'1. Open /67/change-orders\n2. Click "New Change Order"',
   'Navigation occurs to a change-order create route and a create form is displayed.',
   'HIGH', 'scenario', '/67/change-orders'),

  ('<smoke_suite_id>', '1.6', 'Navigation', 'Row open',
   'Clicking a prime row opens prime detail page',
   'Confirms row -> detail navigation for the prime tab.',
   E'- At least one prime change order exists.',
   E'1. Open /67/change-orders\n2. Ensure "Prime Contract" tab is active\n3. Click first row title',
   'Prime detail route opens and renders header, status, and tabs without errors.',
   'HIGH', 'scenario', '/67/change-orders'),

  ('<smoke_suite_id>', '1.7', 'Navigation', 'Commitment row open',
   'Clicking a commitment row opens commitment detail page',
   'Confirms row -> detail navigation for commitment tab.',
   E'- At least one commitment change order exists.',
   E'1. Open /67/change-orders?tab=commitment\n2. Click first row title/description',
   'Commitment detail route opens and renders summary/header content without errors.',
   'HIGH', 'scenario', '/67/change-orders?tab=commitment'),

  ('<smoke_suite_id>', '1.8', 'Navigation', 'Empty state',
   'No-match search shows empty state',
   'Ensures no-result UX renders intentionally.',
   null,
   E'1. Open /67/change-orders\n2. Type "zzznomatch999" in search',
   'A valid empty-state message appears. No console/runtime error is triggered.',
   'MEDIUM', 'scenario', '/67/change-orders');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<smoke_suite_id>')
 where id = '<smoke_suite_id>';
*/
