-- Smoke test suite seed for prime-contracts
-- Generated by /test-scenario-audit on 2026-05-14
-- Suite type: smoke  |  Target: 10 cases

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('prime-contracts', 'smoke', 'Prime Contracts — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: After inserting, replace <SMOKE_SUITE_ID> with the returned UUID and run the cases block.
-- The live seed used suite_id = '07ff30a3-c5b4-4782-8626-e76c3654a56e'

delete from public.test_cases where suite_id = '07ff30a3-c5b4-4782-8626-e76c3654a56e';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.1', 'Navigation', 'Page load',
   'Prime Contracts list page loads without error',
   'Verifies the page renders, no 500 errors, table or empty state visible.',
   'Logged in as test1@mail.com on project 67.',
   E'1. Navigate to /67/prime-contracts\n2. Wait for the page to stop loading.',
   'Page renders with title "Prime Contracts". Table with columns (Number, Title, Status, Original Contract Amount, Revised Contract Amount) is visible, or an empty state is shown. No error toast or blank screen.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.2', 'Navigation', 'Table columns',
   'Table shows expected financial columns',
   'Confirms the key Procore-parity columns are present in the column headers.',
   'Prime Contracts list page loaded.',
   E'1. Navigate to /67/prime-contracts\n2. Look at the table column headers.',
   'Columns visible include: Number, Title, Status, Original Contract Amount, Approved Change Orders, Revised Contract Amount, Invoiced, Payments Received, Remaining Balance. No broken layout.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.3', 'Navigation', 'Create button',
   'Clicking "Create" opens the new contract form',
   'Verifies the primary create action is reachable from the list page.',
   'Prime Contracts list page loaded.',
   E'1. Navigate to /67/prime-contracts\n2. Click the "Create" button in the top-right header area.',
   'Browser navigates to /67/prime-contracts/new and a form with fields "Contract #" and "Title" is visible. No error.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.4', 'Navigation', 'Search',
   'Typing in the search box filters the contracts list',
   'Confirms search input is wired to the filter logic.',
   'At least one prime contract exists in project 67.',
   E'1. Navigate to /67/prime-contracts\n2. Click the search input in the toolbar.\n3. Type a partial contract number or title that matches at least one record.',
   'The table updates to show only rows matching the typed text. Clearing the input restores the full list.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.5', 'Navigation', 'Status filter',
   'Applying a Status filter narrows the list',
   'Confirms the status filter dropdown is functional.',
   'Prime Contracts list page loaded.',
   E'1. Navigate to /67/prime-contracts\n2. Click the "Filters" button in the toolbar.\n3. Set Status to "Draft".\n4. Apply the filter.',
   'The table shows only contracts with status "Draft", or an empty-state message if none exist. No 500 error.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.6', 'Navigation', 'Contract detail opens',
   'Clicking a row opens the contract detail page',
   'Verifies row-click navigation and that the detail page renders without error.',
   'At least one prime contract exists in project 67.',
   E'1. Navigate to /67/prime-contracts\n2. Click any contract row.',
   'Browser navigates to /67/prime-contracts/{contractId}. The page renders with contract title, status badge, and the General tab visible. No blank screen.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.7', 'Navigation', 'Detail tabs',
   'Each tab on the contract detail page loads without error',
   'Smoke-checks all 11 tabs so a broken tab is caught immediately.',
   'Contract detail page open.',
   E'1. Open a prime contract detail page.\n2. Click "SOV".\n3. Click "Change Orders".\n4. Click "Invoices".\n5. Click "Payments Received".\n6. Click "Financial Markup".\n7. Click "Advanced Settings".',
   'Each tab renders its content area or an empty state without a crash, error toast, or blank white section.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.8', 'Navigation', 'Empty state',
   'Filtering to zero results shows the empty state',
   'Verifies filtered-empty-state copy renders correctly.',
   'Prime Contracts list page loaded.',
   E'1. Navigate to /67/prime-contracts\n2. Type a long random string (e.g. "ZZZNOMATCH9999") in the search box.',
   'The table area shows the empty-state component with text "No contracts found" and a message about adjusting filters. No 500 error.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.9', 'Navigation', 'Expand row',
   'Clicking the expand chevron shows linked change orders / PCOs',
   'Verifies the expandable sub-row feature loads without crashing.',
   'At least one prime contract exists in project 67.',
   E'1. Navigate to /67/prime-contracts\n2. Click the ">" expand icon on the left of any contract row.\n3. Wait for loading to complete.',
   'The row expands to show either a "No change orders or potential change orders" message, or a table of linked PCCOs and PCOs. No JS error.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('07ff30a3-c5b4-4782-8626-e76c3654a56e', '1.10', 'Navigation', 'Footer totals',
   'Financial totals row appears at the bottom of the table',
   'Confirms the footer totals section renders for the visible rows.',
   'At least one prime contract with a non-zero original contract value exists.',
   E'1. Navigate to /67/prime-contracts\n2. Scroll to the bottom of the contracts table.',
   'A "Totals" row is visible below the data rows showing numeric values (formatted as currency) for Original Contract Amount, Revised Contract Amount, and Remaining Balance.',
   'MEDIUM', 'scenario', '/67/prime-contracts');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '07ff30a3-c5b4-4782-8626-e76c3654a56e')
 where id = '07ff30a3-c5b4-4782-8626-e76c3654a56e';
