-- Seed: invoices SMOKE test suite
-- Generated by /test-scenario-audit invoices on 2026-04-20
-- Suite type: smoke | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('invoices', 'smoke', 'Invoices — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;
-- NOTE: Replace <smoke_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<smoke_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<smoke_suite_id>', '1.1', 'Navigation', 'Page load',
   'Open the Invoices page',
   'Verifies invoices index renders and base tabs are visible.',
   null,
   E'1. Log in as test1@mail.com\n2. Navigate to /67/invoices',
   'Page loads without runtime errors. Tabs Owner, Subcontractor, and Billing Periods are visible.',
   'HIGH', 'scenario', '/67/invoices'),

  ('<smoke_suite_id>', '1.2', 'Navigation', 'Tab switch',
   'Switch Owner/Subcontractor/Billing Periods tabs',
   'Checks tab routing and loading for all invoice list contexts.',
   null,
   E'1. Open /67/invoices\n2. Click Subcontractor\n3. Click Billing Periods\n4. Click Owner',
   'All three tabs load without errors and show appropriate table/empty states.',
   'HIGH', 'scenario', '/67/invoices'),

  ('<smoke_suite_id>', '1.3', 'Navigation', 'Search',
   'Search filters invoice rows on active tab',
   'Confirms search input narrows visible rows.',
   E'- At least one invoice exists on active tab.',
   E'1. Open /67/invoices\n2. Type INV in search input',
   'Rows filter to matching invoice numbers/titles; clearing search restores full list.',
   'HIGH', 'scenario', '/67/invoices'),

  ('<smoke_suite_id>', '1.4', 'Navigation', 'Status filter',
   'Status filter narrows invoice rows',
   'Validates filter controls are wired to the list query.',
   null,
   E'1. Open /67/invoices\n2. Open Filters\n3. Select a status value',
   'Only rows for selected status remain visible; clearing filters restores full list.',
   'HIGH', 'scenario', '/67/invoices'),

  ('<smoke_suite_id>', '1.5', 'Navigation', 'Create owner invoice',
   'New Invoice opens owner invoice create flow',
   'Verifies primary create action availability.',
   null,
   E'1. Open /67/invoices\n2. Click New Invoice',
   'Navigation occurs to /67/invoices/new and create form renders.',
   'HIGH', 'scenario', '/67/invoices'),

  ('<smoke_suite_id>', '1.6', 'Navigation', 'Owner row open',
   'Clicking owner invoice row opens detail',
   'Confirms owner row navigation into detail route.',
   E'- At least one owner invoice exists.',
   E'1. Open /67/invoices (Owner tab)\n2. Click first row',
   'Owner invoice detail page opens and displays status + totals sections.',
   'HIGH', 'scenario', '/67/invoices'),

  ('<smoke_suite_id>', '1.7', 'Navigation', 'Subcontractor row open',
   'Clicking subcontractor invoice row opens detail',
   'Confirms subcontractor row navigation into detail route.',
   E'- At least one subcontractor invoice exists.',
   E'1. Open /67/invoices?tab=subcontractor\n2. Click first row',
   'Subcontractor invoice detail page opens and renders header/line-item sections.',
   'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<smoke_suite_id>', '1.8', 'Navigation', 'Billing period create modal',
   'Create Billing Period modal opens and validates required fields',
   'Checks the billing-period creation entry point on Billing Periods tab.',
   null,
   E'1. Open /67/invoices?tab=billing-periods\n2. Click Create Billing Period\n3. Click Create without filling fields',
   'Modal opens. Validation errors appear for required fields and no billing period is created.',
   'MEDIUM', 'scenario', '/67/invoices?tab=billing-periods');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<smoke_suite_id>')
 where id = '<smoke_suite_id>';
*/;
