-- Meeting digests: per-meeting executive summaries generated by pipeline Stage 4
CREATE TABLE public.meeting_digests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    metadata_id TEXT NOT NULL REFERENCES document_metadata(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id),
    digest_text TEXT NOT NULL,
    digest_html TEXT,
    decisions_summary JSONB DEFAULT '[]'::jsonb,
    action_items_summary JSONB DEFAULT '[]'::jsonb,
    risks_summary JSONB DEFAULT '[]'::jsonb,
    opportunities_summary JSONB DEFAULT '[]'::jsonb,
    follow_ups JSONB DEFAULT '[]'::jsonb,
    key_takeaways TEXT[],
    model_used TEXT DEFAULT 'gpt-4o-mini',
    generation_time_seconds NUMERIC(8, 2),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(metadata_id)
);
CREATE INDEX idx_meeting_digests_project ON meeting_digests(project_id);
CREATE INDEX idx_meeting_digests_created ON meeting_digests(created_at DESC);
-- RLS: allow all roles (internal tool)
ALTER TABLE public.meeting_digests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to meeting_digests"
    ON public.meeting_digests FOR ALL
    USING (true)
    WITH CHECK (true);
GRANT ALL ON TABLE public.meeting_digests TO anon;
GRANT ALL ON TABLE public.meeting_digests TO authenticated;
GRANT ALL ON TABLE public.meeting_digests TO service_role;
