-- Seed: change-events FEATURE test suite
-- Generated by /test-scenario-audit change-events on 2026-04-20
-- Suite type: feature | Supabase project: lgveqfnpkxvzbnnwuled
-- 30 cases covering: CRUD, status workflow, line items, add-to workflow,
--                    RFQs, filters, views, export, history, attachments,
--                    permissions, edge cases (markup computation, tab counts)

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('change-events', 'feature', 'Change Events — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- Replace <feature_suite_id> with the returned id, then run the insert below.
-- (Full insert omitted here for brevity; see Supabase for live data.)
