-- Seed: commitments feature suite
-- Generated by /test-scenario-audit on 2026-05-14

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('commitments', 'feature', 'Commitments — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <FEATURE_SUITE_ID> with the id returned above before running
-- the insert below, or run the upsert first and capture the id.

-- delete from public.test_cases where suite_id = '<FEATURE_SUITE_ID>';

-- insert into public.test_cases
--   (suite_id, test_number, category, subcategory, test_name,
--    context_note, setup_steps, steps, expected_result, priority,
--    test_type, start_url)
-- values
--   -- ── CREATE ──────────────────────────────────────────────────────────────
--   ('<FEATURE_SUITE_ID>', '1.1', 'Create', 'Subcontract creation',
--    'Create a subcontract with all fields filled',
--    'Exercises the full subcontract create flow including vendor, dates, retainage, and description.',
--    '- Logged in as test1@mail.com. At least one company exists in the directory.',
--    E'1. Navigate to /67/commitments.\n2. Click "Create" then select "Subcontract".\n3. Fill in Number: SC-TEST-001, Title: Test Subcontract, select any Contract Company.\n4. Set Start Date to 2026-06-01, Est. Completion to 2026-12-31, Contract Date to 2026-05-14.\n5. Set Default Retainage to 5.\n6. Add Description: Test description for smoke.\n7. Click Save. Wait for the page to stop loading.',
--    'The form saves and redirects to the new commitment detail page. The Number, Title, Contract Company, dates, and retainage values are all visible in the General tab.',
--    'HIGH', 'scenario', '/67/commitments/new?type=subcontract'),
--
--   ('<FEATURE_SUITE_ID>', '1.2', 'Create', 'Purchase Order creation',
--    'Create a purchase order with all fields filled',
--    'Exercises the PO create form which differs from subcontract (no Start Date, uses Delivery Date).',
--    '- Logged in as test1@mail.com.',
--    E'1. Navigate to /67/commitments.\n2. Click "Create" then select "Purchase Order".\n3. Fill in Number: PO-TEST-001, Title: Test Purchase Order, select any Contract Company.\n4. Set Delivery Date to 2026-09-30, Contract Date to 2026-05-14.\n5. Set Default Retainage to 0.\n6. Click Save. Wait for the page to stop loading.',
--    'The form saves. The detail page shows the new PO with Type "Purchase Order", the correct dates, and 0% retainage.',
--    'HIGH', 'scenario', '/67/commitments/new?type=purchase_order'),
--
--   ('<FEATURE_SUITE_ID>', '1.3', 'Create', 'Required field validation',
--    'Submitting the create form without required fields shows validation errors',
--    'Verifies that Title is enforced before a commitment can be saved.',
--    '- On the new subcontract form for project 67.',
--    E'1. Navigate to /67/commitments/new?type=subcontract.\n2. Leave Title blank.\n3. Click Save.',
--    'The form does not navigate away. A validation error is shown near the Title field indicating it is required.',
--    'HIGH', 'scenario', '/67/commitments/new?type=subcontract'),
--
--   -- ... (30 cases total — see Supabase for full data)
--
-- update public.test_suites
--    set total_cases = (select count(*) from public.test_cases where suite_id = '<FEATURE_SUITE_ID>')
--  where id = '<FEATURE_SUITE_ID>';
