-- =============================================================================
-- Seed: estimates — Smoke Test Suite
-- Generated by /test-scenario-audit on 2026-05-14
-- Supabase project: lgveqfnpkxvzbnnwuled
-- =============================================================================

-- 1. Upsert suite
insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('estimates', 'smoke', 'Estimates — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <suite_id> below with the id returned above before re-running.
-- The seeded suite id is: 54876b89-b681-43a3-bbb1-f2aab5334e2e

-- 2. Wipe existing cases
delete from public.test_cases where suite_id = '54876b89-b681-43a3-bbb1-f2aab5334e2e';

-- 3. Insert cases
insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.1', 'Navigation', 'Page load',
   'Open the Estimates list page',
   'Confirms the estimates list renders without errors for a project.',
   null,
   E'1. Log in as test1@mail.com\n2. Click "Estimates" in the left sidebar of project "Vermillion Rise Warehouse".\n3. Wait for the page to stop loading.',
   'The page loads fully. A table with columns Title, Estimate #, Rev, Status, Estimator, Date, Last Updated is visible, or an empty-state message is shown.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.2', 'Navigation', 'Column presence',
   'Estimates table shows the correct default columns',
   'Checks that the expected columns are visible on first load without any column-visibility changes.',
   E'- On the Estimates list page.',
   E'1. Observe the table header row.',
   'The columns Title, Estimate #, Rev, Status, Estimator, Date, and Last Updated are all visible. The Location column is NOT visible by default.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.3', 'Navigation', 'New Estimate button',
   'Clicking "New Estimate" opens the create form',
   'Verifies the primary create action is reachable from the list page.',
   E'- On the Estimates list page.',
   E'1. Click the "New Estimate" button in the top-right header.\n2. Wait for navigation to complete.',
   'The New Estimate form page loads. Fields for Title, Estimate Number, Revision, Status, Estimate Type, Date, Estimator, Location, Project Duration, Insurance Rate, Fee Rate, Contingency Amount, and Notes are visible.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.4', 'Navigation', 'Search',
   'Typing in the search box filters the estimates list',
   'Confirms the client-side search filters rows by title, estimator, and other searchable fields.',
   E'- At least one estimate exists in the project.',
   E'1. On the Estimates list page, type a known estimate title (or partial word) into the "Search estimates..." input.\n2. Wait for the list to update.',
   'Only rows whose title, estimate number, estimator, location, or status match the search term are displayed. Rows that do not match disappear.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.5', 'Navigation', 'Status filter',
   'Selecting a status filter narrows the estimates list',
   'Verifies the Status filter dropdown works as expected.',
   E'- At least one estimate with status "draft" exists.',
   E'1. On the Estimates list page, open the Status filter dropdown in the toolbar.\n2. Select "Draft".\n3. Wait for the list to update.',
   'Only estimates with status "Draft" are shown. Other status rows disappear. The toolbar shows the updated filtered count.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.6', 'Navigation', 'Empty state',
   'Filtering to no results shows the empty state message',
   'Ensures an empty-state UI is displayed rather than a blank area when no rows match.',
   null,
   E'1. On the Estimates list page, type a search term that matches no estimates (e.g., "zzznomatch999").\n2. Wait for the list to update.',
   'The table is empty and an empty-state message such as "No estimates match your current filters." is displayed.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.7', 'Navigation', 'Detail page load',
   'Clicking a row opens the estimate detail page',
   'Confirms row-click navigation to the detail view works and the detail page renders.',
   E'- At least one estimate exists.',
   E'1. On the Estimates list page, click any estimate row.\n2. Wait for navigation to complete.',
   'The estimate detail page loads. The page shows the estimate title, status, revision, and the three tabs: "General Conditions", "Quantity Takeoff", and "Alternates & Allowances". The left sidebar shows Estimate Settings and Division Summary.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.8', 'Navigation', 'Detail tabs',
   'All three tabs on the detail page load without errors',
   'Confirms each tab renders content (or a meaningful empty state) without a crash.',
   E'- On an estimate detail page.',
   E'1. Click the "General Conditions" tab. Wait for it to load.\n2. Click the "Quantity Takeoff" tab. Wait for it to load.\n3. Click the "Alternates & Allowances" tab. Wait for it to load.',
   'Each tab renders without a blank screen or error. General Conditions shows a table of cost codes. Quantity Takeoff shows division accordions. Alternates & Allowances shows Alternates and Allowances sections.',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.9', 'Navigation', 'Row actions menu',
   'The row actions menu (⋯) opens with View Details, Edit, and Delete options',
   'Confirms the three-dot menu is present and shows the expected actions.',
   E'- At least one estimate exists on the list page.',
   E'1. On the Estimates list page, hover over any row.\n2. Click the "⋯" (MoreHorizontal) icon on that row.',
   'A dropdown menu appears with three items: "View Details", "Edit", and "Delete".',
   'HIGH', 'scenario', '/67/estimates'),

  ('54876b89-b681-43a3-bbb1-f2aab5334e2e', '1.10', 'Navigation', 'Summary sidebar',
   'The estimate summary sidebar shows Grand Total',
   'Confirms the cost summary (Subtotal → Contingency → Insurance → Fee → Grand Total) renders on the detail page.',
   E'- On an estimate detail page with at least one line item that has a non-zero cost.',
   E'1. Open any estimate with cost data.\n2. Observe the left sidebar.',
   'The sidebar shows Subtotal, Contingency, Insurance (with rate %), Fee (with rate %), and Grand Total rows. Grand Total displays a dollar value.',
   'HIGH', 'scenario', '/67/estimates');

-- 4. Update total_cases
update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '54876b89-b681-43a3-bbb1-f2aab5334e2e')
 where id = '54876b89-b681-43a3-bbb1-f2aab5334e2e';
