-- Seed: change-events SMOKE test suite
-- Generated by /test-scenario-audit change-events on 2026-04-20
-- Suite type: smoke | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('change-events', 'smoke', 'Change Events — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <smoke_suite_id> with the id returned above before running
-- delete from public.test_cases where suite_id = '<smoke_suite_id>';

-- After running the upsert, execute the insert below using the returned id:
/*
insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<smoke_suite_id>', '1.1', 'Navigation', 'Page load',
   'Open the Change Events page',
   'Verifies the list page renders without errors for project 67.',
   null,
   E'1. Log in as test1@mail.com\n2. Navigate to /67/change-events',
   'The page loads fully. The "Change Events" heading and the data table are visible (or an empty state with "No change events found").',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.2', 'Navigation', 'Table columns',
   'Table shows expected column headers',
   'Confirms the core column groups — CE, Revenue, Cost — render correctly.',
   null,
   E'1. Open /67/change-events\n2. Inspect the table header row',
   'Column headers are visible including at least: #, Title, Status, Scope, Revenue (Prime PCO), Cost ROM. The column-group labels "Change Event", "Revenue", and "Cost" appear above the relevant columns.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.3', 'Navigation', 'Primary action',
   'Create button opens the new change event form',
   'Confirms the main entry point for creating a change event is accessible.',
   null,
   E'1. Open /67/change-events\n2. Click the "Create" button in the page header',
   'The browser navigates to /67/change-events/new. A form titled "New Change Event" (or similar) is visible with a Title field.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.4', 'Navigation', 'Search',
   'Search bar filters the change events list',
   'Verifies that typing in the search box narrows the visible rows.',
   E'- At least one change event exists in project 67.',
   E'1. Open /67/change-events\n2. Click the search input and type a partial title or CE number (e.g. "CE-")',
   'The list updates to show only rows whose number or title contains the search term. The row count in the toolbar reflects the filtered count.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.5', 'Navigation', 'Status filter',
   'Status filter narrows the list to matching records',
   'Confirms the Status dropdown filter is wired to the API query.',
   E'- At least one change event with status "Open" exists.',
   E'1. Open /67/change-events\n2. Click "Filters" in the toolbar\n3. Select Status = "Open"\n4. Wait for the list to reload',
   'Only change events with status "Open" are shown. The active filter chip "Status: Open" appears in the toolbar.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.6', 'Navigation', 'Tab switching',
   'All list tabs load without error',
   'Checks that clicking each tab renders content or an empty state, not a crash.',
   null,
   E'1. Open /67/change-events\n2. Click the "Line Items" tab\n3. Click the "No Line Items" tab\n4. Click the "RFQs" tab\n5. Click the "Recycle Bin" tab\n6. Click the "All" tab to return',
   'Each tab loads without a JavaScript error or blank page. Each shows either rows or an empty state message appropriate to that tab.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.7', 'Navigation', 'Empty state',
   'Filtered list shows empty state when no records match',
   'Verifies the empty state component renders instead of a blank table.',
   null,
   E'1. Open /67/change-events\n2. In the search bar, type a string that matches no change event (e.g. "zzznomatch999")',
   'The table is replaced by an empty state message such as "No change events found" or "Try adjusting your search or filters." No JavaScript error is thrown.',
   'MEDIUM', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.8', 'Navigation', 'Row click → detail',
   'Clicking a change event row opens the detail page',
   'Confirms the row-click navigation to the detail page is working.',
   E'- At least one change event exists in project 67.',
   E'1. Open /67/change-events\n2. Click anywhere on the first data row (not a button)',
   'The browser navigates to /67/change-events/<id>. The detail page loads with the CE number and title visible in the header.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.9', 'Navigation', 'Detail page tabs',
   'Detail page tabs all load without error',
   'Confirms that every tab on the detail view renders its content or an empty state.',
   E'- At least one change event exists in project 67.',
   E'1. Open /67/change-events/<any-id>\n2. Click the "Line Items" tab\n3. Click the "Related Items" tab\n4. Click the "RFQs" tab\n5. Click the "History" tab',
   'Each tab renders without a JavaScript error. Line Items shows a table or empty state. Related Items, RFQs, and History show their respective content or empty state.',
   'HIGH', 'scenario', '/67/change-events'),

  ('<smoke_suite_id>', '1.10', 'Navigation', 'Grand totals row',
   'Footer grand totals row renders monetary columns',
   'Confirms the Revenue Prime PCO, Cost ROM, and Commitment totals are computed and displayed.',
   E'- At least one change event with line items exists in project 67.',
   E'1. Open /67/change-events\n2. Scroll to the bottom of the table',
   'A "Grand Totals" footer row is visible. The Revenue Prime PCO, Cost ROM, and Commitment columns show dollar amounts (e.g. "$1,000.00") rather than blank or "--".',
   'MEDIUM', 'scenario', '/67/change-events');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<smoke_suite_id>')
 where id = '<smoke_suite_id>';
*/
