-- Seed: invoices FEATURE test suite
-- Generated by /test-scenario-audit invoices on 2026-04-20
-- Suite type: feature | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('invoices', 'feature', 'Invoices — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;
-- NOTE: Replace <feature_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<feature_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<feature_suite_id>', '1.1', 'Create', 'Owner', 'Create owner invoice (happy path)', 'Creates owner invoice with valid contract + dates + line item inputs.', null, E'1. Open /67/invoices/new\n2. Select prime contract\n3. Fill invoice number, date, billing period\n4. Add line item values\n5. Save', 'Owner invoice is created and detail page opens with persisted values.', 'HIGH', 'scenario', '/67/invoices/new'),
  ('<feature_suite_id>', '1.2', 'Create', 'Owner validation', 'Owner invoice create enforces required fields', 'Validates missing required values block save.', null, E'1. Open /67/invoices/new\n2. Leave required fields empty\n3. Click Save', 'Inline validation appears and invoice is not created.', 'HIGH', 'scenario', '/67/invoices/new'),
  ('<feature_suite_id>', '1.3', 'Create', 'Subcontractor', 'Create subcontractor invoice (happy path)', 'Creates subcontractor invoice via subcontractor flow.', E'- At least one commitment exists.', E'1. Open /67/invoices?tab=subcontractor\n2. Trigger create flow\n3. Fill required fields\n4. Save', 'Subcontractor invoice is created and appears on subcontractor tab.', 'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '2.1', 'Edit', 'Owner', 'Edit owner invoice fields and persist', 'Updates owner invoice summary fields and verifies persistence after refresh.', E'- Existing owner invoice available.', E'1. Open owner invoice detail\n2. Click Edit\n3. Update notes/date/line-item amount\n4. Save\n5. Refresh', 'Updated values remain after refresh.', 'HIGH', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '2.2', 'Edit', 'Subcontractor', 'Edit subcontractor invoice fields and persist', 'Updates subcontractor invoice fields and verifies persistence.', E'- Existing subcontractor invoice available.', E'1. Open subcontractor invoice detail\n2. Edit fields\n3. Save\n4. Refresh', 'Updated values remain after refresh.', 'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '3.1', 'Delete', 'Owner', 'Delete owner invoice from list', 'Covers owner invoice delete row action.', E'- Deletable owner invoice exists.', E'1. Open owner tab\n2. Row menu -> Delete\n3. Confirm', 'Owner invoice row disappears and success toast appears.', 'HIGH', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '3.2', 'Delete', 'Subcontractor', 'Delete subcontractor invoice from list', 'Covers subcontractor invoice delete row action.', E'- Deletable subcontractor invoice exists.', E'1. Open subcontractor tab\n2. Row menu -> Delete\n3. Confirm', 'Subcontractor invoice row disappears and success toast appears.', 'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '4.1', 'Status', 'Owner approve-as-noted', 'Approve owner invoice as noted', 'Covers owner status transition via approve-as-noted action.', E'- Owner invoice in reviewable status exists.', E'1. Open owner invoice detail\n2. Trigger Approve as Noted\n3. Confirm', 'Status changes to approved_as_noted and persists.', 'HIGH', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '4.2', 'Status', 'Owner void', 'Void owner invoice with reason', 'Covers owner void transition with reason payload.', E'- Owner invoice not already paid/void exists.', E'1. Open owner invoice detail\n2. Trigger Void\n3. Provide reason and confirm', 'Status changes to void and reason is retained in history/notes.', 'HIGH', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '4.3', 'Status', 'Subcontractor submit', 'Submit subcontractor invoice', 'Covers draft -> under_review transition for subcontractor invoices.', E'- Draft subcontractor invoice exists.', E'1. Open subcontractor invoice detail\n2. Click Submit\n3. Confirm', 'Status changes from draft to under_review.', 'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),
  ('<feature_suite_id>', '4.4', 'Status', 'Subcontractor approve', 'Approve subcontractor invoice', 'Covers under_review -> approved transition.', E'- Under-review subcontractor invoice exists.', E'1. Open subcontractor detail\n2. Click Approve\n3. Confirm', 'Status changes to approved and persists.', 'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),
  ('<feature_suite_id>', '4.5', 'Status', 'Subcontractor revise', 'Revise subcontractor invoice', 'Covers under_review -> revise_and_resubmit transition.', E'- Under-review subcontractor invoice exists.', E'1. Open subcontractor detail\n2. Click Revise\n3. Confirm', 'Status changes to revise_and_resubmit.', 'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),
  ('<feature_suite_id>', '4.6', 'Status', 'Subcontractor void', 'Void subcontractor invoice', 'Covers subcontractor void transition.', E'- Subcontractor invoice in voidable status exists.', E'1. Open subcontractor detail\n2. Click Void\n3. Confirm', 'Status changes to void and invoice is excluded from active workflows.', 'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '5.1', 'Line Items', 'Owner calculations', 'Owner invoice line-item calculations update totals', 'Validates line-item arithmetic (gross, retention, net).', E'- Owner invoice with editable line items exists.', E'1. Edit owner line item amounts\n2. Save\n3. Observe totals panel', 'Totals recalculate correctly and match row-level amounts.', 'HIGH', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '5.2', 'Line Items', 'Subcontractor calculations', 'Subcontractor line-item calculations update totals', 'Validates subcontractor line-item rollup values.', E'- Subcontractor invoice with line items exists.', E'1. Edit subcontractor line item amounts\n2. Save', 'Rollup totals (gross/net/retainage) update consistently.', 'HIGH', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '6.1', 'Billing Periods', 'Create', 'Create billing period (happy path)', 'Creates billing period from Billing Periods tab modal.', null, E'1. Open /67/invoices?tab=billing-periods\n2. Click Create Billing Period\n3. Fill name/start/end/due date\n4. Create', 'New billing period row appears in the billing periods table.', 'HIGH', 'scenario', '/67/invoices?tab=billing-periods'),
  ('<feature_suite_id>', '6.2', 'Billing Periods', 'Edit/close', 'Edit billing period and toggle closed status', 'Covers billing period update path including close behavior.', E'- Existing billing period exists.', E'1. Open billing period row\n2. Update dates or name\n3. Toggle closed\n4. Save', 'Changes persist and status reflects closed/open setting.', 'MEDIUM', 'scenario', '/67/invoices?tab=billing-periods'),

  ('<feature_suite_id>', '7.1', 'Filters', 'Owner status', 'Owner status filter returns matching rows', 'Validates owner status filtering behavior.', null, E'1. Open owner tab\n2. Apply Status filter', 'All visible owner rows match selected status.', 'MEDIUM', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '7.2', 'Filters', 'Subcontractor status', 'Subcontractor status filter returns matching rows', 'Validates subcontractor status filtering behavior.', null, E'1. Open subcontractor tab\n2. Apply Status filter', 'All visible subcontractor rows match selected status.', 'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),
  ('<feature_suite_id>', '7.3', 'Search', 'Owner search', 'Owner search matches invoice number', 'Validates owner search by invoice number fragments.', null, E'1. Open owner tab\n2. Search by known invoice number fragment', 'Rows filter to matching owner invoices.', 'MEDIUM', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '7.4', 'Search', 'Subcontractor search', 'Subcontractor search matches invoice number', 'Validates subcontractor search by invoice number fragments.', null, E'1. Open subcontractor tab\n2. Search by known invoice number fragment', 'Rows filter to matching subcontractor invoices.', 'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '8.1', 'Documents', 'Owner PDF', 'Generate owner invoice PDF', 'Covers owner PDF endpoint/action.', E'- Owner invoice exists.', E'1. Open owner invoice detail\n2. Click Generate/Download PDF', 'PDF download/preview succeeds and contains invoice number + totals.', 'MEDIUM', 'scenario', '/67/invoices'),
  ('<feature_suite_id>', '8.2', 'Documents', 'Subcontractor PDF', 'Generate subcontractor invoice PDF', 'Covers subcontractor PDF endpoint/action.', E'- Subcontractor invoice exists.', E'1. Open subcontractor detail\n2. Click Generate/Download PDF', 'PDF download/preview succeeds and contains invoice number + totals.', 'MEDIUM', 'scenario', '/67/invoices?tab=subcontractor'),

  ('<feature_suite_id>', '9.1', 'Email', 'Owner email', 'Email owner invoice from detail', 'Covers email send action and payload validation.', E'- Mail transport configured for environment.', E'1. Open owner invoice detail\n2. Click Email\n3. Fill recipient + subject\n4. Send', 'Email send succeeds and success feedback appears.', 'LOW', 'scenario', '/67/invoices'),

  ('<feature_suite_id>', '10.1', 'Permissions', 'Read-only', 'Read-only user cannot create or mutate invoices', 'Permission gate on invoices list/detail actions.', E'- Read-only project user exists.', E'1. Log in as read-only user\n2. Open /67/invoices\n3. Inspect New Invoice and row actions', 'Mutating actions are hidden or blocked; user can still view lists/details.', 'MEDIUM', 'scenario', '/67/invoices');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<feature_suite_id>')
 where id = '<feature_suite_id>';
*/;
