-- Seed: Invoicing — Smoke test suite
-- Generated by /test-scenario-audit invoicing all
-- Supabase project: lgveqfnpkxvzbnnwuled

-- 1. Upsert suite
insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('invoicing', 'smoke', 'Invoicing — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <smoke_suite_id> with the id returned above before running step 2+.
-- Actual id used in production seed: 557d7bac-32b3-435e-b956-1b8b01e24cd3

-- 2. Wipe existing cases
delete from public.test_cases where suite_id = '557d7bac-32b3-435e-b956-1b8b01e24cd3';

-- 3. Insert cases
insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.1', 'Navigation', 'Page load',
   'Open the Invoices page',
   'Checks that the Invoices page renders without a 500 error and shows the Owner tab by default.',
   null,
   E'1. Log in as test1@mail.com\n2. Navigate to project "Vermillion Rise Warehouse"\n3. Click "Invoices" in the left sidebar\n4. Wait for the page to stop loading.',
   'The Invoices page loads. The "Owner" tab is active. Either a table of invoices or an empty state is visible. No error banner appears.',
   'HIGH', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.2', 'Navigation', 'Tab switching — Subcontractor',
   'Switch to the Subcontractor tab',
   'Checks that the Subcontractor invoices tab loads without error.',
   null,
   E'1. Open /67/invoices\n2. Click the "Subcontractor" tab\n3. Wait for the page to stop loading.',
   'The Subcontractor tab becomes active. The table shows subcontractor invoice rows or the empty state "No subcontractor invoices found". No error appears.',
   'HIGH', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.3', 'Navigation', 'Tab switching — Billing Periods',
   'Switch to the Billing Periods tab',
   'Checks that the Billing Periods tab loads and shows the "Create Billing Period" button.',
   null,
   E'1. Open /67/invoices\n2. Click the "Billing Periods" tab\n3. Wait for the page to stop loading.',
   'The Billing Periods tab is active. The header shows "Create Billing Period" button. Rows or empty state is visible. No error appears.',
   'HIGH', 'scenario', '/67/invoices?tab=billing-periods'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.4', 'Navigation', 'Owner tab columns',
   'Owner invoice table shows expected columns',
   'Verifies the Owner tab renders all default columns correctly.',
   null,
   E'1. Open /67/invoices (Owner tab)\n2. Observe the table header row.',
   'Columns visible include: Invoice #, Invoice Status, Billing Period, Gross Amount, Net Amount, Paid Amount. KPI row shows Under Review, Approved, Revise & Resubmit totals.',
   'HIGH', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.5', 'Navigation', 'KPI row renders',
   'KPI row shows on both Owner and Subcontractor tabs',
   'Checks the summary metrics bar above the table is visible and formatted.',
   null,
   E'1. Open /67/invoices (Owner tab)\n2. Observe the area above the table.\n3. Click the "Subcontractor" tab and observe again.',
   'Both tabs display a KPI row with three labelled metrics: "Under Review", "Approved", and "Revise & Resubmit". Values are formatted as currency (e.g. $0.00 if no data).',
   'HIGH', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.6', 'Create', 'New invoice form opens',
   'Clicking "New Invoice" opens the create-invoice page',
   'Checks the primary create action navigates to the correct form without error.',
   null,
   E'1. Open /67/invoices\n2. Click the "New Invoice" button in the page header.\n3. Wait for the page to stop loading.',
   'The browser navigates to /67/invoices/new. A form appears with fields for contract selection, invoice number, billing period, and line items.',
   'HIGH', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.7', 'Filters', 'Status filter applies on Owner tab',
   'Selecting a status filter narrows the Owner invoice list',
   'Checks that the status dropdown filter reduces the visible rows.',
   E'- At least one owner invoice exists in the project.',
   E'1. Open /67/invoices (Owner tab)\n2. Open the filter toolbar\n3. Select "Draft" from the Invoice Status filter\n4. Wait for the list to update.',
   'Only invoices with status "Draft" are shown. The filtered item count in the toolbar is less than or equal to the total count.',
   'MEDIUM', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.8', 'Filters', 'Search narrows Owner invoice list',
   'Typing in the search box filters the Owner invoice list',
   'Checks the search input reduces visible rows by invoice number.',
   E'- At least one owner invoice exists whose invoice number contains "INV".',
   E'1. Open /67/invoices (Owner tab)\n2. Type "INV" in the search box\n3. Wait for the list to update.',
   'Only rows whose Invoice # contains "INV" are shown. The toolbar shows a reduced item count.',
   'MEDIUM', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.9', 'Navigation', 'Owner invoice detail opens',
   'Clicking an invoice row navigates to the detail page',
   'Checks that the owner invoice detail page loads without a 500.',
   E'- At least one owner invoice exists in the project.',
   E'1. Open /67/invoices (Owner tab)\n2. Click the invoice number link in the first row.\n3. Wait for the page to stop loading.',
   'The browser navigates to /67/invoicing/<id>. The invoice detail page renders with the invoice header, status badge, and line-items section.',
   'HIGH', 'scenario', '/67/invoices'),

  ('557d7bac-32b3-435e-b956-1b8b01e24cd3', '1.10', 'Navigation', 'Empty state renders when filtered to nothing',
   'Filtering to a status with no results shows the empty state',
   'Checks that the empty-state component appears instead of a blank table.',
   null,
   E'1. Open /67/invoices (Owner tab)\n2. Apply a status filter that yields no results (e.g. "Paid" if none exist)\n3. Wait for the list to update.',
   'The table shows the empty state message "No owner invoices found" with the helper text "Try adjusting your search or filters." No blank white space or spinner remains.',
   'MEDIUM', 'scenario', '/67/invoices')
;

-- 4. Update total_cases
update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '557d7bac-32b3-435e-b956-1b8b01e24cd3')
 where id = '557d7bac-32b3-435e-b956-1b8b01e24cd3';
