-- Seed: submittals SMOKE test suite
-- Generated by /test-scenario-audit submittals on 2026-04-20
-- Suite type: smoke | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('submittals', 'smoke', 'Submittals — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <smoke_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<smoke_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<smoke_suite_id>', '1.1', 'Navigation', 'Page load',
   'Open the Submittals page',
   'Verifies submittals list renders and primary controls load.',
   null,
   E'1. Log in as test1@mail.com\n2. Navigate to /67/submittals',
   'Page loads with list/table content or valid empty state. No runtime error appears.',
   'HIGH', 'scenario', '/67/submittals'),

  ('<smoke_suite_id>', '1.2', 'Navigation', 'Tabs',
   'Switch Items, Packages, Spec Sections, Ball-in-Court, Recycle Bin tabs',
   'Ensures each top-level submittals tab loads without crashes.',
   null,
   E'1. Open /67/submittals\n2. Click Packages\n3. Click Spec Sections\n4. Click Ball-in-Court\n5. Click Recycle Bin\n6. Return to Items',
   'Each tab renders expected grouped/list view without errors.',
   'HIGH', 'scenario', '/67/submittals'),

  ('<smoke_suite_id>', '1.3', 'Navigation', 'Search',
   'Search filters submittal rows',
   'Confirms list search narrows rows by number/title/spec/type/status text.',
   E'- At least one submittal exists in project 67.',
   E'1. Open /67/submittals\n2. Type a known keyword in search',
   'Rows narrow to matches. Clearing search restores full list.',
   'HIGH', 'scenario', '/67/submittals'),

  ('<smoke_suite_id>', '1.4', 'Navigation', 'Status filter',
   'Status filter narrows submittals',
   'Validates active status filter changes visible rows.',
   null,
   E'1. Open /67/submittals\n2. Open Filters\n3. Select a status value',
   'Only rows for selected status remain visible; clear restores all rows.',
   'HIGH', 'scenario', '/67/submittals'),

  ('<smoke_suite_id>', '1.5', 'Navigation', 'Create action',
   'Create Submittal action opens new form',
   'Checks primary create entry point from list page.',
   null,
   E'1. Open /67/submittals\n2. Click Create Submittal',
   'Navigation occurs to /67/submittals/new and form renders.',
   'HIGH', 'scenario', '/67/submittals'),

  ('<smoke_suite_id>', '1.6', 'Navigation', 'Detail open',
   'Clicking a submittal row opens detail page',
   'Verifies row navigation to detail route.',
   E'- At least one submittal exists.',
   E'1. Open /67/submittals\n2. Click first row title/number',
   'Detail route opens and shows submittal header/details without errors.',
   'HIGH', 'scenario', '/67/submittals'),

  ('<smoke_suite_id>', '1.7', 'Navigation', 'Packages grouped view',
   'Packages tab search filters package list',
   'Checks grouped package panel search behavior.',
   null,
   E'1. Open /67/submittals?tab=packages\n2. Type text in package search field',
   'Package list filters to matching names; no errors appear.',
   'MEDIUM', 'scenario', '/67/submittals?tab=packages'),

  ('<smoke_suite_id>', '1.8', 'Navigation', 'Spec sections grouped view',
   'Spec Sections tab search filters spec list',
   'Checks grouped spec-section panel search behavior.',
   null,
   E'1. Open /67/submittals?tab=spec-sections\n2. Type text in spec search field',
   'Spec section list filters to matching sections/titles.',
   'MEDIUM', 'scenario', '/67/submittals?tab=spec-sections'),

  ('<smoke_suite_id>', '1.9', 'Navigation', 'Recycle restore',
   'Restore action appears and works on Recycle Bin',
   'Ensures deleted submittals can be restored from recycle bin view.',
   E'- At least one deleted submittal exists in recycle bin.',
   E'1. Open /67/submittals?tab=recycle-bin\n2. Click Restore on a row\n3. Confirm action if prompted',
   'Success feedback appears and item is removed from recycle bin.',
   'MEDIUM', 'scenario', '/67/submittals?tab=recycle-bin'),

  ('<smoke_suite_id>', '1.10', 'Navigation', 'Export/print',
   'Export CSV and Print are available on list view',
   'Confirms list reporting actions are wired.',
   null,
   E'1. Open /67/submittals\n2. Open Export menu\n3. Trigger CSV export and Print',
   'CSV download starts and print dialog opens with tabular content.',
   'MEDIUM', 'scenario', '/67/submittals');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<smoke_suite_id>')
 where id = '<smoke_suite_id>';
*/
