-- =============================================================================
-- Seed: Direct Costs — Feature test suite
-- Generated by /test-scenario-audit on 2026-05-14
-- Supabase project: lgveqfnpkxvzbnnwuled
-- =============================================================================

do $$
declare
  v_suite_id uuid;
begin
  -- 1. Upsert suite
  insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
  values ('direct-costs', 'feature', 'Direct Costs — Feature', 0)
  on conflict (tool_name, suite_type) do update set
    display_name      = excluded.display_name,
    last_generated_at = now()
  returning id into v_suite_id;

  if v_suite_id is null then
    select id into v_suite_id from public.test_suites
    where tool_name = 'direct-costs' and suite_type = 'feature';
  end if;

  -- 2. Wipe existing cases
  delete from public.test_cases where suite_id = v_suite_id;

  -- 3. Insert cases
  insert into public.test_cases
    (suite_id, test_number, category, subcategory, test_name,
     context_note, setup_steps, steps, expected_result, priority,
     test_type, start_url)
  values
    -- NAVIGATION
    (v_suite_id, '1.1', 'Navigation', 'Page load',
     'Direct Costs page loads with correct title and toolbar',
     'Full page-load check — title, tabs, toolbar, and table must all render.',
     null,
     E'1. Log in as test1@mail.com\n2. Navigate to /67/direct-costs\n3. Wait for the page to stop loading.',
     'Page title "Direct Costs" is visible. Two tabs ("Summary" and "Summary by Cost Code") are present. The toolbar shows a search box. Table headers Date, Vendor, Type, Status, Amount are visible.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.2', 'Navigation', 'Tab — Cost Code view',
     'Summary by Cost Code tab renders grouped rows',
     'Checks the cost-code hierarchy view loads and groups data by division/cost code.',
     E'- On the Direct Costs summary tab.',
     E'1. Click "Summary by Cost Code" tab\n2. Wait for the view to load.',
     'Rows are grouped by division label. Each group shows Budget Code, Vendor, Type, Invoice #, Status, Description, Amount, Received columns.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.3', 'Navigation', 'Tab persistence',
     'Returning to Summary tab restores default columns',
     'Switching back to Summary from Cost Code should restore the original column set.',
     E'- User has switched to the "Summary by Cost Code" tab.',
     E'1. Click "Summary" tab\n2. Observe the table columns.',
     'Columns Date, Vendor, Type, Status, Amount are shown. Cost-code-only columns (Budget Code, Division) are not present.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- READ / DETAIL
    (v_suite_id, '2.1', 'Read', 'Preview pane',
     'Clicking a row (desktop) opens the detail preview pane',
     'On desktop, row click should open a side panel, not navigate away.',
     E'- On the Direct Costs summary tab on a desktop viewport.',
     E'1. Click any row in the table.\n2. Observe the right side of the screen.',
     'A side preview pane slides in showing the selected direct cost details (vendor, amount, status, date). The table list is still visible on the left.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '2.2', 'Read', 'Detail page',
     'Opening a record''s detail page shows all fields and line items',
     'The detail page must render Cost Information, Record Information, and a Line Items table.',
     E'- At least one direct cost record exists in project 67.',
     E'1. Click the three-dots (⋯) menu on any row\n2. Click "View"\n3. Wait for the detail page to load.',
     'Detail page shows: cost type badge, status badge, Total Amount (large), Date, Vendor, Invoice Number, Received Date (if present), Paid Date (if present). If the record has line items, a "Line Items" table is visible with columns Budget Code, Description, Qty, UOM, Unit Cost, Line Total and a footer total row.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '2.3', 'Read', 'ERP sync link',
     'Synced records show an Acumatica link in ERP Status column',
     'When a record has been synced from Acumatica, the ERP Status column should show a clickable reference number.',
     E'- At least one synced direct cost exists (acumatica_ref_nbr is not null).\n- Enable the "ERP Status" column via column visibility toggle.',
     E'1. Open column visibility toggle and enable "ERP Status"\n2. Find a row with a reference value in ERP Status column\n3. Observe the cell value.',
     'ERP Status cell shows the doc type + reference number as a link (e.g. "AP 000123"). Clicking the link opens the Acumatica URL in a new tab.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    (v_suite_id, '2.4', 'Read', 'Unsynced ERP status',
     'Unsynced records show "Not synced" in ERP Status',
     'Records without an Acumatica sync timestamp should clearly say "Not synced".',
     E'- ERP Status column is visible.\n- At least one record with no Acumatica sync exists.',
     E'1. Enable "ERP Status" column\n2. Find a row with no Acumatica reference\n3. Observe the ERP Status cell.',
     '"Not synced" text appears in the ERP Status cell for that row (no link, no badge).',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- READ-ONLY ENFORCEMENT
    (v_suite_id, '3.1', 'Read', 'Create blocked — UI',
     '"Add Direct Cost" shows the read-only notice, not a form',
     'Direct costs are Acumatica-synced. Navigating to /new must show a notice page, not a create form.',
     null,
     E'1. Click "Add Direct Cost" in the page header.',
     'Page title "Direct Costs Are Read-Only" is shown. The description explains records sync from Acumatica. A "Back to Direct Costs" button is present. No form fields are shown.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '3.2', 'Read', 'Create blocked — API',
     'POST /api/projects/67/direct-costs returns 405',
     'The API must reject create attempts with a read-only guardrail error.',
     E'- Authenticated session active.',
     E'1. Send POST /api/projects/67/direct-costs with a JSON body\n2. Observe the HTTP response.',
     'Response is HTTP 405 with error code READ_ONLY_RESOURCE and message "Direct costs are read-only in Alleato. Sync from Acumatica to add records."',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '3.3', 'Read', 'Bulk actions blocked — API',
     'POST /api/projects/67/direct-costs/bulk returns 405',
     'Bulk status-update and bulk delete must be blocked at the API level.',
     E'- Authenticated session active.',
     E'1. Send POST /api/projects/67/direct-costs/bulk with operation "delete" and an ids array\n2. Observe the HTTP response.',
     'Response is HTTP 405 with error code READ_ONLY_RESOURCE.',
     'HIGH', 'scenario', '/67/direct-costs'),

    -- SEARCH
    (v_suite_id, '4.1', 'Filters', 'Search',
     'Search matches vendor name, invoice number, and amount',
     'The search bar should filter across multiple fields simultaneously.',
     E'- At least one direct cost record exists.',
     E'1. Type a known vendor name fragment into the search box\n2. Observe the list\n3. Clear the search and type a known invoice number\n4. Observe the list.',
     'Step 2: Only rows whose vendor name matches are shown. Step 4: Only rows whose invoice number matches are shown. Row count updates immediately after each keystroke (debounced).',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '4.2', 'Filters', 'Search — amount',
     'Searching by a dollar amount filters the list',
     'Amount values must be searchable by formatted string (e.g. "1,234.56").',
     E'- At least one record exists.',
     E'1. Note the total amount of any record (e.g. "$1,234.56")\n2. Type "1,234" into the search box.',
     'The row with that amount is shown. Other rows that do not contain "1,234" in vendor/invoice/description/amount are hidden.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- FILTERS
    (v_suite_id, '5.1', 'Filters', 'Status filter',
     'Each status filter value narrows the list correctly',
     'Covers all four status values in a single case.',
     E'- Direct Costs page is open.',
     E'1. Open the filter panel\n2. Select "Pending" from Status\n3. Apply and observe\n4. Change to "Approved" and observe\n5. Change to "Draft" and observe\n6. Change to "Revise and Resubmit" and observe\n7. Clear filters.',
     'Each filter application shows only records matching the selected status. After clearing, the full list returns.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '5.2', 'Filters', 'Cost Type filter',
     'Cost Type filter shows only Expense, Invoice, or Subcontractor Invoice records',
     'Checks all three cost type options.',
     E'- Direct Costs page is open.',
     E'1. Open filters, select "Invoice" for Cost Type and apply\n2. Observe the list\n3. Change to "Expense"\n4. Change to "Subcontractor Invoice"\n5. Clear filters.',
     'Each selection narrows the list to rows with the matching cost type. Rows with other types are hidden.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '5.3', 'Filters', 'Date range filter',
     'Date From and Date To filter correctly bound the visible records',
     'Records outside the selected date window must be excluded.',
     E'- Multiple records with different dates exist.',
     E'1. Open filters, set "Date From" to **2025-01-01** and "Date To" to **2025-12-31**\n2. Apply\n3. Observe each visible row''s Date column.',
     'Only records dated between Jan 1 2025 and Dec 31 2025 (inclusive) are shown. Records outside this range are hidden.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '5.4', 'Filters', 'Amount range filter',
     'Min and Max Amount filters bound the visible records',
     'Records outside the amount range must be excluded.',
     E'- Multiple records with varying amounts exist.',
     E'1. Open filters, set "Min Amount" to **500** and "Max Amount" to **5000**\n2. Apply\n3. Check each visible row''s Amount column.',
     'Only records with total_amount between $500 and $5,000 (inclusive) are shown. Rows outside that range are hidden.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    (v_suite_id, '5.5', 'Filters', 'Combined filters',
     'Combining Status + Cost Type filters applies both constraints',
     'Verifies AND logic when multiple filters are active.',
     E'- Direct Costs page is open.',
     E'1. Set Status filter to "Approved"\n2. Set Cost Type filter to "Invoice"\n3. Apply both\n4. Observe results.',
     'Only records that are BOTH Approved AND of type Invoice are shown. Records that match only one condition are excluded.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    (v_suite_id, '5.6', 'Filters', 'Clear filters',
     'Clearing all filters restores the full record list',
     'Confirm the clear action removes all active filter state.',
     E'- At least one filter is active.',
     E'1. With an active filter applied, click "Clear filters"\n2. Observe the list.',
     'All filter chips disappear. The full unfiltered list is shown. Row count returns to the total for the project.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- SORTING
    (v_suite_id, '6.1', 'Filters', 'Column sort',
     'Clicking column headers sorts the list ascending then descending',
     'Covers sort toggling on Date and Amount columns.',
     E'- Direct Costs summary tab is open with multiple records.',
     E'1. Click the "Date" column header\n2. Observe order\n3. Click "Date" again\n4. Observe order\n5. Click "Amount" header\n6. Observe order.',
     'First click: rows sorted by date ascending (oldest first). Second click: rows sorted descending (newest first). Amount click: rows sorted by total_amount ascending.',
     'HIGH', 'scenario', '/67/direct-costs'),

    -- COLUMN VISIBILITY
    (v_suite_id, '7.1', 'Filters', 'Column visibility toggle',
     'Toggling optional columns shows and hides them in the table',
     'Verifies that hidden columns (Received, Paid, Description, ERP Status) can be toggled on and off.',
     E'- Direct Costs summary tab is open.',
     E'1. Open the column visibility menu\n2. Enable "Received" column\n3. Observe the table\n4. Enable "Paid" column\n5. Enable "Description" column\n6. Disable "Vendor" column\n7. Observe the table.',
     'Enabling "Received" adds a Received column. Enabling "Paid" adds a Paid column. Enabling "Description" adds a Description column. Disabling "Vendor" removes the Vendor column from the table.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- PAGINATION
    (v_suite_id, '8.1', 'Filters', 'Pagination',
     'Pagination controls work when record count exceeds per-page limit',
     'Checks that next/previous page navigation changes the visible rows.',
     E'- More than 25 direct cost records exist for project 67 (or set per-page to a small value).',
     E'1. If needed, set per-page to **10**\n2. Click the "Next page" button\n3. Observe which rows are shown\n4. Click "Previous page".',
     'Page 2 shows a different set of records than page 1. Clicking previous returns to the first set. Current page indicator updates accordingly.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- VIEW TOGGLE
    (v_suite_id, '9.1', 'Navigation', 'List view toggle',
     'Switching to list view renders card-style items',
     'Verifies the list view mode renders correctly for the summary tab.',
     E'- Direct Costs summary tab is open in table view.',
     E'1. Click the list view icon in the toolbar\n2. Observe the layout.',
     'Records switch to a card/list layout showing Vendor name, Invoice #, Cost Type, Amount, Status, and Date. No table headers are shown.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- FOOTER TOTALS
    (v_suite_id, '10.1', 'Read', 'Footer totals',
     'Footer row shows correct sum of filtered records',
     'The footer total must reflect the filtered set, not the entire project.',
     E'- Direct Costs summary tab is open with multiple records.',
     E'1. Note the footer "Totals" row Amount value\n2. Apply a Status filter (e.g. "Approved")\n3. Note the new footer total.',
     'After filtering, the footer total decreases to show only the sum of visible records. The total is numerically equal to the sum of the Amount column values shown.',
     'HIGH', 'scenario', '/67/direct-costs'),

    -- ERP SYNC
    (v_suite_id, '11.1', 'Navigation', 'ERP sync button',
     'Clicking the sync icon triggers an Acumatica sync and shows a toast',
     'Verifies the refresh/sync button calls the ERP sync endpoint and reports the result.',
     E'- Direct Costs page is open.',
     E'1. Click the refresh icon (sync from ERP) in the toolbar\n2. Wait for the action to complete.',
     'A toast notification appears. On success: "ERP sync complete: X created, Y updated". On error: an error toast with a descriptive message. The sync icon shows a spinner while in progress.',
     'HIGH', 'scenario', '/67/direct-costs'),

    -- EXPORT
    (v_suite_id, '12.1', 'Navigation', 'Export dialog',
     'Export button opens the export dialog with format options',
     'Checks the export UI renders and offers CSV and Excel options.',
     E'- Direct Costs page is open.',
     E'1. Click the export icon in the toolbar\n2. Observe the dialog that opens.',
     'An export dialog opens showing format options (at minimum CSV and Excel). A download or confirm button is present.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    (v_suite_id, '12.2', 'Navigation', 'Export CSV',
     'Exporting to CSV downloads a file with correct column headers',
     'End-to-end export: dialog → CSV download.',
     E'- Export dialog is open.',
     E'1. Select "CSV" format\n2. Click the download/export button\n3. Open the downloaded file.',
     'A .csv file downloads. The first row contains column headers matching the visible columns (e.g. Date, Vendor, Type, Status, Amount). Data rows follow.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- SELECTION
    (v_suite_id, '13.1', 'Navigation', 'Row selection',
     'Selecting individual rows increments the selection count',
     'Verifies the row selection checkboxes work on the summary table.',
     E'- Direct Costs summary tab is open with multiple records.',
     E'1. Click the checkbox on the first row\n2. Click the checkbox on a second row\n3. Observe the toolbar.',
     'Toolbar shows "2 selected" (or similar count indicator). Each checked row is visually highlighted.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    (v_suite_id, '13.2', 'Navigation', 'Select all',
     'Select-all checkbox selects every visible row',
     'Checks the header checkbox selects all filtered rows, not just the current page.',
     E'- Direct Costs page is open with multiple records.',
     E'1. Click the header checkbox (select all)\n2. Observe the selection count.',
     'All visible rows are selected. The selection count matches the filteredItems count shown in the toolbar.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- MOBILE
    (v_suite_id, '14.1', 'Navigation', 'Mobile — row tap opens detail',
     'On a mobile viewport, tapping a row navigates to the full detail page',
     'On mobile, row click should navigate (not open a panel) to avoid obscuring the list.',
     E'- Viewport is set to 375px wide (mobile).',
     E'1. Resize viewport to 375px\n2. Navigate to /67/direct-costs\n3. Tap any row.',
     'The browser navigates to the /67/direct-costs/[costId] detail page. The list is no longer visible.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- BACK NAVIGATION
    (v_suite_id, '15.1', 'Navigation', 'Back navigation from detail',
     'Back button on detail page returns to the Direct Costs list',
     'Confirms the onBack handler works and does not cause a dead end.',
     E'- User is on a direct cost detail page.',
     E'1. Click the back arrow / "Back" button in the page header.',
     'Browser navigates back to the Direct Costs list (/67/direct-costs). The list is fully rendered with previous scroll position or filter state retained.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    -- PERMISSIONS / AUTH
    (v_suite_id, '16.1', 'Permissions', 'Auth required',
     'Unauthenticated request to GET /api/projects/67/direct-costs returns 401',
     'API must reject unauthenticated access.',
     E'- No auth session active.',
     E'1. Send GET /api/projects/67/direct-costs without an auth cookie or token.',
     'Response is HTTP 401 with an authentication-required error message.',
     'HIGH', 'scenario', '/67/direct-costs'),

    -- EDGE CASES
    (v_suite_id, '17.1', 'Edge', 'Invalid cost ID returns 404',
     'Navigating to a non-existent direct cost ID shows the not-found state',
     'Checks graceful handling of a bogus costId in the URL.',
     null,
     E'1. Navigate to /67/direct-costs/00000000-0000-0000-0000-000000000000\n2. Wait for the page to load.',
     'The detail page shows "Direct cost not found" text and a "Back to Direct Costs" button. No unhandled error or blank screen.',
     'MEDIUM', 'scenario', '/67/direct-costs'),

    (v_suite_id, '17.2', 'Edge', 'Record with no line items',
     'Detail page for a record with zero line items does not show the Line Items section',
     'The line items section is conditional — it must be hidden when the array is empty.',
     E'- A direct cost record with no line items exists in project 67.',
     E'1. Navigate to the detail page of a record with no line items.',
     'The Cost Information section is shown. No "Line Items" section heading or table is rendered.',
     'LOW', 'scenario', '/67/direct-costs'),

    (v_suite_id, '17.3', 'Edge', 'URL search params preserved on tab switch',
     'Active search query is preserved when switching between Summary and Cost Code tabs',
     'Tab navigation must not clear the search state.',
     E'- Direct Costs page is open with an active search query.',
     E'1. Type "test" in the search box\n2. Click "Summary by Cost Code" tab\n3. Click "Summary" tab\n4. Observe the search box.',
     'After returning to the Summary tab, the search box still contains "test" and the list is still filtered accordingly.',
     'LOW', 'scenario', '/67/direct-costs');

  -- 4. Update total_cases
  update public.test_suites
     set total_cases = (select count(*) from public.test_cases where suite_id = v_suite_id)
   where id = v_suite_id;
end $$;
