-- Seed: submittals FEATURE test suite
-- Generated by /test-scenario-audit submittals on 2026-04-20
-- Suite type: feature | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('submittals', 'feature', 'Submittals — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <feature_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<feature_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<feature_suite_id>', '1.1', 'Create', 'Base', 'Create submittal with required fields (happy path)', 'Creates a submittal via standard form flow.', null, E'1. Open /67/submittals/new\n2. Fill required fields (title/type/spec/status)\n3. Save', 'Submittal is created and appears in list and detail.', 'HIGH', 'scenario', '/67/submittals/new'),
  ('<feature_suite_id>', '1.2', 'Create', 'Validation', 'Create blocks when required fields are missing', 'Required-field validation coverage in create form.', null, E'1. Open /67/submittals/new\n2. Leave required fields empty\n3. Save', 'Inline validation appears and no record is created.', 'HIGH', 'scenario', '/67/submittals/new'),
  ('<feature_suite_id>', '1.3', 'Create', 'From package', 'Create submittal from package context', 'Covers create-from-package entrypoint and prefilled package binding.', E'- At least one package exists.', E'1. Open Packages tab\n2. Start create from package\n3. Save submittal', 'New submittal links to selected package.', 'HIGH', 'scenario', '/67/submittals?tab=packages'),
  ('<feature_suite_id>', '1.4', 'Create', 'From specification', 'Create submittal from specification section context', 'Covers create-from-spec entrypoint and prefilled spec section.', E'- At least one spec section exists.', E'1. Open Spec Sections tab\n2. Start create from specification\n3. Save', 'New submittal retains selected specification section.', 'MEDIUM', 'scenario', '/67/submittals?tab=spec-sections'),

  ('<feature_suite_id>', '2.1', 'Edit', 'General fields', 'Edit submittal fields and persist after refresh', 'Updates core fields and confirms persistence.', E'- Existing submittal available.', E'1. Open submittal detail\n2. Click Edit\n3. Update title/spec/status\n4. Save\n5. Refresh', 'Updated values remain after refresh and on list.', 'HIGH', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '2.2', 'Edit', 'Revision', 'Create a new revision for existing submittal', 'Covers revisions endpoint and revision increment behavior.', E'- Existing submittal available.', E'1. Open submittal detail\n2. Trigger New Revision\n3. Save changes', 'Revision number increments and revision record is accessible.', 'HIGH', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '3.1', 'Delete', 'Soft delete', 'Delete submittal from Items tab', 'Verifies delete moves item out of active list.', E'- Deletable submittal exists.', E'1. Open Items tab\n2. Delete row\n3. Confirm', 'Submittal disappears from active list and appears in recycle bin.', 'HIGH', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '3.2', 'Delete', 'Restore', 'Restore deleted submittal from Recycle Bin', 'Verifies restoration back to active items.', E'- Deleted submittal exists in recycle bin.', E'1. Open Recycle Bin tab\n2. Click Restore on submittal', 'Submittal returns to active Items tab.', 'HIGH', 'scenario', '/67/submittals?tab=recycle-bin'),

  ('<feature_suite_id>', '4.1', 'Workflow', 'Step assignment', 'Add workflow steps to submittal', 'Covers workflow step management on detail page.', E'- Existing submittal available.', E'1. Open submittal detail\n2. Add workflow step with assignee\n3. Save', 'Workflow step appears in ordered list with assignee.', 'HIGH', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '4.2', 'Workflow', 'Respond', 'Responder updates workflow step status', 'Validates response path and latest response rollup.', E'- Existing workflow step assigned to current user.', E'1. Open submittal detail\n2. Open assigned step\n3. Submit response status/comments', 'Step response is saved and latest response updates.', 'HIGH', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '4.3', 'Workflow', 'Ball-in-Court', 'Ball-in-Court tab reflects pending responsibility', 'Ensures pending assignments populate ball-in-court grouped view.', E'- At least one submittal has pending assigned step.', E'1. Open /67/submittals?tab=ball-in-court', 'Grouped view includes pending submittal under responsible party.', 'MEDIUM', 'scenario', '/67/submittals?tab=ball-in-court'),

  ('<feature_suite_id>', '5.1', 'Attachments', 'Upload', 'Upload attachment to submittal', 'Covers attachment upload endpoint and UI.', E'- Have test file available.', E'1. Open submittal detail\n2. Upload attachment\n3. Save if prompted', 'Attachment row appears with file metadata.', 'HIGH', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '5.2', 'Attachments', 'Current version', 'Set attachment as current and verify flag', 'Ensures is_current behavior is reflected in attachments list.', E'- Submittal has multiple attachments.', E'1. Open attachments section\n2. Mark one file as current', 'Selected file shows current indicator; previous current clears.', 'MEDIUM', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '6.1', 'Distribution', 'Distribute', 'Distribute submittal to recipients', 'Covers submittal distribution send flow.', E'- Recipient users available in project.', E'1. Open submittal detail\n2. Click Distribute\n3. Select recipients and message\n4. Send', 'Distribution record appears with recipients and timestamp.', 'HIGH', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '7.1', 'Related Items', 'Link', 'Link related items to submittal', 'Covers related-items add flow.', E'- Related records exist (RFI/CO/etc).', E'1. Open submittal detail\n2. Add related item\n3. Save', 'Related item appears in linked items list.', 'MEDIUM', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '8.1', 'Duplicate', 'Clone', 'Duplicate submittal creates new draft', 'Validates duplicate endpoint and copied field behavior.', E'- Existing source submittal exists.', E'1. Open source submittal\n2. Click Duplicate\n3. Confirm', 'New submittal is created with copied data and distinct identifier.', 'HIGH', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '9.1', 'Packages', 'Create package', 'Create new submittal package', 'Covers package creation modal flow.', null, E'1. Open Packages tab\n2. Click Create Package\n3. Fill name/description\n4. Create', 'New package appears in packages list.', 'MEDIUM', 'scenario', '/67/submittals?tab=packages'),
  ('<feature_suite_id>', '9.2', 'Packages', 'Edit package', 'Edit existing package metadata', 'Covers package edit modal flow.', E'- Existing package available.', E'1. Open Packages tab\n2. Edit package\n3. Save', 'Package metadata updates in grouped list.', 'LOW', 'scenario', '/67/submittals?tab=packages'),

  ('<feature_suite_id>', '10.1', 'Filters', 'Combined', 'Combined filters narrow rows correctly', 'Applies status + package + spec filters together.', null, E'1. Open /67/submittals\n2. Apply multiple filters\n3. Observe results', 'Visible rows satisfy all active filters.', 'MEDIUM', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '10.2', 'Filters', 'Clear', 'Clear Filters resets to full list', 'Ensures filter reset returns default list state.', null, E'1. Apply one or more filters\n2. Click Clear Filters', 'All filters clear and full list returns.', 'LOW', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '11.1', 'Export', 'CSV', 'Export submittals CSV includes visible columns', 'Validates export payload and column header presence.', null, E'1. Open Items tab\n2. Trigger CSV export', 'CSV downloads and includes visible list columns.', 'MEDIUM', 'scenario', '/67/submittals'),
  ('<feature_suite_id>', '11.2', 'Export', 'Print', 'Print renders table preview with current filters', 'Validates print output honors filtered set.', null, E'1. Apply search/filter\n2. Trigger Print', 'Print preview opens with filtered rows and visible columns.', 'LOW', 'scenario', '/67/submittals'),

  ('<feature_suite_id>', '12.1', 'Permissions', 'Read-only', 'Read-only user cannot create/edit/delete submittals', 'Covers permission gates for mutation actions.', E'- Read-only project user exists.', E'1. Log in as read-only user\n2. Open /67/submittals\n3. Inspect create and row actions', 'Mutating controls are hidden/disabled while read access remains.', 'MEDIUM', 'scenario', '/67/submittals');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<feature_suite_id>')
 where id = '<feature_suite_id>';
*/
