-- Seed: specifications FEATURE test suite
-- Generated by /test-scenario-audit specifications on 2026-04-20
-- Suite type: feature | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('specifications', 'feature', 'Specifications — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <feature_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<feature_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<feature_suite_id>', '1.1', 'Create', 'Section', 'Create specification section with required fields', 'Covers spec section creation flow.', null, E'1. Open specifications create flow\n2. Fill section number/title/status\n3. Save', 'Section is created and appears in list.', 'HIGH', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '1.2', 'Create', 'Validation', 'Create blocks when required fields are missing', 'Validates create form required fields.', null, E'1. Open create/edit dialog\n2. Leave required fields empty\n3. Save', 'Validation errors appear and save is blocked.', 'HIGH', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '1.3', 'Create', 'Area linkage', 'Create section with linked areas', 'Verifies area assignment on create.', E'- At least one area exists.', E'1. Create section\n2. Assign one or more areas\n3. Save', 'Section persists with selected area chips/tags.', 'MEDIUM', 'scenario', '/67/specifications'),

  ('<feature_suite_id>', '2.1', 'Edit', 'Section metadata', 'Edit section metadata and persist', 'Updates section number/title/status and verifies persistence.', E'- Existing section available.', E'1. Open section\n2. Edit metadata\n3. Save\n4. Refresh', 'Updated values persist after refresh and on list row.', 'HIGH', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '2.2', 'Edit', 'Archive/unarchive', 'Archive section and verify recycle behavior', 'Covers archive action and movement into recycle tab.', E'- Existing active section available.', E'1. Archive section from list action\n2. Open recycle tab', 'Section is hidden from active list and visible in recycle tab.', 'HIGH', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '2.3', 'Edit', 'Restore', 'Restore archived section from recycle tab', 'Covers restore flow back to active.', E'- Existing archived section exists.', E'1. Open recycle tab\n2. Restore section', 'Section returns to active list.', 'HIGH', 'scenario', '/67/specifications?spec_tab=recycle'),

  ('<feature_suite_id>', '3.1', 'Revisions', 'Upload', 'Upload new revision on section detail', 'Covers add-revision dialog and upload endpoint.', E'- Existing section exists.', E'1. Open section detail\n2. Click Add Revision\n3. Upload file and save', 'New revision appears in revision history with incremented revision number.', 'HIGH', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '3.2', 'Revisions', 'Set current', 'Set a non-current revision as current', 'Covers set-current revision action.', E'- Section has at least two revisions.', E'1. Open revision history\n2. Click Set Current on older revision', 'Selected revision is marked current; previous current clears.', 'HIGH', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '3.3', 'Revisions', 'Delete', 'Delete non-current revision', 'Covers revision delete action and list refresh.', E'- Section has deletable non-current revision.', E'1. Open revision history\n2. Delete non-current revision\n3. Confirm', 'Revision row is removed; remaining revisions unchanged.', 'MEDIUM', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '3.4', 'Revisions', 'Download by revision', 'Download specific revision from history', 'Covers per-revision download action.', E'- Section has at least one revision.', E'1. Open revision history\n2. Click Download on a revision', 'Download succeeds for chosen revision.', 'MEDIUM', 'scenario', '/67/specifications'),

  ('<feature_suite_id>', '4.1', 'Subscriptions', 'Subscribe', 'Subscribe to section updates', 'Covers subscribe toggle on list page.', E'- Existing section available.', E'1. Toggle Subscribe for a section', 'Subscription state updates and persists on reload.', 'MEDIUM', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '4.2', 'Subscriptions', 'Unsubscribe', 'Unsubscribe from section updates', 'Covers unsubscribe toggle behavior.', E'- Existing subscribed section exists.', E'1. Toggle Subscribe off', 'Section unsubscribes and state persists.', 'LOW', 'scenario', '/67/specifications'),

  ('<feature_suite_id>', '5.1', 'Revisions Tab', 'List', 'Revisions tab shows cross-section revision feed', 'Verifies revisions tab dataset and columns.', null, E'1. Open /67/specifications?spec_tab=revisions', 'Revisions tab lists rows with section, revision, file, size, and uploaded time.', 'MEDIUM', 'scenario', '/67/specifications?spec_tab=revisions'),
  ('<feature_suite_id>', '5.2', 'Revisions Tab', 'Search', 'Revisions tab search filters by section/file', 'Validates revision tab search.', null, E'1. Open revisions tab\n2. Search by file or section', 'Rows filter to matching records.', 'LOW', 'scenario', '/67/specifications?spec_tab=revisions'),

  ('<feature_suite_id>', '6.1', 'Filters', 'Combined', 'Combined status + area filters narrow rows', 'Applies multiple filters concurrently.', null, E'1. Apply status and area filters together', 'Visible rows satisfy both filters.', 'MEDIUM', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '6.2', 'Filters', 'Clear', 'Clear filters restores full list', 'Ensures reset behavior after filtering.', null, E'1. Apply filters\n2. Clear filters', 'All filters clear and full list returns.', 'LOW', 'scenario', '/67/specifications'),

  ('<feature_suite_id>', '7.1', 'Export', 'CSV specs', 'Export CSV from specifications tab', 'Validates specs-tab CSV export content.', null, E'1. Open specs tab\n2. Export CSV', 'CSV includes section/title/status/revision columns.', 'MEDIUM', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '7.2', 'Export', 'CSV revisions', 'Export CSV from revisions tab', 'Validates revisions-tab CSV export content.', null, E'1. Open revisions tab\n2. Export CSV', 'CSV includes section/revision/file/uploaded columns.', 'MEDIUM', 'scenario', '/67/specifications?spec_tab=revisions'),
  ('<feature_suite_id>', '7.3', 'Export', 'Print specs', 'Print specs tab with current filters', 'Validates print output for specs list.', null, E'1. Apply search/filter\n2. Print', 'Print preview opens with filtered specs rows.', 'LOW', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '7.4', 'Export', 'Print revisions', 'Print revisions tab with current filters', 'Validates print output for revisions list.', null, E'1. Open revisions tab\n2. Apply search\n3. Print', 'Print preview opens with filtered revisions rows.', 'LOW', 'scenario', '/67/specifications?spec_tab=revisions'),

  ('<feature_suite_id>', '8.1', 'Areas', 'Create area', 'Create area used by specifications', 'Covers area management API-backed flow.', null, E'1. Open area management\n2. Create new area\n3. Save', 'Area is created and available in area filters/assignments.', 'LOW', 'scenario', '/67/specifications'),
  ('<feature_suite_id>', '8.2', 'Areas', 'Update area', 'Update existing area name', 'Covers area update behavior.', E'- Existing area available.', E'1. Edit area name\n2. Save', 'Area name updates wherever displayed.', 'LOW', 'scenario', '/67/specifications'),

  ('<feature_suite_id>', '9.1', 'Permissions', 'Read-only', 'Read-only user cannot mutate specifications/revisions', 'Permission gate for create/edit/archive/upload/delete actions.', E'- Read-only project user exists.', E'1. Log in as read-only user\n2. Open /67/specifications\n3. Inspect mutation actions', 'Mutation controls are hidden/disabled while read access remains.', 'MEDIUM', 'scenario', '/67/specifications');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<feature_suite_id>')
 where id = '<feature_suite_id>';
*/
