-- =============================================================================
-- Seed: estimates — Feature Test Suite
-- Generated by /test-scenario-audit on 2026-05-14
-- Supabase project: lgveqfnpkxvzbnnwuled
-- =============================================================================

-- 1. Upsert suite
insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('estimates', 'feature', 'Estimates — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <suite_id> below with the id returned above before re-running.
-- The seeded suite id is: 3988da5c-ab91-4942-a4bf-3d43963d8cb6

-- 2. Wipe existing cases
delete from public.test_cases where suite_id = '3988da5c-ab91-4942-a4bf-3d43963d8cb6';

-- 3. Insert cases
insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  -- CREATE
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '1.1', 'Create', 'Happy path',
   'Create an estimate with all fields filled',
   'Covers the full create form: every field saved correctly and user lands on the detail page.',
   null,
   E'1. Click "New Estimate" on the Estimates list page.\n2. Type "Warehouse HVAC Replacement R1" in the Title field.\n3. Type "EST-001" in the Estimate Number field.\n4. Set Revision to **2**.\n5. Set Status to "Pending Review".\n6. Set Estimate Type to "Design Build".\n7. Set Date to **2026-06-01**.\n8. Type "John Smith" in the Estimator field.\n9. Type "Fresno, CA" in the Location field.\n10. Set Project Duration to **14** weeks.\n11. Set Insurance Rate to **0.015**.\n12. Set Fee Rate to **0.12**.\n13. Set Contingency Amount to **5000**.\n14. Type "Initial rough-order-of-magnitude estimate." in the Notes field.\n15. Click "Create Estimate".\n16. Wait for the page to stop loading.',
   'A success toast "Estimate created successfully" appears. The browser navigates to the detail page for the new estimate. The title "Warehouse HVAC Replacement R1", status "Pending Review", and revision "R2" are visible in the page header.',
   'HIGH', 'scenario', '/67/estimates/new'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '1.2', 'Create', 'Required field validation',
   'Submitting the create form without a Title shows a validation error',
   'Title is the only required field; confirms the form blocks submission and shows an inline error.',
   null,
   E'1. Click "New Estimate" on the Estimates list page.\n2. Leave the Title field blank.\n3. Click "Create Estimate".',
   'The form does not submit. An inline error message appears beneath the Title field. No navigation occurs and no toast is shown.',
   'HIGH', 'scenario', '/67/estimates/new'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '1.3', 'Create', 'Minimal create',
   'Create an estimate with only the required Title field',
   'Confirms an estimate can be saved with only Title filled; all optional fields use defaults.',
   null,
   E'1. Click "New Estimate" on the Estimates list page.\n2. Type "Minimal Estimate Test" in the Title field.\n3. Click "Create Estimate".\n4. Wait for navigation.',
   'A success toast appears. The detail page loads with title "Minimal Estimate Test", status "Draft", revision "R1", insurance rate "1.25%", and fee rate "10%".',
   'HIGH', 'scenario', '/67/estimates/new'),

  -- EDIT
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '2.1', 'Edit', 'Edit estimate settings (inline)',
   'Changing Duration, Contingency, Insurance Rate, or Fee Rate on the detail page auto-saves',
   'Estimate settings on the detail page save via a debounced PUT; confirms the save indicator appears and persists.',
   E'- An estimate detail page is open.',
   E'1. In the "Estimate Settings" sidebar, change "Duration (weeks)" to **20**.\n2. Wait for the "saving…" indicator to appear and disappear.\n3. Refresh the page.',
   'After refresh the Duration shows **20** weeks. The Grand Total in the summary sidebar has recalculated to reflect the new duration.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '2.2', 'Edit', 'Edit estimate via row menu',
   'Clicking Edit from the row actions menu navigates to an edit form',
   'Confirms the Edit action in the ⋯ menu works and the form is pre-populated with existing values.',
   E'- At least one estimate exists on the list page.',
   E'1. On the Estimates list page, click the "⋯" menu on any estimate row.\n2. Click "Edit".\n3. Observe the form fields.',
   'The edit form opens pre-filled with the estimate''s existing Title, Status, Estimator, and other fields. All dropdowns show the saved values rather than placeholders.',
   'HIGH', 'scenario', '/67/estimates'),

  -- DELETE
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '3.1', 'Delete', 'Delete confirmation dialog',
   'Clicking Delete shows a confirmation dialog before removing the estimate',
   'Confirms the destructive action requires explicit confirmation and the dialog copy is correct.',
   E'- At least one estimate exists on the list page.',
   E'1. On the Estimates list page, click the "⋯" menu on any estimate row.\n2. Click "Delete".',
   'A dialog appears with title "Delete Estimate", the estimate''s name in the body text, and "Cancel" and "Delete" buttons.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '3.2', 'Delete', 'Confirm delete removes row',
   'Confirming deletion removes the estimate from the list',
   'Confirms soft-delete actually hides the row from the list view.',
   E'- At least one estimate exists that is safe to delete.',
   E'1. Open the delete confirmation dialog for an estimate (see 3.1).\n2. Click "Delete" in the dialog.\n3. Wait for the page to refresh.',
   'A success toast "Estimate deleted" appears. The deleted estimate no longer appears in the list. Refreshing the page confirms it is still absent.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '3.3', 'Delete', 'Cancel delete leaves row intact',
   'Cancelling the delete dialog leaves the estimate unchanged',
   'Confirms the cancel path does not perform any deletion.',
   E'- The delete confirmation dialog is open.',
   E'1. Open the delete confirmation dialog for an estimate.\n2. Click "Cancel".',
   'The dialog closes. The estimate row is still present in the list. No toast is shown.',
   'MEDIUM', 'scenario', '/67/estimates'),

  -- STATUS
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '4.1', 'Status', 'Status transitions via edit form',
   'An estimate can move through all four statuses: Draft → Pending Review → Approved → Rejected',
   'Covers the full status lifecycle in one flow using the edit form.',
   E'- An estimate in Draft status exists.',
   E'1. Open the edit form for a Draft estimate.\n2. Change Status to "Pending Review" and save.\n3. Re-open edit; change to "Approved" and save.\n4. Re-open edit; change to "Rejected" and save.\n5. On the list page, observe the status badge.',
   'Each save succeeds. The status badge on the list page updates to the correct label and dot color after each transition: amber (Pending Review), green (Approved), red (Rejected).',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '4.2', 'Status', 'Status badge colors',
   'Status badges show correct colors for each value',
   'Confirms the dot-color indicator matches the status: gray=Draft, amber=Pending Review, green=Approved, red=Rejected.',
   E'- Estimates with each of the four statuses exist (or create them).',
   E'1. On the Estimates list page, locate one row for each status.\n2. Observe the colored dot next to the status label for each.',
   'Draft has a gray dot. Pending Review has an amber dot. Approved has a green dot. Rejected has a red dot.',
   'MEDIUM', 'scenario', '/67/estimates'),

  -- LINE ITEMS — GC
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '5.1', 'LineItems', 'GC tab inline edit saves correctly',
   'Editing Qty or Rate on a General Conditions row updates the row total and the summary sidebar',
   'Inline edits on the GC tab trigger a PUT to the line-items API; the total recomputes client-side immediately.',
   E'- On an estimate detail page with GC line items loaded.',
   E'1. Click the "General Conditions" tab.\n2. Click into the Qty cell for the first row and change the value to **10**.\n3. Press Enter or click away.\n4. Observe the "Total" column for that row and the Grand Total in the sidebar.',
   'The row Total updates immediately to Qty × Rate. The Division Summary and Grand Total in the left sidebar recalculate to reflect the change. After page refresh the value is still **10**.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '5.2', 'LineItems', 'GC tab Rate edit recalculates total',
   'Editing the Rate field on a GC row recalculates the line total',
   'Confirms the Rate field triggers the same recalculation as Qty.',
   E'- On the General Conditions tab of an estimate detail page.',
   E'1. Click into the Rate cell for any row and change the value to **500**.\n2. Press Enter.\n3. Observe the row Total and the Grand Total.',
   'The row Total is Qty × 500. The Grand Total in the summary sidebar updates accordingly.',
   'HIGH', 'scenario', '/67/estimates'),

  -- LINE ITEMS — QTO
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '6.1', 'LineItems', 'QTO add row',
   'Clicking "Add item" in a QTO division adds a new editable row',
   'Tests the POST /line-items endpoint triggered by the "+ Add item" button.',
   E'- On the Quantity Takeoff tab of an estimate detail page.\n- A division accordion is expanded.',
   E'1. Click the "Quantity Takeoff" tab.\n2. Expand the "03 — Concrete" division (or any division).\n3. Click "+ Add item" at the bottom of that division.\n4. In the new row, type "Test Footing" in the Description field.\n5. Set Qty to **100** and Unit to **CY**.\n6. Set Mat $/unit to **150**.\n7. Press Enter.',
   'A new row appears in the division with a blank description. After editing and pressing Enter, the row persists. The division total and Grand Total update to include the new item''s cost.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '6.2', 'LineItems', 'QTO delete row',
   'Clicking the trash icon on a QTO row removes it from the estimate',
   'Tests DELETE /line-items/:id and confirms the division total recalculates.',
   E'- A QTO row exists in an expanded division.',
   E'1. On the Quantity Takeoff tab, hover over an existing QTO row.\n2. Click the trash icon (Trash2) that appears on hover.\n3. Observe the division and the Grand Total.',
   'The row disappears immediately. The division total decreases by the deleted row''s cost. The Grand Total reflects the removal. After page refresh the row is still gone.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '6.3', 'LineItems', 'QTO expand/collapse all',
   '"Expand All" and "Collapse All" buttons toggle all division accordions',
   'Confirms the expand/collapse UI controls work for all divisions at once.',
   E'- On the Quantity Takeoff tab.',
   E'1. Click "Collapse All".\n2. Observe divisions.\n3. Click "Expand All".\n4. Observe divisions.',
   'After "Collapse All" all division accordions are closed (no rows visible). After "Expand All" all divisions are open and their rows are visible.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '6.4', 'LineItems', 'QTO inline description edit persists',
   'Editing a line item description and tabbing away saves the change',
   'Confirms PUT /line-items/:id is called on blur and the value persists after refresh.',
   E'- A QTO row exists in an expanded division.',
   E'1. Click the Description cell of a QTO row and change the text to "Updated Scope Item".\n2. Press Enter or click outside the cell.\n3. Wait 1 second for the auto-save.\n4. Refresh the page.',
   'The description shows "Updated Scope Item" after refresh.',
   'HIGH', 'scenario', '/67/estimates'),

  -- CALCULATIONS
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '7.1', 'Calculations', 'Grand total formula',
   'Grand Total = Subtotal + Contingency + (Subtotal × Insurance Rate) + (Subtotal × Fee Rate)',
   'Validates the summary sidebar calculation against the known formula.',
   E'- An estimate with at least one line item and non-zero cost exists.',
   E'1. Note the Subtotal, Contingency, Insurance rate %, and Fee rate % values in the sidebar.\n2. Manually compute: Insurance = Subtotal × rate; Fee = Subtotal × rate; Grand Total = Subtotal + Contingency + Insurance + Fee.\n3. Compare with the displayed Grand Total.',
   'The displayed Grand Total matches the manual calculation (within $1 rounding). Changing Contingency by $1000 causes Grand Total to increase by exactly $1000.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '7.2', 'Calculations', 'Division summary reflects line item totals',
   'Division Summary in the sidebar shows per-division totals matching the QTO tab',
   'Cross-checks that the sidebar division totals equal the sum of line items within each division on the QTO tab.',
   E'- An estimate with QTO line items in at least two divisions exists.',
   E'1. On the detail page, observe the Division Summary in the sidebar.\n2. Switch to the Quantity Takeoff tab and expand a division.\n3. Sum the "Total" column values manually for that division.\n4. Compare with the sidebar value.',
   'The sidebar division total matches the sum of all QTO rows for that division. If a row is edited, the sidebar updates immediately.',
   'HIGH', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '7.3', 'Calculations', 'Insurance and Fee rate display',
   'Insurance and Fee row labels show the actual rate percentage',
   'Confirms the sidebar labels read "Insurance (1.25%)" and "Fee (10.0%)" based on the current settings, not hard-coded text.',
   E'- An estimate detail page with default insurance (0.0125) and fee (0.10) rates.',
   E'1. Observe the Insurance and Fee rows in the summary sidebar.',
   'The Insurance label reads "Insurance (1.25%)" and the Fee label reads "Fee (10.0%)". Changing the insurance rate to 0.02 updates the label to "Insurance (2.00%)".',
   'MEDIUM', 'scenario', '/67/estimates'),

  -- FILTERS / SEARCH / SORT
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '8.1', 'Filters', 'Search by estimator name',
   'Typing an estimator name in the search box filters to matching rows',
   'Confirms the search includes the estimator field.',
   E'- At least one estimate with a named estimator exists.',
   E'1. On the Estimates list, type the estimator''s name (or part of it) in the search box.',
   'Only rows whose estimator field matches the search term are shown.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '8.2', 'Filters', 'Filter by Approved status',
   'Selecting "Approved" from the Status filter shows only approved estimates',
   'Tests a specific non-default filter value.',
   E'- At least one approved estimate exists.',
   E'1. Open the Status filter dropdown.\n2. Select "Approved".\n3. Wait for the list to update.',
   'Only estimates with status "Approved" are shown. The toolbar count updates. Clearing the filter (select "All Statuses") restores all rows.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '8.3', 'Filters', 'Column sort by Title',
   'Clicking the Title column header sorts estimates alphabetically',
   'Confirms the client-side sort is applied when clicking a column header.',
   E'- More than one estimate exists.',
   E'1. Click the "Title" column header.\n2. Observe the row order.\n3. Click again to reverse sort.',
   'First click sorts ascending (A→Z). Second click sorts descending (Z→A). The rows reorder accordingly.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '8.4', 'Filters', 'Column visibility toggle',
   'Toggling the Location column on/off via the column visibility menu works',
   'Confirms the optional Location column can be shown and hidden.',
   E'- On the Estimates list page.',
   E'1. Open the column visibility menu (gear/columns icon in the toolbar).\n2. Enable the "Location" column.\n3. Observe the table.',
   'The Location column appears in the table. Toggling it off removes it. The setting persists if the URL encodes it.',
   'LOW', 'scenario', '/67/estimates'),

  -- BULK ACTIONS
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '9.1', 'BulkActions', 'Select all rows',
   'Checking the header checkbox selects all visible rows',
   'Confirms the select-all behaviour and the selection count in the toolbar updates.',
   E'- At least two estimates exist on the list.',
   E'1. Click the checkbox in the table header row.\n2. Observe the toolbar.',
   'All visible rows are checked. The toolbar shows the correct selected count (e.g., "3 selected").',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '9.2', 'BulkActions', 'Deselect individual row',
   'Unchecking one row reduces the selected count',
   'Confirms individual row deselection while others remain selected.',
   E'- Multiple rows are selected (see 9.1).',
   E'1. After selecting all rows, uncheck one row''s checkbox.\n2. Observe the toolbar.',
   'The selected count decreases by 1. The deselected row''s checkbox is empty. Other rows remain checked.',
   'MEDIUM', 'scenario', '/67/estimates'),

  -- VIEWS
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '10.1', 'Views', 'List view shows card-style rows',
   'Switching to List view renders estimates as card-style list items with title, estimator, revision, date, and status badge',
   'Confirms the list view variant renders without errors and shows the correct fields.',
   E'- At least one estimate exists.',
   E'1. On the Estimates list page, click the List view icon in the toolbar.\n2. Observe the rendered rows.',
   'Rows are displayed as list items with title (bold), estimator, revision (e.g., "R1"), date, and a status badge. The table header row is no longer visible.',
   'MEDIUM', 'scenario', '/67/estimates'),

  -- PAGINATION
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '11.1', 'Pagination', 'Per-page selector changes row count',
   'Changing the rows-per-page selector updates how many rows are shown',
   'Confirms the pagination control works.',
   E'- More than 10 estimates exist, or reduce perPage to a small value.',
   E'1. On the Estimates list page, locate the per-page dropdown.\n2. Change from 25 to 10.\n3. Observe the number of rows.',
   'At most 10 rows are shown. The pagination controls show the correct total pages.',
   'LOW', 'scenario', '/67/estimates'),

  -- EDGE CASES
  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '12.1', 'Edge', 'Back button from detail returns to list',
   'Clicking the "Back" button on the detail page navigates back to the Estimates list',
   'Confirms the back navigation in the detail page header works.',
   E'- On an estimate detail page.',
   E'1. Click the "← Back" button in the detail page header.',
   'The browser navigates to /67/estimates. The estimates list is shown.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '12.2', 'Edge', 'Invalid estimate ID shows not-found message',
   'Navigating directly to a non-existent estimate ID shows "Estimate not found"',
   'Confirms the error state renders when the estimate does not exist.',
   null,
   E'1. Navigate directly to /67/estimates/99999999 in the browser.',
   'The page renders with "Estimate not found." or equivalent error text. No blank screen or unhandled exception is shown.',
   'MEDIUM', 'scenario', '/67/estimates/99999999'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '12.3', 'Edge', 'Estimate settings saving indicator',
   'The "saving…" label appears while a settings PUT is in flight',
   'Confirms the isSavingSettings spinner is visible during the debounced auto-save.',
   E'- On an estimate detail page.',
   E'1. Change a setting field (e.g., Fee Rate) in the sidebar.\n2. Immediately observe the "Estimate Settings" header area.',
   'The text "saving…" (dimmed) appears next to "Estimate Settings" while the PUT is in flight, and disappears once the save completes.',
   'LOW', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '12.4', 'Edge', 'Estimate with zero line items shows empty Division Summary',
   'A brand-new estimate with no line items shows "No costs yet" in the Division Summary',
   'Confirms the EmptyState component renders when there are no division totals.',
   E'- A newly created estimate with no line items is open.',
   E'1. Create a new estimate (title only).\n2. Navigate to its detail page.\n3. Observe the Division Summary in the left sidebar.',
   'The Division Summary area shows "No costs yet" with the description "Edit the General Conditions or Quantity Takeoff rows to build this estimate." Grand Total shows $0.',
   'MEDIUM', 'scenario', '/67/estimates'),

  ('3988da5c-ab91-4942-a4bf-3d43963d8cb6', '12.5', 'Edge', 'Alternates & Allowances tab shows placeholder text when empty',
   'An estimate with no alternates or allowances shows placeholder text in the Alternates & Allowances tab',
   'Confirms the two empty-state fallbacks in the Alternates & Allowances tab render correctly.',
   E'- An estimate with no alternates and no allowances is open.',
   E'1. Navigate to the Alternates & Allowances tab.\n2. Observe the Alternates section and the Allowances section.',
   'The Alternates section shows "No alternates defined." and the Allowances section shows "No allowances defined." No table is rendered.',
   'LOW', 'scenario', '/67/estimates');

-- 4. Update total_cases
update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '3988da5c-ab91-4942-a4bf-3d43963d8cb6')
 where id = '3988da5c-ab91-4942-a4bf-3d43963d8cb6';
