-- Seed: change-orders FEATURE test suite
-- Generated by /test-scenario-audit change-orders on 2026-04-20
-- Suite type: feature | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('change-orders', 'feature', 'Change Orders — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;
-- NOTE: Replace <feature_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<feature_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<feature_suite_id>', '1.1', 'Create', 'Prime', 'Create prime contract change order (happy path)', 'Creates a prime CO with required and common optional fields.', null, E'1. Open /67/change-orders\n2. Click New Change Order\n3. Fill PCCO Number, Title, Status, Amount\n4. Click Create', 'Prime CO is created and detail page opens with saved values.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '1.2', 'Create', 'Prime validation', 'Prime create blocks when PCCO Number or Title is missing', 'Consolidated required-field validation coverage.', null, E'1. Open prime create form\n2. Leave PCCO Number and Title empty\n3. Click Create', 'Inline validation appears and no record is created.', 'HIGH', 'scenario', '/67/change-orders/prime/new'),
  ('<feature_suite_id>', '1.3', 'Create', 'Commitment', 'Create commitment change order (happy path)', 'Creates a commitment CO with commitment selection and amount.', E'- At least one commitment exists in project 67.', E'1. Open /67/change-orders?tab=commitment\n2. Click New Change Order\n3. Select Commitment, fill Number/Title/Amount\n4. Click Create', 'Commitment CO is created and detail page opens.', 'HIGH', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '2.1', 'Edit', 'Prime', 'Edit prime CO fields and persist after refresh', 'Updates title/status/amount and verifies persistence.', E'- Existing prime CO available.', E'1. Open prime CO detail\n2. Click Edit\n3. Change title, status, amount\n4. Save\n5. Refresh page', 'Updated values remain after refresh.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '2.2', 'Edit', 'Commitment', 'Edit commitment CO fields and persist after refresh', 'Updates description/status/amount and verifies persistence.', E'- Existing commitment CO available.', E'1. Open commitment CO detail\n2. Edit fields\n3. Save\n4. Refresh', 'Updated values remain after refresh.', 'HIGH', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '3.1', 'Delete', 'Prime', 'Delete prime CO from list row actions', 'Confirms delete flow and list removal.', E'- Deletable prime CO exists.', E'1. Open prime tab\n2. Row menu -> Delete\n3. Confirm', 'Deleted row no longer appears; success toast shown.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '3.2', 'Delete', 'Commitment', 'Delete commitment CO from list row actions', 'Confirms delete flow and list removal on commitment tab.', E'- Deletable commitment CO exists.', E'1. Open commitment tab\n2. Row menu -> Delete\n3. Confirm', 'Deleted row no longer appears; success toast shown.', 'HIGH', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '4.1', 'Status', 'Prime approve', 'Approve prime CO', 'Covers prime approval transition.', E'- Prime CO in proposed/pending state exists.', E'1. Open prime detail\n2. Trigger Approve action\n3. Confirm', 'Status changes to Approved and persists.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '4.2', 'Status', 'Prime reject', 'Reject prime CO', 'Covers prime reject transition.', E'- Prime CO in proposed/pending state exists.', E'1. Open prime detail\n2. Trigger Reject action\n3. Confirm', 'Status changes to Rejected and persists.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '4.3', 'Status', 'Commitment approve', 'Approve commitment CO', 'Covers commitment approval transition.', E'- Commitment CO in pending state exists.', E'1. Open commitment detail\n2. Trigger Approve action\n3. Confirm', 'Status changes to Approved and persists.', 'HIGH', 'scenario', '/67/change-orders?tab=commitment'),
  ('<feature_suite_id>', '4.4', 'Status', 'Commitment reject', 'Reject commitment CO', 'Covers commitment reject transition.', E'- Commitment CO in pending state exists.', E'1. Open commitment detail\n2. Trigger Reject action\n3. Confirm', 'Status changes to Rejected and persists.', 'HIGH', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '5.1', 'Line Items', 'Prime', 'Add prime line item and verify total updates', 'Validates line-item create and header total recalculation.', E'- Prime CO detail page available.', E'1. Open prime detail -> Line Items\n2. Click Add Line Item\n3. Enter quantity/unit cost and save', 'New line item appears and prime total reflects added amount.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '5.2', 'Line Items', 'Prime', 'Edit and delete prime line item', 'Consolidated edit/delete line item coverage.', E'- Prime CO has at least one line item.', E'1. Edit line item amount\n2. Save\n3. Delete same line item\n4. Confirm', 'Amount updates after edit; item disappears after delete; total recalculates each time.', 'HIGH', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '5.3', 'Line Items', 'Commitment', 'Add commitment line item and verify total updates', 'Validates commitment line-item create path.', E'- Commitment CO detail page available.', E'1. Open commitment detail -> Line Items\n2. Add line item with amount\n3. Save', 'Line item persists and commitment total updates.', 'HIGH', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '6.1', 'Attachments', 'Prime', 'Upload and delete attachment on prime CO', 'Covers file attach lifecycle.', E'- Have a small local test file available.', E'1. Open prime detail -> Attachments\n2. Upload file\n3. Verify row\n4. Delete file', 'Attachment appears after upload, then is removed after delete.', 'MEDIUM', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '6.2', 'Attachments', 'Commitment', 'Upload and delete attachment on commitment CO', 'Covers file attach lifecycle for commitment CO.', E'- Have a small local test file available.', E'1. Open commitment detail -> Attachments\n2. Upload file\n3. Verify row\n4. Delete file', 'Attachment appears after upload, then is removed after delete.', 'MEDIUM', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '7.1', 'Filters', 'Prime status', 'Prime status filter returns only matching rows', 'Validates status filtering behavior on prime tab.', null, E'1. Open prime tab\n2. Apply Status filter=Approved', 'All visible rows are Approved.', 'MEDIUM', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '7.2', 'Filters', 'Commitment status', 'Commitment status filter returns only matching rows', 'Validates status filtering behavior on commitment tab.', null, E'1. Open commitment tab\n2. Apply Status filter=Pending', 'All visible rows are Pending.', 'MEDIUM', 'scenario', '/67/change-orders?tab=commitment'),
  ('<feature_suite_id>', '7.3', 'Search', 'Prime', 'Prime search matches number or title', 'Validates free-text search fields on prime tab.', null, E'1. Open prime tab\n2. Search by known PCCO number fragment', 'Result rows match the search term.', 'MEDIUM', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '7.4', 'Search', 'Commitment', 'Commitment search matches number or description', 'Validates free-text search fields on commitment tab.', null, E'1. Open commitment tab\n2. Search by known CO number fragment', 'Result rows match the search term.', 'MEDIUM', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '8.1', 'Export', 'Prime', 'Export prime COs to CSV', 'Covers export endpoint from UI action.', null, E'1. Open prime tab\n2. Click Export CSV', 'Download starts and CSV contains expected header columns.', 'MEDIUM', 'scenario', '/67/change-orders'),
  ('<feature_suite_id>', '8.2', 'Export', 'Commitment', 'Export commitment COs to CSV', 'Covers export endpoint from UI action.', null, E'1. Open commitment tab\n2. Click Export CSV', 'Download starts and CSV contains expected header columns.', 'MEDIUM', 'scenario', '/67/change-orders?tab=commitment'),

  ('<feature_suite_id>', '9.1', 'Permissions', 'Read-only', 'Read-only user cannot mutate change orders', 'Permission gate for create/edit/delete/approve actions.', E'- A read-only project user exists.', E'1. Log in as read-only user\n2. Open /67/change-orders\n3. Inspect create button and row actions', 'Create/edit/delete/approve/reject actions are hidden or blocked; list remains readable.', 'MEDIUM', 'scenario', '/67/change-orders');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<feature_suite_id>')
 where id = '<feature_suite_id>';
*/;
