-- Feature test suite seed for prime-contracts
-- Generated by /test-scenario-audit on 2026-05-14
-- Suite type: feature  |  Target: 31 cases
-- Live suite_id = 'a535e0b8-bb7c-4be0-a690-694f269d4d9f'

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('prime-contracts', 'feature', 'Prime Contracts — Feature', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

delete from public.test_cases where suite_id = 'a535e0b8-bb7c-4be0-a690-694f269d4d9f';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values

-- CREATE
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '1.1', 'Create', 'Happy path',
   'Create a prime contract with all fields filled',
   'Confirms full creation flow: required fields, optional financial fields, status defaults to Draft.',
   'Logged in as test1@mail.com on project 67.',
   E'1. Navigate to /67/prime-contracts\n2. Click "Create".\n3. Fill "Contract #" with **PC-TEST-001**.\n4. Fill "Title" with **Test Prime Contract - Full**.\n5. Set "Original Contract Value" to **500000**.\n6. Set "Start Date" to **2026-06-01**.\n7. Set "End Date" to **2027-05-31**.\n8. Set "Retention %" to **10**.\n9. Click "Save".',
   'Browser redirects to the new contract detail page. Status badge shows "Draft". Original Contract Value shows $500,000.00. No error toast.',
   'HIGH', 'scenario', '/67/prime-contracts/new'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '1.2', 'Create', 'Required field validation',
   'Submitting the create form without required fields shows validation errors',
   'Confirms Contract # and Title are enforced as required.',
   'Create form open at /67/prime-contracts/new.',
   E'1. Navigate to /67/prime-contracts/new\n2. Leave "Contract #" blank.\n3. Leave "Title" blank.\n4. Click "Save".',
   'Form does not submit. Inline validation errors appear on "Contract #" and "Title" fields. No navigation away from the form.',
   'HIGH', 'scenario', '/67/prime-contracts/new'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '1.3', 'Create', 'Duplicate contract number',
   'Creating a contract with an already-used contract number shows an error',
   'API enforces unique contract_number per project; confirms the error surfaces in the UI.',
   'A contract with number PC-TEST-001 already exists in project 67.',
   E'1. Navigate to /67/prime-contracts/new\n2. Fill "Contract #" with **PC-TEST-001**.\n3. Fill "Title" with **Duplicate Test**.\n4. Click "Save".',
   'Form shows an error message "Contract number already exists for this project". No new contract is created.',
   'HIGH', 'scenario', '/67/prime-contracts/new'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '1.4', 'Create', 'Negative contract value rejected',
   'Entering a negative original contract value is blocked',
   'Validation schema enforces min(0) on original_contract_value.',
   'Create form open.',
   E'1. Navigate to /67/prime-contracts/new\n2. Fill "Contract #" with **PC-VAL-001**.\n3. Fill "Title" with **Validation Test**.\n4. Enter **-1000** in "Original Contract Value".\n5. Click "Save".',
   'Form shows a validation error on the Original Contract Value field. No contract is created.',
   'MEDIUM', 'scenario', '/67/prime-contracts/new'),

-- READ
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '2.1', 'Read', 'Detail overview',
   'All General tab fields display the correct saved values',
   'Verifies data persistence: fields saved on creation show correctly in read mode.',
   'Contract PC-TEST-001 exists with title, value, dates, and retention set.',
   E'1. Navigate to /67/prime-contracts\n2. Click the row for contract PC-TEST-001.',
   'General tab shows: contract number PC-TEST-001, title "Test Prime Contract - Full", status "Draft", Original Contract Amount $500,000.00, Start Date 2026-06-01, End Date 2027-05-31, Retention 10%.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '2.2', 'Read', 'Financial calculations',
   'Revised Contract Value = Original Value + Approved Change Orders',
   'Confirms the financial summary view computes the revised value correctly.',
   'A contract with $500,000 original value and at least one approved change order exists.',
   E'1. Open the detail page for a contract with known original value and approved COs.\n2. Note the Revised Contract Amount shown in the header or General tab.',
   'Revised Contract Amount = Original Contract Amount + sum of all Approved Change Order amounts. Value matches arithmetic.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '2.3', 'Read', 'Private contract visibility',
   'A private contract is hidden from users not in the allowed_user_ids list',
   'Confirms the privacy gate in GET /contracts filters out unauthorized users.',
   'A contract marked is_private=true exists. Test user is NOT in allowed_user_ids.',
   E'1. Log in as a non-admin user who is not in the allowed list.\n2. Navigate to /67/prime-contracts.\n3. Check if the private contract appears in the list.',
   'The private contract does NOT appear in the list. The contract detail URL returns 404 if navigated to directly.',
   'HIGH', 'scenario', '/67/prime-contracts'),

-- EDIT
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '3.1', 'Edit', 'Happy path',
   'Edit all editable fields on a contract and save',
   'Confirms the PUT endpoint and edit form round-trip correctly.',
   'Contract PC-TEST-001 exists.',
   E'1. Open contract PC-TEST-001 detail page.\n2. Click the edit action (three-dot menu → Edit, or ?edit=1 URL param).\n3. Change "Title" to **Updated Contract Title**.\n4. Change "Original Contract Value" to **600000**.\n5. Change "Payment Terms" to **Net 30**.\n6. Click "Save".',
   'Page exits edit mode. Title now shows "Updated Contract Title". Original Contract Amount shows $600,000.00. Payment Terms shows "Net 30". After page refresh, all changes persist.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '3.2', 'Edit', 'Duplicate number on edit blocked',
   'Changing a contract number to one already in use is rejected',
   'Confirms uniqueness check runs on PUT as well as POST.',
   'Contracts PC-TEST-001 and PC-TEST-002 both exist.',
   E'1. Open contract PC-TEST-001 detail page and enter edit mode.\n2. Change "Contract #" to **PC-TEST-002**.\n3. Click "Save".',
   'Error message "Contract number already exists for this project" is shown. The contract number is NOT updated.',
   'HIGH', 'scenario', '/67/prime-contracts'),

-- DELETE
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '4.1', 'Delete', 'Delete with no children',
   'Deleting a contract with no line items or change orders succeeds',
   'Confirms the happy-path delete flow and optimistic UI update.',
   'An empty contract (no SOV line items, no change orders) exists.',
   E'1. Navigate to /67/prime-contracts\n2. Click the three-dot row action on an empty contract.\n3. Click "Delete".\n4. Click "Delete Contract" in the confirmation dialog.',
   'Contract is removed from the list. Success toast "Contract deleted successfully" appears. The contract no longer appears after page refresh.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '4.2', 'Delete', 'Delete blocked by child records',
   'Deleting a contract with SOV line items returns a 409 error',
   'Confirms the guard that prevents data loss: DELETE is blocked when line items or COs exist.',
   'A contract with at least one SOV line item exists.',
   E'1. Navigate to /67/prime-contracts\n2. Click the three-dot row action on a contract that has SOV line items.\n3. Click "Delete".\n4. Click "Delete Contract" in the confirmation dialog.',
   'Error toast shown: "Cannot delete contract with existing line items or change orders. Remove them first." Contract remains in the list.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '4.3', 'Delete', 'Bulk delete',
   'Selecting multiple contracts and bulk-deleting removes all eligible ones',
   'Confirms select-all + bulk delete flow.',
   'At least two empty contracts exist (no line items or COs).',
   E'1. Navigate to /67/prime-contracts\n2. Check the select-all checkbox.\n3. Click "Delete" in the bulk actions toolbar.\n4. Confirm the bulk delete dialog.',
   'All selected eligible contracts are removed. Toast shows count of deleted contracts. Any contracts with child records show a partial-failure message.',
   'HIGH', 'scenario', '/67/prime-contracts'),

-- STATUS
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '5.1', 'Status', 'Status transitions',
   'A contract status can be changed through all valid states',
   'Covers the full status workflow: Draft → Out for Signature → Approved → Complete.',
   'Contract PC-TEST-001 is in Draft status.',
   E'1. Open contract PC-TEST-001 in edit mode.\n2. Change "Status" to **Out for Signature** and save.\n3. Re-open edit mode, change "Status" to **Approved** and save.\n4. Re-open edit mode, change "Status" to **Complete** and save.',
   'After each save, the status badge on the detail page updates to the new value. List page also reflects the updated status. No error at any step.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '5.2', 'Status', 'Terminated status',
   'A contract can be set to Terminated and a termination date recorded',
   'Confirms the Terminated status and contract_termination_date field work end-to-end.',
   'A contract in Approved status exists.',
   E'1. Open the contract in edit mode.\n2. Set "Status" to **Terminated**.\n3. Set "Contract Termination Date" to **2026-12-31**.\n4. Click "Save".',
   'Status badge shows "Terminated". Contract Termination Date shows 2026-12-31. After refresh, values persist.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '5.3', 'Status', 'Executed checkbox',
   'Marking a contract as Executed sets the executed flag and timestamp',
   'Confirms the executed boolean and executed_at datetime are saved correctly.',
   'A contract in Approved status exists.',
   E'1. Open the contract in edit mode.\n2. Check the "Executed" checkbox.\n3. Click "Save".',
   'The Executed column in the list shows "Yes" for this contract. The contract detail shows the executed date. After refresh, the value persists.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

-- SOV
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '6.1', 'SOV', 'Add SOV line item',
   'Adding a line item to the Schedule of Values updates the SOV total',
   'Confirms SOV line item creation and that the revised contract value reflects it.',
   'A prime contract exists with no SOV items.',
   E'1. Open the contract detail page.\n2. Click the "SOV" tab.\n3. Click "Add Line Item".\n4. Fill "Description" with **Foundation Work**.\n5. Fill "Quantity" with **1**.\n6. Fill "Unit Cost" with **100000**.\n7. Click "Save".',
   'New line item appears in the SOV table with description "Foundation Work" and total $100,000.00. The SOV total updates accordingly. No error.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '6.2', 'SOV', 'Delete SOV line item',
   'Deleting an SOV line item removes it and recalculates the SOV total',
   'Confirms SOV line item deletion and total recalculation.',
   'A contract with at least one SOV line item exists.',
   E'1. Open the contract detail page SOV tab.\n2. Click the delete action on a line item.\n3. Confirm deletion.',
   'Line item is removed from the SOV table. SOV total decreases by the deleted item amount. The contract can now be deleted (if it was the only line item).',
   'HIGH', 'scenario', '/67/prime-contracts'),

-- CHANGE ORDERS
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '7.1', 'Change Orders', 'Linked PCCOs show in expanded row',
   'Expanding a contract row on the list page shows linked Prime Contract Change Orders',
   'Confirms the expandable sub-row fetches and displays PCCOs for the correct contract.',
   'A prime contract with at least one PCCO in Approved status exists.',
   E'1. Navigate to /67/prime-contracts\n2. Click the ">" expand icon on the contract with linked PCCOs.\n3. Wait for loading.',
   'The expanded row shows a "Change Orders" sub-section with the PCCO number, title, status badge, and amount. No JS error.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '7.2', 'Change Orders', 'Change Orders tab',
   'The Change Orders tab on the detail page lists all linked change orders',
   'Confirms tab content loads and the CO table renders.',
   'A prime contract with change orders exists.',
   E'1. Open the contract detail page.\n2. Click the "Change Orders" tab.',
   'The Change Orders tab shows a table or list with CO number, title, status, and amount columns. Badge count on the tab matches the number of COs displayed.',
   'HIGH', 'scenario', '/67/prime-contracts'),

-- FILTERS & SEARCH
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '8.1', 'Filters', 'Filter by Owner/Client',
   'Filtering by Owner/Client shows only contracts for that company',
   'Confirms the dynamic client_name filter works end-to-end.',
   'At least two contracts with different Owner/Client values exist.',
   E'1. Navigate to /67/prime-contracts\n2. Click "Filters".\n3. Select a specific company from the "Owner/Client" dropdown.\n4. Apply.',
   'Table shows only contracts matching the selected Owner/Client. The filter chip is visible in the toolbar. Clearing the filter restores all contracts.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '8.2', 'Filters', 'Filter by Executed',
   'Filtering by Executed=Yes shows only executed contracts',
   'Confirms the executed boolean filter works.',
   'At least one contract is marked Executed.',
   E'1. Navigate to /67/prime-contracts\n2. Click "Filters".\n3. Set "Executed" to **Yes**.',
   'Only contracts with Executed=true appear. If none, the empty state is shown.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '8.3', 'Filters', 'Sort by Original Contract Amount',
   'Clicking the Original Contract Amount column header sorts contracts ascending/descending',
   'Confirms column sorting works on financial columns.',
   'At least two contracts with different original values exist.',
   E'1. Navigate to /67/prime-contracts\n2. Click the "Original Contract Amount" column header.\n3. Note the sort order.\n4. Click it again.',
   'First click: rows sorted ascending by Original Contract Amount. Second click: rows sorted descending. Arrow icon toggles direction.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

-- EXPORT
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '9.1', 'Export', 'CSV export',
   'Clicking the export icon downloads a CSV of visible contracts',
   'Confirms the CSV export feature includes only visible columns and filtered rows.',
   'At least one prime contract exists.',
   E'1. Navigate to /67/prime-contracts\n2. Click the export icon in the toolbar.\n3. Check the downloaded file.',
   'A CSV file named prime-contracts-{page}.csv is downloaded. It contains a header row with the visible column names, and one data row per visible contract. No error toast.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

-- COLUMN VISIBILITY
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '10.1', 'Filters', 'Column visibility toggle',
   'Toggling a column off hides it from the table',
   'Confirms the column visibility picker works.',
   'Prime Contracts list page loaded with at least one contract.',
   E'1. Navigate to /67/prime-contracts\n2. Click the column visibility button in the toolbar.\n3. Uncheck "Invoiced".\n4. Close the picker.',
   'The "Invoiced" column disappears from the table. Other columns remain. Re-checking it restores it.',
   'LOW', 'scenario', '/67/prime-contracts'),

-- CONFIGURE
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '11.1', 'Navigation', 'Configure page opens',
   'Clicking the Settings gear icon opens the Configure page',
   'Confirms the configure route is reachable.',
   'Logged in as test1@mail.com.',
   E'1. Navigate to /67/prime-contracts\n2. Click the gear (Settings) icon next to the "Create" button.',
   'Browser navigates to /67/prime-contracts/configure and the page renders without error.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

-- INVOICES TAB
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '12.1', 'Invoices', 'Invoices tab loads',
   'The Invoices tab on contract detail shows payment applications',
   'Confirms the invoices/payment-applications sub-route renders.',
   'A prime contract exists (any status).',
   E'1. Open a prime contract detail page.\n2. Click the "Invoices" tab.',
   'Invoices tab renders with either a list of payment applications or an empty state. No error toast.',
   'HIGH', 'scenario', '/67/prime-contracts'),

-- FINANCIAL MARKUP
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '13.1', 'Financial Markup', 'Financial markup tab loads',
   'The Financial Markup tab renders vertical markup rows',
   'Confirms the financial markup sub-route renders without crash.',
   'A prime contract exists.',
   E'1. Open a prime contract detail page.\n2. Click the "Financial Markup" tab.',
   'Financial Markup tab renders. Either markup rows are listed, or an empty state is shown. No error toast.',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

-- ADVANCED SETTINGS
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '14.1', 'Advanced Settings', 'Privacy and inclusions saved',
   'Advanced Settings fields (inclusions, exclusions, is_private, payment_terms) persist after save',
   'Confirms the advanced settings write path works end-to-end.',
   'A prime contract exists.',
   E'1. Open a prime contract detail page.\n2. Click "Advanced Settings" tab.\n3. Enter **Steel and concrete** in "Inclusions".\n4. Enter **FF&E** in "Exclusions".\n5. Set "Payment Terms" to **Net 30**.\n6. Click "Save".',
   'Success toast appears. After navigating away and back to the Advanced Settings tab, Inclusions shows "Steel and concrete", Exclusions shows "FF&E", and Payment Terms shows "Net 30".',
   'MEDIUM', 'scenario', '/67/prime-contracts'),

-- PAGINATION
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '15.1', 'Filters', 'Pagination controls',
   'Changing page size and navigating pages works correctly',
   'Confirms the pagination footer is functional.',
   'More than 25 prime contracts exist, OR change per-page to 5 to trigger pagination.',
   E'1. Navigate to /67/prime-contracts\n2. Change "Rows per page" to **5**.\n3. Click "Next page".',
   'Page shows 5 rows. Clicking Next Page advances to page 2. The page counter updates. Clicking Previous returns to page 1.',
   'LOW', 'scenario', '/67/prime-contracts'),

-- PERMISSIONS
  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '16.1', 'Permissions', 'Write permission gate',
   'A user without contracts write permission cannot create or edit contracts',
   'Confirms requirePermission("contracts","write") blocks unauthorized users.',
   'A second user account exists without contracts write permission.',
   E'1. Log in as the restricted user.\n2. Navigate to /67/prime-contracts\n3. Attempt to POST to /api/projects/67/contracts directly.',
   'POST returns 403 Forbidden. The "Create" button is either hidden or navigating to the form shows an access denied message.',
   'HIGH', 'scenario', '/67/prime-contracts'),

  ('a535e0b8-bb7c-4be0-a690-694f269d4d9f', '16.2', 'Permissions', 'Admin delete gate',
   'Deleting a contract requires admin permission',
   'Confirms requirePermission("contracts","admin") is enforced on DELETE.',
   'A user with write but not admin permission exists.',
   E'1. Log in as a write-only user.\n2. Navigate to the row actions on any contract.\n3. Attempt to delete.',
   'DELETE request returns 403 Forbidden. Error toast is shown. The contract is not deleted.',
   'HIGH', 'scenario', '/67/prime-contracts');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = 'a535e0b8-bb7c-4be0-a690-694f269d4d9f')
 where id = 'a535e0b8-bb7c-4be0-a690-694f269d4d9f';
