-- Seed: specifications SMOKE test suite
-- Generated by /test-scenario-audit specifications on 2026-04-20
-- Suite type: smoke | Supabase project: lgveqfnpkxvzbnnwuled

insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('specifications', 'smoke', 'Specifications — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <smoke_suite_id> with the id returned above before running.
/*
delete from public.test_cases where suite_id = '<smoke_suite_id>';

insert into public.test_cases
  (suite_id, test_number, category, subcategory, test_name,
   context_note, setup_steps, steps, expected_result, priority,
   test_type, start_url)
values
  ('<smoke_suite_id>', '1.1', 'Navigation', 'Page load', 'Open the Specifications page', 'Verifies list renders without runtime errors.', null, E'1. Log in as test1@mail.com\n2. Navigate to /67/specifications', 'Page loads with specs list or valid empty state.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.2', 'Navigation', 'Tabs', 'Switch Specifications / Revisions / Recycle tabs', 'Checks all top tabs load and route correctly.', null, E'1. Open /67/specifications\n2. Click Revisions tab\n3. Click Recycle tab\n4. Return to Specifications tab', 'Each tab loads without error.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.3', 'Navigation', 'Search', 'Search filters sections', 'Confirms search narrows list by section number/title.', E'- At least one section exists.', E'1. Open /67/specifications\n2. Enter a known term in search', 'Rows filter to matching records; clearing restores all.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.4', 'Navigation', 'Status filter', 'Status filter narrows specifications', 'Validates status filter behavior.', null, E'1. Open /67/specifications\n2. Apply status filter', 'Visible rows match selected status.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.5', 'Navigation', 'Area filter', 'Area filter narrows specifications', 'Validates area-based filtering.', null, E'1. Open /67/specifications\n2. Apply area filter', 'Rows update to selected area only.', 'MEDIUM', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.6', 'Navigation', 'Detail open', 'Clicking a section row opens detail', 'Verifies row navigation to detail route.', E'- At least one section exists.', E'1. Open /67/specifications\n2. Click first section row', 'Detail page opens with section details and revision history.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.7', 'Navigation', 'Add revision dialog', 'Add Revision dialog opens from detail page', 'Checks revision upload entrypoint.', E'- Existing specification section exists.', E'1. Open section detail\n2. Click Add Revision', 'Upload dialog opens with expected fields.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.8', 'Navigation', 'Download', 'Download current revision works', 'Confirms revision download action returns file/url.', E'- Section has a current revision.', E'1. Open section detail\n2. Click Download for current revision', 'Download starts or signed URL opens successfully.', 'HIGH', 'scenario', '/67/specifications'),
  ('<smoke_suite_id>', '1.9', 'Navigation', 'Revisions tab search', 'Revisions tab search filters revision rows', 'Checks revision search behavior on list page.', null, E'1. Open /67/specifications?spec_tab=revisions\n2. Search by section/file text', 'Revision rows filter to matching entries.', 'MEDIUM', 'scenario', '/67/specifications?spec_tab=revisions'),
  ('<smoke_suite_id>', '1.10', 'Navigation', 'Export/print', 'CSV export and print actions are available', 'Ensures report actions are wired on list.', null, E'1. Open /67/specifications\n2. Trigger CSV export\n3. Trigger Print', 'CSV download starts and print preview opens.', 'MEDIUM', 'scenario', '/67/specifications');

update public.test_suites
   set total_cases = (select count(*) from public.test_cases where suite_id = '<smoke_suite_id>')
 where id = '<smoke_suite_id>';
*/
