-- =============================================================================
-- Seed: Direct Costs — Smoke test suite
-- Generated by /test-scenario-audit on 2026-05-14
-- Supabase project: lgveqfnpkxvzbnnwuled
-- =============================================================================

-- 1. Upsert suite
insert into public.test_suites (tool_name, suite_type, display_name, total_cases)
values ('direct-costs', 'smoke', 'Direct Costs — Smoke', 0)
on conflict (tool_name, suite_type) do update set
  display_name      = excluded.display_name,
  last_generated_at = now()
returning id;

-- NOTE: Replace <SMOKE_SUITE_ID> below with the id returned above before re-running.
-- In practice this migration was applied via MCP; the suite id is 5ec70db8-dbf0-4e9c-a125-8e143b626efc.

do $$
declare
  v_suite_id uuid;
begin
  select id into v_suite_id
  from public.test_suites
  where tool_name = 'direct-costs' and suite_type = 'smoke';

  -- 2. Wipe existing cases
  delete from public.test_cases where suite_id = v_suite_id;

  -- 3. Insert cases
  insert into public.test_cases
    (suite_id, test_number, category, subcategory, test_name,
     context_note, setup_steps, steps, expected_result, priority,
     test_type, start_url)
  values
    (v_suite_id, '1.1', 'Navigation', 'Page load',
     'Open the Direct Costs page',
     'Checks the page renders without a blank screen or uncaught error.',
     null,
     E'1. Log in as test1@mail.com\n2. Open project "Vermillion Rise Warehouse" (ID 67)\n3. Click "Direct Costs" in the left sidebar',
     'The Direct Costs page loads. The table or an empty state is visible. No error banner is shown.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.2', 'Navigation', 'Table columns',
     'Summary table shows expected columns',
     'Confirms the default column set matches the spec: Date, Vendor, Type, Status, Amount.',
     E'- Direct Costs page is open.',
     E'1. On the Direct Costs page observe the table header row.',
     'Columns "Date", "Vendor", "Type", "Status", and "Amount" are visible in the table header.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.3', 'Navigation', 'Tab switching',
     'Switch to Summary by Cost Code tab',
     'Verifies the second tab loads without error.',
     E'- Direct Costs summary tab is active.',
     E'1. Click the "Summary by Cost Code" tab\n2. Wait for the page to stop loading.',
     'The cost-code grouped view renders without error. Rows are shown grouped by division/cost code.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.4', 'Navigation', 'Search',
     'Searching by vendor name filters the list',
     'Confirms the search bar narrows results to matching records.',
     E'- Direct Costs page is open with at least one record visible.',
     E'1. Type a known vendor name (or partial name) into the "Search vendor, invoice, date, amount, status..." field\n2. Wait for the list to update.',
     'Only records matching the typed value are shown. The row count decreases (or an empty state is shown if no match).',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.5', 'Navigation', 'Status filter',
     'Filtering by status narrows the list',
     'Confirms the Status filter dropdown works.',
     E'- Direct Costs page is open.',
     E'1. Click the filter icon in the toolbar\n2. Select "Approved" from the Status filter\n3. Apply the filter.',
     'Only records with status "Approved" are shown. Records with other statuses are no longer visible.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.6', 'Navigation', 'Empty state',
     'Filtering to zero results shows the empty state',
     'Checks the app renders a message instead of a blank table body when filters exclude everything.',
     E'- Direct Costs page is open.',
     E'1. Search for a string that matches nothing (e.g. "ZZZNOMATCH999")\n2. Wait for the list to update.',
     'An empty state message "No direct costs found" with hint text about adjusting filters is shown. No JS error in the console.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.7', 'Navigation', 'Detail page',
     'Clicking a row opens the detail page',
     'Verifies navigation from the list to a detail record works.',
     E'- Direct Costs page is open with at least one record.',
     E'1. Click the three-dots (⋯) action menu on any row\n2. Click "View".',
     'The direct cost detail page loads. Cost Information section is visible with fields: Total Amount, Date, Vendor, Invoice Number, Status badge.',
     'HIGH', 'scenario', '/67/direct-costs'),

    (v_suite_id, '1.8', 'Navigation', 'Read-only create',
     '"Add Direct Cost" leads to the read-only notice page',
     'Confirms that the create route does not show a form but instead explains records are Acumatica-synced.',
     E'- Direct Costs page is open.',
     E'1. Click "Add Direct Cost" in the page header.',
     'A page with title "Direct Costs Are Read-Only" is shown. A "Back to Direct Costs" button is present. No create form is displayed.',
     'HIGH', 'scenario', '/67/direct-costs');

  -- 4. Update total_cases
  update public.test_suites
     set total_cases = (select count(*) from public.test_cases where suite_id = v_suite_id)
   where id = v_suite_id;
end $$;
