import {
  getPreviewReviewCard,
  getPreviewReviewGroups,
} from "../preview-review-card";

describe("getPreviewReviewGroups", () => {
  it("extracts structured assistant write-preview review groups", () => {
    const card = getPreviewReviewCard({
      table: "change_events",
      fields: {
        project_id: 43,
        title: "Owner-requested lobby finish change",
      },
      reviewCard: {
        title: "Change event draft",
        subtitle: "Review the fields before Alleato creates the record.",
        recordType: "change_event",
        groups: [
          {
            title: "Required",
            fields: [
              {
                key: "project_id",
                label: "Project",
                value: "43",
                required: true,
              },
              {
                key: "title",
                label: "Title",
                value: "Owner-requested lobby finish change",
                required: true,
              },
            ],
          },
          {
            title: "Generated by Alleato",
            fields: [
              {
                key: "number",
                label: "Number",
                value: "Generated after confirmation",
                generated: true,
              },
            ],
          },
        ],
        notices: [
          {
            tone: "info",
            text: "Chat create writes the change event header.",
          },
        ],
      },
    });

    expect(card.title).toBe("Change event draft");
    expect(card.subtitle).toBe("Review the fields before Alleato creates the record.");
    expect(card.notices).toEqual([
      {
        tone: "info",
        text: "Chat create writes the change event header.",
      },
    ]);
    expect(card.groups).toEqual([
      {
        title: "Required",
        fields: [
          {
            key: "project_id",
            label: "Project",
            value: "43",
            helper: undefined,
            required: true,
            generated: false,
          },
          {
            key: "title",
            label: "Title",
            value: "Owner-requested lobby finish change",
            helper: undefined,
            required: true,
            generated: false,
          },
        ],
      },
      {
        title: "Generated by Alleato",
        fields: [
          {
            key: "number",
            label: "Number",
            value: "Generated after confirmation",
            helper: undefined,
            required: false,
            generated: true,
          },
        ],
      },
    ]);
  });

  it("keeps the legacy group helper available for existing call sites", () => {
    const groups = getPreviewReviewGroups({
      reviewCard: {
        groups: [
          {
            title: "Line items",
            fields: [
              {
                key: "line_items",
                label: "Line items",
                value: "Not supported by chat create yet",
                helper: "Use the full form after creation.",
              },
            ],
          },
        ],
      },
    });

    expect(groups).toEqual([
      {
        title: "Line items",
        fields: [
          {
            key: "line_items",
            label: "Line items",
            value: "Not supported by chat create yet",
            helper: "Use the full form after creation.",
            required: false,
            generated: false,
          },
        ],
      },
    ]);
  });

  it("ignores malformed review-card groups", () => {
    expect(
      getPreviewReviewGroups({
        reviewCard: {
          groups: [
            { title: "Broken", fields: [{ key: "title" }] },
            { fields: "not-fields" },
          ],
        },
      }),
    ).toEqual([]);
  });
});
