import { getPreviewReviewGroups } from "../preview-review-card";

describe("getPreviewReviewGroups", () => {
  it("extracts structured assistant write-preview review groups", () => {
    const groups = getPreviewReviewGroups({
      table: "change_events",
      fields: {
        project_id: 43,
        title: "Owner-requested lobby finish change",
      },
      reviewCard: {
        title: "Review change request",
        recordType: "change_event",
        groups: [
          {
            title: "Required",
            fields: [
              {
                key: "project_id",
                label: "Project",
                value: "43",
                required: true,
              },
              {
                key: "title",
                label: "Title",
                value: "Owner-requested lobby finish change",
                required: true,
              },
            ],
          },
          {
            title: "Generated by Alleato",
            fields: [
              {
                key: "number",
                label: "Number",
                value: "Generated after confirmation",
                generated: true,
              },
            ],
          },
        ],
      },
    });

    expect(groups).toEqual([
      {
        title: "Required",
        fields: [
          {
            key: "project_id",
            label: "Project",
            value: "43",
            helper: undefined,
            required: true,
            generated: false,
          },
          {
            key: "title",
            label: "Title",
            value: "Owner-requested lobby finish change",
            helper: undefined,
            required: true,
            generated: false,
          },
        ],
      },
      {
        title: "Generated by Alleato",
        fields: [
          {
            key: "number",
            label: "Number",
            value: "Generated after confirmation",
            helper: undefined,
            required: false,
            generated: true,
          },
        ],
      },
    ]);
  });

  it("ignores malformed review-card groups", () => {
    expect(
      getPreviewReviewGroups({
        reviewCard: {
          groups: [
            { title: "Broken", fields: [{ key: "title" }] },
            { fields: "not-fields" },
          ],
        },
      }),
    ).toEqual([]);
  });
});
