import {
  buildChangeRequestReviewCard,
  CHANGE_REQUEST_FIELD_GUIDE,
  renderChangeRequestFieldGuide,
  renderChangeRequestToolDescription,
} from "../change-request-field-guide";

describe("change request field guide", () => {
  it("documents required, optional, generated, and confirmation fields", () => {
    expect(CHANGE_REQUEST_FIELD_GUIDE.canonicalTool).toBe("createChangeEvent");
    expect(CHANGE_REQUEST_FIELD_GUIDE.aliases).toContain("change request");
    expect(CHANGE_REQUEST_FIELD_GUIDE.requiredFields.map((field) => field.name)).toEqual([
      "projectId",
      "title",
    ]);
    expect(CHANGE_REQUEST_FIELD_GUIDE.optionalFields.map((field) => field.name)).toEqual([
      "description",
      "scope",
      "type",
      "status",
    ]);
    expect(CHANGE_REQUEST_FIELD_GUIDE.generatedFields.map((field) => field.name)).toEqual([
      "number",
      "updated_at",
    ]);
    expect(CHANGE_REQUEST_FIELD_GUIDE.previewRule).toContain(
      "confirmed=false first",
    );
  });

  it("renders prompt and tool-description guidance from the same source", () => {
    expect(renderChangeRequestFieldGuide()).toContain(
      "Canonical tool: `createChangeEvent`",
    );
    expect(renderChangeRequestFieldGuide()).toContain(
      "projectId (Project): Numeric Alleato project id",
    );
    expect(renderChangeRequestToolDescription()).toContain("change request");
    expect(renderChangeRequestToolDescription()).toContain("projectId and title");
    expect(renderChangeRequestToolDescription()).toContain("confirmed=false first");
  });

  it("builds structured review-card metadata from preview fields", () => {
    const reviewCard = buildChangeRequestReviewCard({
      project_id: 43,
      title: "Owner-requested lobby finish change",
      description: "Owner asked to upgrade the lobby finish package.",
      scope: "owner_change",
      type: "potential_change",
      status: "open",
    });

    expect(reviewCard).toMatchObject({
      title: "Review change request",
      recordType: "change_event",
      groups: [
        {
          title: "Required",
          fields: [
            {
              key: "project_id",
              label: "Project",
              value: "43",
              required: true,
            },
            {
              key: "title",
              label: "Title",
              value: "Owner-requested lobby finish change",
              required: true,
            },
          ],
        },
        {
          title: "Optional",
          fields: expect.arrayContaining([
            expect.objectContaining({
              key: "scope",
              label: "Scope",
              value: "owner_change",
            }),
          ]),
        },
        {
          title: "Generated by Alleato",
          fields: expect.arrayContaining([
            expect.objectContaining({
              key: "number",
              label: "Number",
              value: "Generated after confirmation",
              generated: true,
            }),
          ]),
        },
      ],
    });
  });
});
