// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/dev-tools/generate-page-schema-fk-map.mjs
// Generated at: 2026-05-08T21:46:40.023Z

export const PAGE_SCHEMA_FK_TARGETS: Record<string, string> = {
  "change_event_line_items.budget_code_id": "budget_lines.id",
  "change_event_line_items.vendor_id": "companies.id",
};
